### ISSUE TITLE
Add sample script to add shims PATH to add to your .bashrc

### ISSUE THREAD

**Issue by jylenhof** [jdx/mise#1101]
Perhaps it could be nice to add this litlle script to a contrib directory or something else you think is better to avoid user to add with a bad script the PATH of its rtx shims PATH to its default PATH

Example with a script named `add_rtx_path_shims.bash`

```shell
#!/usr/bin/env bash

pathmunge() {
  if ! echo "${PATH}" | /usr/bin/grep -E -q "(^|:)$1($|:)"; then
    if [ "$2" = "after" ]; then
      PATH=${PATH}:$1
    else
      PATH=$1:${PATH}
    fi
  fi
}

pathmunge ~/.local/share/rtx/shims
```
You just need after to add these lines to your .bashrc to add rtx (previously installed with linux package management) :
```
source ~/add_rtx_path_shims.bash
source <(rtx completion bash)
```

**Comment by jylenhof** [comment]
Hi,
I've done a little PR for doc about this :
https://github.com/jdx/rtx-docs/pull/2

**Comment by texastoland** [comment]
@jdx I found a [dead simple pattern](https://github.com/texastoland/dotfiles/blob/73d99c98724da3f1d4406c8cf6417ae1e9d31273/.zshrc#L20-L23):

```sh
if [[ -t 0 ]]; then # terminal has stdin i.e. interactive
  eval "$(mise activate "$SHELL_NAME")"
else
  eval "$(mise activate --shims)"
fi
```

Explained in [my tweets](https://x.com/texastoland/status/1776030275023094159):

> Modern editors either receive their environment from the command line or more often read it similar to zsh -ilc env. That session is "interactive" (and login) in order to trigger all user configs. But that broke my dotfile's assumption. But how to check "interactive"? AFAICT [[ -t 0 ]] might be what I'm looking for because it fails (false) when editors are reading the environment

**Comment by jdx** [comment]
`mise activate --shims` should serve this purpose
