### ISSUE TITLE
rtx exec shorthand

### ISSUE THREAD

**Issue by mustafa0x** [jdx/mise#1205]
I find myself doing `rtx x <tool> -- <tool>` a fair bit. Can this perhaps be simplified?

**Comment by jdx** [comment]
I'm open to ideas. That said I really don't like that we could optimize `rtx x node -- node` but not `rtx x node -- npm`.

Of course a shell function could do this pretty easily:

```
rtxx() {
  rtx x $1 -- "$@"
}
```

**Comment by mustafa0x** [comment]
> That said I really don't like that we could optimize `rtx x node -- node` but not `rtx x node -- npm`.

`rtx x npm -- npm --version` seems to work?

> Of course a shell function could do this pretty easily

I need this where `<tool>` isn't already in $PATH. Namely, `ssh '<cmd>'` and in services.

**Comment by mustafa0x** [comment]
Ok, went with this for now. Seems to work decently.

```bash
echo -e '#!/bin/bash\nrtx x $1 -- "$@"' | \
sudo bash -c 'cat - > /usr/local/bin/rtxx && chmod +x /usr/local/bin/rtxx'
```
