### ISSUE TITLE
No AdoptOpenJDK 8.X versions available

### ISSUE THREAD

**Issue by a-glapinski** [jdx/mise#1208]
**Describe the bug**
AdoptOpenJDK 8.X versions are not available using core Java plugin.

**To Reproduce**
1. Run `rtx ls-remote java` command.
2. See that there are no AdoptOpenJDK 8.X versions available.

**Expected behavior**
AdoptOpenJDK 8.X versions should be available, because according to https://adoptium.net/support/ they should be supported at least until Nov 2026.

**`rtx doctor` output**

```text
rtx version:
  2023.12.23 macos-arm64 (2023-12-11)

build:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS
  Built: Mon, 11 Dec 2023 23:53:10 +0000
  Rust Version: rustc 1.74.0 (79e9716c9 2023-11-13) (Homebrew)
  Profile: release

shell:
  /opt/homebrew/bin/fish
  fish, version 3.6.4

rtx data directory:
  /Users/adrian.glapinski/.local/share/rtx

rtx environment variables:
  RTX_SHELL=fish

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "false", "jobs": "4", "legacy_version_file": "true", "legacy_version_file_disable_tools": "[]", "plugin_autoupdate_last_check_duration": "7d", "raw": "false", "trusted_config_paths": "[]", "verbose": "false", "yes": "false"}

config files:
  /Users/adrian.glapinski/.config/rtx/config.toml

plugins:
  go       (core)
  gradle   https://github.com/rfrancis/asdf-gradle.git#6dcf009
  java     (core)
  node     (core)
  python   (core)
  ruby     (core)
  sbt      https://github.com/bram2000/asdf-sbt.git#33f9637
  scala    https://github.com/asdf-community/asdf-scala.git#6de4edb

toolset:
  python@3.9, node@latest, scala@2.12.18, java@temurin-17.0.9+9, gradle@8.5, sbt@1.9.8

1 problem found:
new rtx version 2023.12.30 available, currently on 2023.12.23
```

**Comment by jdx** [comment]
the metadata I use comes from this: https://github.com/joschi/java-metadata. I'm not sure why this version is not in there.

**Comment by roele** [comment]
Usually you wont find ARM builds for JDK 8 versions for some of the vendors. Only a few vendors created ARM builds for older Java versions. Also installing an x64 version on ARM is currently not supported as available versions are filtered by architecture. 

As you can see on https://adoptium.net/temurin/archive/?version=8 there is no ARM build for macOS listed, only x64.

A possible workaround could be to download and extract the binary archive directly to ~/.local/share/mise/installs/java/adoptopenjdk-8u392-b08. You might need to move the content of `Content/Home` to the top directory and create a symlink from `Content/Home` to the top directory to make it work. Also note that running x64 Java will use the Rosetta emulation and will have a certain performance impact.

**Comment by jdx** [comment]
see https://mise.jdx.dev/tips-and-tricks.html#macos-rosetta for rosetta tips
