### ISSUE TITLE
Extend `install` with additional tasks

### ISSUE THREAD

**Issue by pepicrft** [jdx/mise#1268]
When contributing to a project, developers usually go through a two-step process:

- Make sure the system dependencies are present. This is something they can do easily with `rtx install`.
- Run other project setup steps like installing NPM dependencies (this is usually documented in the README).

I think it'd be great if `rtx` could help integrate the latter into the `rtx install`, which users of the tool will get familiar with. I think install could support being extended with additional tasks. Each of those tasks should include the command/script that needs to run and a way to verify if the task needs to run (this can be a future improvement).

**Comment by jdx** [comment]
there's now a [hook](https://mise.jdx.dev/hooks.html#preinstall-postinstall-hook) that could be used for this

**Comment by pepicrft** [comment]
> there's now a [hook](https://mise.jdx.dev/hooks.html#preinstall-postinstall-hook) that could be used for this

This is amazing :). Every repo of mine had an `install` task that I asked people to run when they set up the project for development.

Thanks @jdx
