### ISSUE TITLE
change task directory

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1270]
right now the directories `.config/rtx/tasks` and `.rtx/tasks` are hardcoded and cannot be changed. This should be configurable.

**Comment by jdx** [comment]
I think this makes sense just as a setting. I think serde has a serializer config that you could use to make it parse ":" as a deliminator

**Comment by Ajpantuso** [comment]
Is there a simple way for projects to share settings with contributors (within mise's conventions)? 

The ergonomics of a project using a different/additional task root and then requiring users to run some additional mise commands (other than install) seems a little lackluster.

Not a huge deal, but my experience working on declarative tools is people want that to mean zero imperative steps. The reality is probably minimal imperative steps, but we just hide those with helper scripts anyway.

**Comment by jdx** [comment]
You just put the settings onto .mise.toml. Is that what you mean?

**Comment by Ajpantuso** [comment]
Yes, which I now see is already possible :facepalm:. From the [docs](https://mise.jdx.dev/configuration.html#settings) I thought env vars were the only local override.

**Comment by jdx** [comment]
that said I thought through a downside with settings. Settings are global so you can't have different settings in different files. You might have a nested structure with different task directories in different directories.

I would like to avoid a new top-level `task_config` property but that might be the best we can do for now.

**Comment by Ajpantuso** [comment]
Trying to get insight from other projects:
- [Make](https://www.gnu.org/software/make/manual/html_node/Include.html)
    - Probably only good for deciding what not to do
- [Just](https://just.systems/man/en/chapter_53.html#imports)
    - More sane then _Make_, but still doesn't align well because a `justfile` is more script than config
- [Task](https://taskfile.dev/usage/#including-other-taskfiles)
    - Nice feature set and more config-like, but tasks are at the top-level of configuration so it's really just slicing the aggregate config across partials.
- [Gulp](https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles/#splitting-a-gulpfile)
    - Uses JS module structure so not really relevant here
    
So a few options I see are:
1. Add a top-level property just for configuring task directories
2. Add a top-level object for task config with task directory configuration as a property
3. Make the `Task` type an ADT(`enum`) and have a mix of a regular tasks and meta tasks which operate like _Task's_ `include` objects
4. Reserve a special task name like `_`, `_includes`, `__imports`, or some permutation of under/dunder/includes/imports which will be parsed like directives to configure task directories.
5. Same as 3, but with reserved names like 4.

Not sure what the least of all the evils is here, but #2 is probably the least invasive and still relatively extensible.

**Comment by jdx** [comment]
I think we should go with #2, we can always change this later
