### ISSUE TITLE
`rtx run lint:*`

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1271]
wildcards are supported as task dependencies but they should be allowed in `rtx run` CLI commands as well.

**Comment by roele** [comment]
currently the command takes multiple tasks and arguments
 `mise run <task> <args> ::: <task>* <args>`

this raises the question how this feature should treat arguments with multiple tasks. i assume that arguments would be applied to each wildcard match?

**Comment by jdx** [comment]
I'm not sure. I'm also not decided on how arguments are going to work generally. I'm considering making tasks accept arguments be configurable so you wouldn't always need `:::`. That's probably the most ill-defined part of tasks currently.

I do plan to make it possible to define task inputs too which will likely affect this.
