### ISSUE TITLE
visualize task dependency tree

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1272]
I want a way to see a graph of the dependency tree. I'm not at all sure what UI we could/should display here. If anyone knows of a CLI that is able to print decent graphs let me know (doesn't need to be rust)

**Comment by mkos11** [comment]
@jdx Use Graphviz for a CLI solution. Install it, create a DOT file specifying dependencies, then run `dot -Tpng` to visualize.

**Comment by roele** [comment]
Could start out as simple as

```
> brew deps --installed --tree
bat
├── libgit2
│   ├── libssh2
│   │   └── openssl@3
│   │       └── ca-certificates
│   └── openssl@3
│       └── ca-certificates
└── oniguruma
```

or

```
> mvn dependency:tree
[INFO] com.example:playground:jar:0.0.1-SNAPSHOT
[INFO] +- org.projectlombok:lombok:jar:1.18.24:provided
[INFO] +- com.google.code.gson:gson:jar:2.10.1:compile
[INFO] +- org.junit.jupiter:junit-jupiter:jar:5.8.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-api:jar:5.8.2:test
[INFO] |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  +- org.junit.platform:junit-platform-commons:jar:1.8.2:test
[INFO] |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-params:jar:5.8.2:test
[INFO] |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.8.2:test
[INFO] |     \- org.junit.platform:junit-platform-engine:jar:1.8.2:test
[INFO] +- org.mockito:mockito-core:jar:4.6.0:test
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.12.10:test
[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.12.10:test
[INFO] |  \- org.objenesis:objenesis:jar:3.2:test
[INFO] +- org.mockito:mockito-inline:jar:4.6.0:test
[INFO] \- org.mockito:mockito-junit-jupiter:jar:4.6.0:test
```

**Comment by jdx** [comment]
gah I can't find it now but I did find a task runner or something similar that had a nice command for this.

I like both ideas. I think personally I prefer the in-CLI tree thing but I actually think we should support both with a flag probably. Perhaps surprisingly, I think the graphviz thing would be easiest since I already build a graph data structure with a crate that supports exporting to that format.

**Comment by jdx** [comment]
added the "help wanted" tag since I think this is a good task for an external contributor. You'll need to be at least a bit comfortable in rust though (easy tasks I mark "good first issue" and this isn't one). However the nice thing about it is that it is mostly self-contained so you don't need to understand this particular codebase that well to do it.

The graph data structure gets created here: https://github.com/jdx/mise/blob/ab6e912e98b429e79494ae65a9d37c3633bdd0ac/src/cli/run.rs#L432

What would need to be done:
1. that graph needs to be moved from the `mise run` CLI command into a shared library, perhaps `src/tasks.rs` or maybe `src/tasks/graph.rs`
2. a new CLI command should be created, maybe `mise tasks graph` or `mise tasks --graph`. Not sure, open to suggestions.

As always, reach out in the discord if you have any questions.
