### ISSUE TITLE
"demand" library needs work

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1275]
this is actually the wrong repo for this but figured I would post it to get more eyes on it

I wrote this UI prompt library based on [huh?](https://github.com/charmbracelet/huh) for Go: https://github.com/jdx/demand

It solves the problems I had for rtx (and I plan to use it a lot more too), but if someone new to rust or just someone looking for an easy OSS project wanted to contribute I think it would be a great project. What makes it easy is I basically just want "huh?" in rust so you can just read that project's source code basically and fill in the gaps that are missing. It's not difficult work but it just isn't something that's interesting me at the moment.

I do think it would be popular in the rust space though—assuming we took care of these table-stakes. Charm really nailed the UX on this.

Here's some examples of what it needs:

* more themes
* input/text components
* better examples (in particular the "select" example is just a clone of multiselect's)
* replicate the form/group functionality (this is significantly harder than the rest though)

**Comment by jdx** [comment]
kudos @roele who did most of the legwork here and demand just hit 1.0!

**Comment by roele** [comment]
@jdx thanks for the opportunity and all your support!
