### ISSUE TITLE
task inputs

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1276]
tasks can accept arguments (sort of) but I think this could be more formally defined. Maybe this could be paired with demand to have tasks automatically prompt as well as github actions workflow_dispatch. It would also be nice to display in `rtx tasks ls` and if rtx was able to generate readme docs for tasks.

**Comment by jdx** [comment]
noted that this will likely be a breaking change (in tasks which is marked as experimental), so if you're using the current way that arguments work with tasks expect it to change significantly in an upcoming release

**Comment by iilyak** [comment]
As a source of inspiration there are few interesting projects 

- https://github.com/go-task/task
- https://github.com/moonrepo/moon
- https://github.com/rash-sh/rash
- https://github.com/kcmerrill/alfred
