### ISSUE TITLE
implement plugin autoupdating

### ISSUE THREAD

**Issue by jdx** [jdx/mise#128]
plugins should have some form of autoupdating, of course this should be something the user can opt out of

As an alternative, perhaps just notifying about updates would be enough. asdf has discussed this: 
* https://github.com/asdf-vm/asdf/issues/725

**Comment by codykrieger** [comment]
Personally, I'd advocate for automatically attempting to update a plug-in when attempting to install a runtime that can't be found.

I scratched my head for a few minutes at this one before realizing I needed to update the `ruby` plug-in in order to “see” v3.2.1:

```
% rtx install -a
⢄ Installing runtime: ruby@3.2.1...Version not found
[ERROR] [ruby] script exited with non-zero status: exit code 1
[ERROR] Run with RTX_DEBUG=1 for more information.
[ERROR] rtx 1.9.0 macos-arm64 (built 2023-02-13)
```

**Comment by jdxcode** [comment]
ruby appears to be [unique here](https://github.com/asdf-vm/asdf-ruby/blob/master/lib/utils.sh). Most languages that I've seen download all of the versions so you don't have to update the plugin to just get a new version.

**Comment by codykrieger** [comment]
Ah. Good to know.

**Comment by airtonix** [comment]
should be opt in tbh. or is reproducibility not a goal of mise?

are suprising bugs resulting from shifting outputs from newer plugins a desired goal?
