### ISSUE TITLE
rtx swallows terminal output exit codes

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [jdx/mise#1283]
**Describe the bug**

Adding `eval "$(rtx activate zsh)"` to ~/.zshrc swallows all exit codes, so exit code outputs are no longer show, e.g. `random_command` doesn't say command does not exist.

Removing that line from ~/.zshrc fixes the issue.

**To Reproduce**

```shell
brew install rtx
echo 'eval "$(rtx activate zsh)"' >> ~/.zshrc
jakshl4iu3erlndjfvdubh  # random non existent command  
```

This should show a non zero exit code, but it doesn't show anything.

**Expected behavior**

**`rtx doctor` output**

```text
rtx version:
  2023.12.39 macos-arm64 (2023-12-26)

build:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS
  Built: Tue, 26 Dec 2023 16:18:03 +0000
  Rust Version: rustc 1.74.0 (79e9716c9 2023-11-13) (Homebrew)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin23.0)

rtx data directory:
  /Users/andrew/.local/share/rtx

rtx environment variables:
  RTX_SHELL=zsh

settings:
  {
    "experimental": false,
    "color": true,
    "always_keep_download": false,
    "always_keep_install": false,
    "legacy_version_file": true,
    "legacy_version_file_disable_tools": [],
    "plugin_autoupdate_last_check_duration": "7d",
    "trusted_config_paths": [],
    "log_level": "info",
    "trace": false,
    "debug": false,
    "verbose": false,
    "quiet": false,
    "asdf_compat": false,
    "jobs": 4,
    "shorthands_file": null,
    "disable_default_shorthands": false,
    "disable_tools": [],
    "raw": false,
    "yes": false,
    "task_output": null,
    "not_found_auto_install": true,
    "ci": false
  }

config files:
  /Users/andrew/.config/rtx/config.toml
  /Users/andrew/Work/Code/projects/project/project/.rtx.toml

plugins:
  bun      (core)
  deno     (core)
  erlang   (core)
  go       (core)
  java     (core)
  node     (core)
  python   (core)
  ruby     (core)

toolset:
  node@20.10.0, python@3.12.1

No problems found
```

**Additional context**

I use Warp as a terminal, but I used the regular terminal as well and can reproduce there as well.

**Comment by jdx** [comment]
I'm not seeing this behavior:

```
~ ❯ zsh
e
~
❯ rtx -v
2023.12.39 macos-arm64 (2fbe4b9 2023-12-26)
❯ lkwjefl
zsh: command not found: lkwjefl

~
❯ echo $status
127
```

It's likely to do with the not found check though, which you can disable with `rtx settings set not_found_auto_install false`. However, I'm curious why it isn't working. Do you have an existing `command_not_found_handler` set?

**Comment by Andrew-Chen-Wang** [comment]
>

> However, I'm curious why it isn't working. Do you have an existing command_not_found_handler set?

I'm very new to rtx, so I doubt it. The only things in my rtx.toml is:

```
[tools]
node = ['20.10.0']
python = {version='3.12.1', virtualenv='.venv'}
```

**Comment by Andrew-Chen-Wang** [comment]
I've directly added to `~/.zshrc`:
```shell
command_not_found_handler() {
    echo "zsh: command not found: $@"
    return 127
}
```
to my command line, and it is now outputting as expected and is also compatible with rtx, Warp, ZSH, and Pants.

Still unsure why I needed to add the handler though :(

**Comment by Andrew-Chen-Wang** [comment]
Ok so after commenting out the handler and running `unset command_not_found_handler`, it is still functioning properly :P :D
