### ISSUE TITLE
Ruby plugin based on asdf is not compatible

### ISSUE THREAD

**Issue by megatux** [jdx/mise#1293]
**Describe the bug**

Reinstalled the Ruby plugin.
Ran `bundle` command from a new Rails app. (bundle is a command to install the libraries define in the _Gemfile_ file)
It fails with:

```
bundle
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::ENOENT: No such file or directory - asdf
  /Users/megatux/.local/share/rtx/plugins/ruby/rubygems-plugin/rubygems_plugin.rb:5:in ``'
  /Users/megatux/.local/share/rtx/plugins/ruby/rubygems-plugin/rubygems_plugin.rb:5:in `install'
  /Users/megatux/.local/share/rtx/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.21/lib/bundler/installer.rb:89:in `block in run'
```
Checking the file `rtx/plugins/ruby/rubygems-plugin/rubygems_plugin.rb` you see this code:

```ruby
module ReshimInstaller
  def install(options)
    super
    # We don't know which gems were installed, so always reshim.
    `asdf reshim ruby`
  end
end

if defined?(Bundler::Installer)
  Bundler::Installer.prepend ReshimInstaller
else
  Gem.post_install do |installer|
    # Reshim any (potentially) new executables.
    installer.spec.executables.each do |executable|
      `asdf reshim ruby #{RUBY_VERSION} bin/#{executable}`
    end
  end
  Gem.post_uninstall do |installer|
    # Unfortunately, reshimming just the removed executables or
    # ruby version doesn't work as of 2020/04/23.
    `asdf reshim ruby` if installer.spec.executables.any?
  end
end
```

It shows that it executes ``asdf reshim ruby`` and that's not compatible with _rtx_ AFAIK.

Is there another Ruby plugin?

**Expected behavior**

`blundle` command should work fine.

**`rtx doctor` output**

```text
```
(empty)

**Additional context**
- Mac OSX, ARM64, zsh

**Comment by jdx** [comment]
you just use the core plugin https://rtx.jdx.dev/lang/ruby.html
