### ISSUE TITLE
no such file or directory: ~/.local/share/mise/bin/mise

### ISSUE THREAD

**Issue by bklebe** [jdx/mise#1339]
**Describe the bug**
There's no `bin` directory in the mise folder.

**To Reproduce**
I had an `rtx` install via Homebrew, I uninstalled it from Homebrew and installed `mise`. At first I couldn't get `mise` to activate at all, and then I ran `eval "$(mise activate zsh)"` manually and now I have a `mise` directory with no `bin` folder, and no `~/.local/share/rtx` anymore either.

**Expected behavior**
`.local/share/rtx` is properly migrated, including the `bin` folder.

**`mise doctor` output**

```text
mise version:
  2024.1.0 macos-arm64 (2024-01-02)

build:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS
  Built: Tue, 2 Jan 2024 23:47:11 +0000
  Rust Version: rustc 1.75.0 (82e1608df 2023-12-21) (Homebrew)
  Profile: release

shell:
  /opt/homebrew/bin/zsh
  zsh 5.9 (arm-apple-darwin22.1.0)

mise data directory:
  /Users/bklebe/.local/share/mise

mise environment variables:
  (none)

settings:
  {
    "experimental": false,
    "color": true,
    "always_keep_download": false,
    "always_keep_install": false,
    "legacy_version_file": true,
    "legacy_version_file_disable_tools": [],
    "plugin_autoupdate_last_check_duration": "7d",
    "trusted_config_paths": [],
    "log_level": "info",
    "trace": false,
    "debug": false,
    "verbose": false,
    "quiet": false,
    "asdf_compat": false,
    "jobs": 4,
    "shorthands_file": null,
    "disable_default_shorthands": false,
    "disable_tools": [],
    "raw": false,
    "yes": false,
    "task_output": null,
    "not_found_auto_install": true,
    "ci": false,
    "env_file": null,
    "cd": null
  }

config files:
  /Users/bklebe/.config/mise/config.toml

plugins:
  bun          (core)
  deno         (core)
  dotnet       https://github.com/hensou/asdf-dotnet#da92129
  elixir       https://github.com/asdf-vm/asdf-elixir.git#a4c42e1
  erlang       https://github.com/asdf-vm/asdf-erlang.git#6744df7
  go           https://github.com/rtx-plugins/rtx-golang.git#23c62dd
  java         https://github.com/rtx-plugins/rtx-java.git#6c6790c
  make         https://github.com/yacchi/asdf-make.git#2f12c4d
  maven        https://github.com/halcyon/asdf-maven.git#83fb4db
  node         (core)
  php          https://github.com/asdf-community/asdf-php.git#1eaf4de
  poetry       https://github.com/rtx-plugins/rtx-poetry.git#916c061
  python       (core)
  ruby         (core)
  shellcheck   https://github.com/luizm/asdf-shellcheck.git#780d78d
  terraform    https://github.com/asdf-community/asdf-hashicorp.git#197e3ec

toolset:
  go@1.21.3, python@3.12.0, poetry@1.7.1, elixir@1.15.7-otp-26, erlang@26.1.2, java@21.0.1

1 problem found:
mise is not activated, run [33mmise help activate[0m or
read documentation at [4mhttps://mise.jdx.dev[0m for activation instructions.
Alternatively, add the shims directory [36m/Users/bklebe/.local/share/mise/shims[0m to PATH.
Using the shims directory is preferred for non-interactive setups.

```

**Comment by bklebe** [comment]
I just ran a standalone install with `curl https://mise.jdx.dev/install.sh | sh` and that seems to have fixed it, or at least installed another copy at `.local/share/mise/bin/mise`. Curious whether that copy of mise will be kept up to date with the version in Homebrew, though.

**Comment by jdx** [comment]
`~/.local/share/mise/bin/mise` is something that `install.sh` specifically creates. If you install via homebrew you won't have that since the CLI lives in /opt/homebrew/bin/mise. This shouldn't be a problem, could I ask what you were experiencing that led you to need the CLI in that location?

I suspect it may be because the getting started guide uses that location: https://mise.jdx.dev/getting-started.html#_2-add-mise-shims-to-path but that's because it also assumes you're using install.sh. I have been thinking about a way to organize that doc to make this clearer.

**Comment by jdx** [comment]
FYI for new installs this is being moved to `~/.local/bin/mise` which is cleaner and a fairly common convention we want to reuse. The old directory will still work but docs are moved to the new location.

**Comment by bklebe** [comment]
> Suffice to say, if mise is on PATH then you just need to use eval "$(mise activate zsh)" and don't need the full path.

Ahhh yes, that makes sense. Sorry, I don't know why this didn't click for me.

> I have been thinking about a way to organize that doc to make this clearer.

The ASDF docs have a whole list of docs covering a matrix of shells and package managers: https://asdf-vm.com/guide/getting-started.html#_3-install-asdf. It's not very elegant but gets the job done, I guess :)

Thanks so much for the help! And I love the rename, too — I always had trouble finding the repo with search engines.
