### ISSUE TITLE
arch package rename

### ISSUE THREAD

**Issue by inverse** [jdx/mise#1344]
**Describe the bug**

Since `rtx` got renamed to `mise` there are two packages in the AUR which should probably be deprecated properly.

- https://aur.archlinux.org/packages/rtx
- https://aur.archlinux.org/packages/rtx-bin

Looking at the structure for `PKGBUILD` it looks like the new scripts should include a replaces section.

See: https://wiki.archlinux.org/title/PKGBUILD#replaces

**Comment by jdx** [comment]
ah thanks for the pointer, I'll add this config
