### ISSUE TITLE
Not able to install mise via nixpkgs

### ISSUE THREAD

**Issue by supaspoida** [jdx/mise#1362]
I am using https://nixpacks.com to build containers for CI/CD pipelines and was previously able to install `rtx` from nixpkgs by adding it to the `nixPkgs` list as documented here: https://nixpacks.com/docs/configuration/file#nix-packages

When I try to do the same with `mise` my builds fail because they're unable to find the package. When I search via the website I can confirm `mise` is not present: https://search.nixos.org/packages?channel=23.11&show=rtx&from=0&size=50&sort=relevance&type=packages&query=mise

Compare to a search for `rtx` where the package shows up as expected: https://search.nixos.org/packages?channel=23.11&show=rtx&from=0&size=50&sort=relevance&type=packages&query=rtx

Is this expected at this point, and are there any plans to start publishing to nixpkgs under the new name if so?

Thanks!

**Comment by jdx** [comment]
I don't maintain the packaging for nix. I would have a look at the package, file an issue on [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/rtx/default.nix) and tag the maintainers

**Comment by supaspoida** [comment]
Got it, I'm new to the nix ecosystem so thanks for pointing me toward the right place!
