### ISSUE TITLE
Can't check signature of install script

### ISSUE THREAD

**Issue by atusy** [jdx/mise#1369]
**Describe the bug**

By following guide <https://mise.jdx.dev/getting-started.html#install-sh>, `Can't check signature: No public key` error occurs.

```
$ gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 0x29DDE9E0
$ curl https://mise.jdx.dev/install.sh.sig | gpg --decrypt > install.sh
gpg: Signature made Fri Jan  5 08:13:46 2024 JST
gpg:                using RSA key 24853EC9F655CE80B48E6C3A8B81C9D17413A06D
gpg: Can't check signature: No public key
```

**To Reproduce**

See above.

**Expected behavior**

Should be installed without problems.

**Comment by jdx** [comment]
Ah yes, I changed the gpg key with the project rename so I need to update that

**Comment by jdx** [comment]
https://github.com/jdx/mise-docs/commit/b28c77fd4f0be8d492e9db01db02fe3667942cfd

**Comment by atusy** [comment]
Thanks! Perfect!
