### ISSUE TITLE
`$` in env vars fails

### ISSUE THREAD

**Issue by mustafa0x** [jdx/mise#1370]
**.mise.toml**
```
[env.mise]
file = '.env'
```

**.env**
```
SEPARATOR="$"
```

**error**
```
mise error parsing config file: ~/dev/collab/.mise.toml
mise Error parsing line: '"$"', error at line index: 2
```

escaping fixes, as do single quotes, but `export ...`, direnv, docker compose, and systemd services all work fine with `SEPARATOR="$"`.

**Comment by jdx** [comment]
You'll need to take this upstream to dotenvy since it's not something I can control at all

**Comment by jdx** [comment]
well, that's not entirely accurate. I could use a different library or fork that one—but I really don't wan tto

**Comment by mustafa0x** [comment]
For posterity,

> The Ruby implementation of dotenv follows follows bash as closely as possible, which means $ needs to be escaped unless it is in single quotes.

https://github.com/bkeepers/dotenv/issues/214
