### ISSUE TITLE
Sources/outputs can't point to a specific path

### ISSUE THREAD

**Issue by fiadliel** [jdx/mise#1372]
**Describe the bug**
Sources and outputs are used as inputs to "globwalk", which does a recursive search for files matching the string. There doesn't seem to be a way to opt out of this, and provide a real relative path.

**To Reproduce**
Include a config which includes `sources` and `outputs` like
```
[tasks.bug]
sources = [ 'style.css' ]
outputs = [ 'outputs/style.css' ]
```

This task will always trigger, because `outputs/style.css` is also included in the last modified calculation for `sources`.

**Expected behavior**
It should be possible to specify an actual path, rather than a search path. The behavior and syntax should be clear in documentation. One approach used by some libraries (e.g. `glob`) is that `**/` triggers a subdirectory match.

**Comment by jdx** [comment]
not surprising, I forgot to test with non-wildcards

**Comment by fiadliel** [comment]
Understood 🙂 Not a blocker for me to use, I was just scratching my head over why detection change didn't seem to be working.
