### ISSUE TITLE
PATH updating seems a bit dodgy

### ISSUE THREAD

**Issue by defhacks** [jdx/mise#1380]
**Describe the bug**
relative or unqualified paths to mise alter $PATH unexpectedly

**To Reproduce**

Confirmed behaviour in both bash/zsh

relative paths yield an interesting result:
```
% ./mise activate zsh| grep PATH
export PATH=".:$PATH"
export __MISE_ORIG_PATH="$PATH"
```

but possibly more subtle and concerning is this case:
```
% mise activate zsh | grep PATH
export PATH=":$PATH"
export __MISE_ORIG_PATH="$PATH"
```

I was surprised to that both bash/zsh seem to interpret the empty string entry being pre-pended to $PATH here as adding the current working directory to $PATH.

I would propose patches to fix, but when I modified my local copy to prevent this behavior, I saw a comment about direnv, which I don't really use so I thought I'd just kick off the discussion rather than propose something that causes grief to direnv users.

**Comment by jdx** [comment]
do you have experimental enabled? that actually goes down a completely different code path (see #863 if you're curious what)
