### ISSUE TITLE
Osquery and Cnquery Plugin Install

### ISSUE THREAD

**Issue by Niba-nazar** [jdx/mise#1401]
Hi,

I would like to make use of mise to install osquery and cnquery.  Is this plugin already there ? if not would like those plugins to be hosted on mise.

```
mise install cnquery
Error:   x No repository found for plugin cnquery


mise install osquery
Error:   x No repository found for plugin osquery


mise install osqueryd
Error:   x No repository found for plugin osqueryd

```

**Comment by jdx** [comment]
perhaps you should make them yourself: https://github.com/asdf-vm/asdf/blob/master/docs/plugins/create.md
