### ISSUE TITLE
trusted_config_paths no longer expands ~ into users home directory

### ISSUE THREAD

**Issue by ciiqr** [jdx/mise#1402]
**Describe the bug**
The paths in the `trusted_config_paths` setting used to be expanded with the users home directory (ie. from `~/work/my-trusted-projects` into `/home/jdx/work/my-trusted-projects`). This is no longer happening on the latest version.

**To Reproduce**
- created `~/.config/mise/settings.toml` with:
```toml
trusted_config_paths = [
    '~/work/my-trusted-projects',
]
```
- cd into a relevant project
```bash
$ cd ~/work/my-trusted-projects
Error:   × error parsing config file: ~/work/my-trusted-projects/.mise.toml
  ╰─▶ Config file is not trusted.
      Trust it with `mise trust`.

Error:   × error parsing config file: ~/work/my-trusted-projects/.mise.toml
  ╰─▶ Config file is not trusted.
      Trust it with `mise trust`.
```

**Expected behavior**
Paths should be expanded with the users home directory.

**Additional context**
```
$ mise -v    
2024.1.12 macos-arm64 (2024-01-07)
```

**Comment by jdx** [comment]
huh this is strange, I think it actually broke before the settings change. In any case, it works with my patch now.
