### ISSUE TITLE
Changes in behavior for ~/.tool-versions (and guidance for migrating to ~/.config/mise/config.toml?)

### ISSUE THREAD

**Issue by fvsch** [jdx/mise#1405]
**Describe the bug**

Mise's behavior with regard to the `~/.tool-versions` file changed recently.

Before: it would set the default tool versions for the current user.
Now: it is only applied in terminal sessions where the current folder is the home directory or a descendant of the home directory.

In my case, this broke a couple workflows:

- My code projects live on a different volume, mounted at `/Volumes/Code/*`.
- I sometimes use tools installed with rtx/Mise when dealing with files on external drives, which also have their own mount points (e.g. `/Volumes/MyExternalSSD/*`).

To fix this issue, I replaced my `~/.tool-versions` file:

```
node 20.10
ruby 3.1
```

with a `[tools]` config in `~/.config/mise/config.toml`:

```toml
[tools]
node = '20.10'
ruby = '3.1'
```

and now I am getting the same behavior as before.

This change in behavior is not necessarily bad, if it was indeed intended to have all config files scoped to their path, and use `~/.config/mise/config.toml` as the only source of global config.

But the lack of feedback from Mise was not ideal for me. :)

A few ideas:

1. Add a warning (at the start of the session?) when a `~/.tool-versions` file is found. Pros: visible. Cons: can be verbose or undesired, and then it triggers a need for a way to silence that warning, which adds even more complexity.
2. Add a warning in the `mise ls` output when a `~/.tool-versions` file, or other legacy `~/.[tool]-version` files are found, and the result of `mise ls` is that no tool was exposed in `$PATH`.
3. Do nothing, because all the ideas above add to the maintenance burden and might not be worth it (depending on how many users are actually affected). ^^

For the “warn in the `mise ls` output”, here is what the command output looked like for me with an ignored `~/.tool-versions` file:

```sh
/Volumes/Code/some/project $ mise ls
Plugin  Version  Config Source Requested
node    20.10.0
ruby    3.1.4
```

and after the fix:

```sh
/Volumes/Code/some/project $ mise ls
Plugin  Version  Config Source              Requested
node    20.10.0  ~/.config/mise/config.toml 20.10
ruby    3.1.4    ~/.config/mise/config.toml 3.1
```

A couple design notes:

- When the table header is `Plugin  Version  Config Source Requested`, I am reading “Config”, “Source” and “Requested” as three columns. Suggestion: use sentence case (“Config source”), and use two spaces between the “Config source” and “Requested” columns (vs one space currently).
- If there is no config source found, maybe the “Config source” column should say something like “(no config)” or “(none found)” instead of being blank? It would have helped me figure out that the `~/.tool-versions` was not read in this context.

**`mise doctor` output**

```text
/Volumes/Code $ mise doctor

mise version:
  2024.1.12 macos-arm64 (2024-01-07)

build:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS
  Built: Sun, 7 Jan 2024 13:15:45 +0000
  Rust Version: rustc 1.75.0 (82e1608df 2023-12-21) (Homebrew)
  Profile: release

shell:
  /opt/homebrew/bin/fish
  fish, version 3.7.0

mise data directory:
  /Users/florens/.local/share/mise

mise environment variables:
  MISE_SHELL=fish

mise settings file:
  ~/.config/mise/settings.toml

settings:
  {
    "all_compile": false,
    "always_keep_download": false,
    "always_keep_install": false,
    "asdf_compat": false,
    "color": true,
    "disable_default_shorthands": false,
    "disable_tools": [],
    "experimental": false,
    "jobs": 4,
    "legacy_version_file": true,
    "legacy_version_file_disable_tools": [],
    "node_compile": false,
    "not_found_auto_install": true,
    "paranoid": false,
    "plugin_autoupdate_last_check_duration": "7d",
    "python_compile": false,
    "python_venv_auto_create": false,
    "raw": false,
    "shorthands_file": null,
    "task_output": null,
    "trusted_config_paths": [],
    "quiet": false,
    "verbose": false,
    "yes": false,
    "ci": false,
    "cd": null,
    "debug": false,
    "env_file": null,
    "trace": false,
    "log_level": "info"
  }

config files:
  /Users/florens/.config/mise/config.toml

plugins:
  bun      (core)
  deno     (core)
  go       (core)
  java     (core)
  node     (core)
  php      https://github.com/asdf-community/asdf-php.git#1eaf4de
  python   (core)
  ruby     https://github.com/rtx-plugins/rtx-ruby.git#8001be4

toolset:


No problems found
```

**Comment by jdx** [comment]
yes this is a bug. I'll have it patched today

**Comment by jdx** [comment]
Looking at this a bit more, I think I'm going to admit defeat on this. Before there was a lot of logic around this to disable reading it as a global config, but I think it's just easiest for everyone if I just retain the asdf style of using that file everywhere, in all conditions, indefinitely.

Not the way I would've designed it, but I don't think it's possible for me to change it without causing a headache for people coming from asdf and I think there will be people coming to mise from asdf for years to come.
