### ISSUE TITLE
non-precompiled python versions not installable under experimental=1

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1411]
I noticed that mise only shows precompiled versions when it is defaults to precompiled. What should happen is like with node where it displays all versions, precompiled or not, and if it is a version with matching precompiled then it will use the precompiled but use python-build otherwise.

If you run into this the workaround is a bit clunky (might have to be on a single line like that because reasons):

```sh
$ mise cache clear && MISE_PYTHON_COMPILE=1 mise install pypy3
```

**Comment by razvanazamfirei** [comment]
This affected `latest`, `ls-remote` and `outdated`. The command above fixed the issue temporarily. Once the cache was refreshed, it reverted to only showing pre-compiled versions. The issue seems to be solved after setting MISE_PYTHON_COMPILE=1 as a persistent env variable.

**Comment by ericbn** [comment]
@razvanazamfirei, I think you can also do
```
mise settings set python_compile 1
```
instead of setting a persistent MISE_PYTHON_COMPILE=1 environment variable.
