### ISSUE TITLE
Mise missing from nix package repo?

### ISSUE THREAD

**Issue by unredundant** [jdx/mise#1416]
**Describe the bug**
Hey, the docs seem to indicate that mise should be available from nixos 23.05 and on, but, i do not see it available in the package repo https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=mise

**To Reproduce**
see url ^

**Expected behavior**
It should be there :)

**Additional context**
N/A

**Comment by jdx** [comment]
yeah that's perhaps should be updated. rtx is in there but someone will need to rename it
