### ISSUE TITLE
Local settings.toml

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1426]
It should be possible to have project-local settings, e.g.:

```sh
$ cd ~/src/myproj
$ mkdir -p .config/mise
$ cat <<EOF >.config/mise/settings.toml
experimental = true
EOF
```

Related to #1425

**Comment by rouge8** [comment]
This doesn't appear to be working?

```
❯ mise --version
2024.1.30 macos-arm64 (2024-01-27)
```

```
❯ cat .config/mise/settings.toml 
experimental = true
legacy_version_file = true
```

```
❯ mise settings get experimental 
false
```

**Comment by jdx** [comment]
use `.config/mise/config.toml`. This issue was written wrong—I'm moving away from using `settings.toml` in favor of having a single config file

**Comment by rouge8** [comment]
Ah yes, that fixes it!
