### ISSUE TITLE
Switching between pre-compiled and built latest Python

### ISSUE THREAD

**Issue by Aeron** [jdx/mise#1429]
As usual, I ran `mise upgrade` to upgrade my stuff. And it decided to replace my Python 3.12.1 installed previously with the pre-compiled one. The pre-compiled version is 3.12.0—that’s weird already because [indygreg/python-build-standalone](https://github.com/indygreg/python-build-standalone) has 3.12.1.

But ok, the warning message says this:

```text
if you experience issues with this python, switch to python-build
by running: mise settings set python_compile 0
```

The wrong version is a problem, so I ran the command. And then `mise upgrade` again. Nothing. I explicitly ran `mise upgrade python@latest` and got nothing again. Ok, then `mise upgrade python@3.12.1`, so I got the following:

```text
Error:   × no precompiled version found for python@3.12.1
```

Pre-compiled, huh? Ok, the setting must be `true`, so the correct command is `mise settings set python_compile 1`. That’s a minor thing.

Will it install the proper version now? Another go for the `mise upgrade` and nothing. Ok, I will be explicit then—let’s go with `mise upgrade python@3.12.1` again. It downloads and builds just fine. Great! But running `mise ls` gave me this:

```text
Plugin  Version            Config Source              Requested
go      1.21.6             ~/.config/mise/config.toml latest   
python  3.12.0                                                 
python  3.12.1 (outdated)  ~/.config/mise/config.toml latest   
rust    1.75.0             ~/.config/mise/config.toml latest   
zig     0.11.0             ~/.config/mise/config.toml latest  
```

Outdated? This can’t be true. Another go for the `mise up` to be sure. And it started downloading 3.12.0, the source code now. If it ends, it removes 3.12.1 and installs 3.12.0.

So, Mise-en-place (kind of) refuses to recognize the existence of 3.12.1 in any form. It doesn’t see the pre-compiled latest version. It doesn’t want to download the latest source code archive. And it marks the forcefully installed latest version as outdated.

And the fun part. After I ran `mise doctor` to write this issue, my installed Python 3.12.1 is no longer an outdated, and everything works. I’m very baffled at the moment.

Could it be a cached version value of some sort? But it had a chance to see the newer pre-compiled version. I’m not that familiar with Mise code to speculate on this part. But something clearly worked the wrong way here.

**To Reproduce**
 - Have a built Python 3.12.1 installed previously
 - Set the experimental setting to true if not yet
 - Run `mise upgrade`
 - Try to keep 3.12.1

**Expected behavior**
I expect to get or keep the latest version, at least. I expect to see the correct warnings along the way.

**`mise doctor` output**

```text
mise version:
  2024.1.14 macos-arm64 (2024-01-09)

build:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS
  Built: Tue, 9 Jan 2024 02:34:36 +0000
  Rust Version: rustc 1.75.0 (82e1608df 2023-12-21) (Homebrew)
  Profile: release

shell:
  /opt/homebrew/bin/fish
  fish, version 3.7.0

mise data directory:
  /opt/mise

mise environment variables:
  MISE_DATA_DIR=/opt/mise
  MISE_FISH_AUTO_ACTIVATE=0
  MISE_SHELL=fish
  MISE_LOG_LEVEL=warn
  MISE_ENV_FILE=.env
  MISE_USE_TOML=1

mise settings file:
  ~/.config/mise/settings.toml

settings:
  {
    "all_compile": false,
    "always_keep_download": false,
    "always_keep_install": false,
    "asdf_compat": false,
    "color": true,
    "disable_default_shorthands": false,
    "disable_tools": [],
    "experimental": true,
    "jobs": 4,
    "legacy_version_file": false,
    "legacy_version_file_disable_tools": [],
    "node_compile": false,
    "not_found_auto_install": true,
    "paranoid": false,
    "plugin_autoupdate_last_check_duration": "0",
    "python_compile": true,
    "python_venv_auto_create": false,
    "raw": false,
    "shorthands_file": null,
    "task_output": null,
    "trusted_config_paths": [],
    "quiet": false,
    "verbose": false,
    "yes": false,
    "ci": false,
    "cd": null,
    "debug": false,
    "env_file": ".env",
    "trace": false,
    "log_level": "warn"
  }

config files:
  ~/.config/mise/config.toml

plugins:
  bun      (core)
  deno     (core)
  erlang   (core)
  go       https://github.com/kennyp/asdf-golang.git#f006a12
  java     (core)
  node     (core)
  python   (core)
  ruby     (core)
  rust     https://github.com/code-lever/asdf-rust.git#0c88f99
  zig      https://github.com/cheetah/asdf-zig.git#d88f6db

toolset:
  python@latest, go@latest, rust@latest, zig@latest

No problems found
```

**Comment by jdx** [comment]
A couple of these are duplicates:

* https://github.com/jdx/mise/issues/1411
* https://github.com/jdx/mise/issues/1419

I noticed there was a bug in the script that generates the [list of releases](https://mise-versions.jdx.dev/python-precompiled), but I just put a patch in for that so this should be working correctly now. It includes 3.12.1 now.
