### ISSUE TITLE
`env._.run`

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1448]
similar to #1447, it should be possible to execute arbitrary scripts which "export" env vars like this:

```toml
[env]
_.run = "./myscript"
```

Where unlike in #1447, this would be run like any other binary. Somehow it needs to pull env vars out of it, I know that direnv has a trick where they launch direnv inside of this script and that is able to pull the env vars out. We'll need something like that to make this possible.

**Comment by kabouzeid** [comment]
Would also solve my use case for direnv, loading environment modules, eg:

`module load CUDA/12.1`

**Comment by laluka** [comment]
Would be lovely for scripts execution, but for single commands as well, to have atomic commands too :pray:

**Comment by jdx** [comment]
You're welcome to take it on

**Comment by sandstrom** [comment]
@jdx If you are open to it, we'd be willing to sponsor some improvements around this issue as well as these other two:

- https://github.com/jdx/mise/issues/1982
- https://github.com/jdx/mise/issues/1777

Of course, this assumes you are onboard with the proposed changes.

In short, we are trying to replace direnv with Mise and there are some differences in how they work, which are currently blocking a switch. Happy to elaborate on the details if you want to know more about what's keeping us from switching.

I'd guess you are probably busy, but just wanted to ask 😄

**Comment by sandstrom** [comment]
@jdx Awesome 😄 

If you enable donations we'll still send something over (we're not a huge company though, just a dozen of engineers).

In either case, this is great and I think (a colleague is double-checking) that this will unblock us from moving off direnv to Mise! 🎉

**Comment by jdx** [comment]
I really appreciate that! let me know how it works, it was quite a bit of code and it's a bit tricky to test but I had it working well enough on my machine

**Comment by sandstrom** [comment]
@jdx Great! 

I'm not directly involved but my colleague will likely write back here or in the other issue that was also closed yesterday (those were related) in case there are questions.

You should see some fresh sponsorship. I know it's not much, but at least it's something (we're not a big company).

**Comment by glasser** [comment]
I'm not 100% sure how I follow that the hooks feature addresses this issue — can you "export" variables from hooks as described here?

**Comment by rsyring** [comment]
> I'm not 100% sure how I follow that the hooks feature addresses this issue — can you "export" variables from hooks as described here?

Maybe through sourcing the hook?  https://mise.jdx.dev/hooks.html#shell-hooks
