### ISSUE TITLE
can not install fzf 💊

### ISSUE THREAD

**Issue by lost22git** [jdx/mise#1457]
❯ mise install fzf
tar: This does not look like a tar archive
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mise ~/.local/share/mise/plugins/fzf/bin/install failed
∗ Downloading and installing fzf...
tar: This does not look like a tar archive

**Comment by jdx** [comment]
you should ask the plugin maintainer

**Comment by jensbodal** [comment]
Until this PR gets merged (https://github.com/kompiro/asdf-fzf/pull/3) you can fix it yourself

```
mise plugin add fzf https://github.com/christasich/asdf-fzf.git --force
mise up
```

If you do this however note you are using someone else's fork now of the plugin. It'd be safer to just fork the change yourself and use that as the plugin until it's merged.
