### ISSUE TITLE
`mise rm`

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1465]
right now `mise rm|remove` is an alias for `mise uninstall`, however I am wondering if that should stay the case. I am considering whether it should have slightly different behavior where instead of just uninstalling a tool, it would also modify the config file to no longer reference the installed tool. Basically the inverse of `mise use`.

New users—notably this is a problem specific to those _not_ coming from asdf—are becoming confused why they can't "completely remove" something. What they do is something like this:

```sh
$ mise use -g node@20
$ mise uninstall node
$ mise ls
node 20.0.0 (missing)
```

node shows up as v20 with a "missing" tag on it but they just uninstalled it.

Now for asdf users, they don't struggle here. They know that `mise install|uninstall` do not touch config files but `mise global|local` do. It wouldn't make sense for `mise uninstall` to have done that.

This was introduced when I created `mise use` which doesn't have a discoverable inverse command. To illustrate, the matrix of commands looks like this:

|      | **add** | **remove** |
| -- | --- | --- |
| **does not modify config** | `mise install` | `mise uninstall` |
| **does modify config** | `mise use` | `mise ???` |

Although, technically that isn't quite true, there are 2 commands for this task:

* `mise global|local --rm`
* `mise use --rm`

But they both have problems. First, `global|local` is something I actually push users away from for DX reasons. It's asdf legacy support. `mise use` is almost always a better option. `mise use --rm` isn't great though because it just sounds weird and users wouldn't think to look under `mise use` for _removing_ something from config.

I think what would make sense is a new command: `mise rm`. However, I really dislike introducing yet another command that's only slightly different. I worry about confusion between `mise uninstall` and `mise remove`. Perhaps in the beginning it would've made sense to completely break away from asdf's convention and only have `mise install|uninstall` and have _both_ of them modify config files unless some flag was passed, but I'm not sure.

I'm leaning towards thinking we should add it. I think my table above illustrates that it's a fairly clear gap. However I tried to think the logic for that command through and it's actually quite complicated. What if something is defined in multiple config files? Do you need to specify `mise rm --global` if it's _only_ in the global config? Lots of outstanding questions.

Perhaps to avoid confusion I could call it the awkward—but more clear—`mise unuse`.

**Comment by camsteffen** [comment]
How about `mise unuse` and deprecate `mise rm|remove`?

It's also surprising that "remove" doesn't have a complimenting "add".

**Comment by Skipants** [comment]
Hey, just a random user of asdf and now mise, here. Thanks for your work on mise -- I love it so far!

I have a bit of a fringe take on this: Remove editing the `.tool-versions` file completely from the CLI, including `mise use`.

My reasons for this are:

1. Adding and editing .tool-versions very easy for a human to change themselves: the format of .tool-versions is pretty simple and understandable. It's very terse, as well.
2. Editing .tool-versions doesn't happen very often: only when upgrading or adding a new tool. Most large, professional applications I've worked on are slow at this. This may be less true for codebases where the developers are more militant about upgrading patch versions.
3. These are extra commands that are only there to do something very simple. The best CLIs, in my opinion, are ones that have a smaller "surface area", less commands and less flags, but do something very complex under the hood.

**Comment by johnpyp** [comment]
Contrary: I really appreciate editing the `.mise.toml` with mise use, especially that it can understand which files I want to edit, and resolve to the specific versions without me having to first identify the specific version and manually edit it myself, if I ask it to.

**Comment by jdx** [comment]
I was thinking `mise clear` might be a good name for "remove tool from config file"

**Comment by Adirelle** [comment]
What about "forget"? e.g. `mise forget node`

**Comment by jdx** [comment]
to me "forget" would mean "remove from config but not the install", similar to `mise clear`. That doesn't encapsulate what I would like which is a true inverse of `mise use`. Maybe it's ok though, since having something installed but not in use isn't really a big deal. We could always have `mise clear --rm` or `mise forget --rm`.

That said, I do like the cuteness of potentially changing `mise use` to `mise hire` and then having `mise fire` (with a `mise sack` alias for UK users).

**Comment by kenbankspeng** [comment]
mise purge

**Comment by jdx** [comment]
`mise install` without arguments certainly is useful if you're reusing an existing config. `mise install` is asdf behavior that was ported and certainly is not possible for us to remove or reconsider. Too many people rely on that behavior even if it's not the most obvious DX.

**Comment by RafalSkolasinski** [comment]
> Or, more specifically, why do mise install and mise uninstall even exist? Why would you want to add/remove without affecting the config? I'm sure there are good reasons, but I don't see them yet. Thanks!

Yes, installing and uninstalling in context of local config (not global config, but config local for a project) is v. useful.

**Comment by jdx** [comment]
yeah I think this should happen, judging from the feedback on this it seems others are feeling similarly.

here's my proposal:

add `mise unuse` and I think also alias it to `mise rm`. To me `rm` should remove from the config file and uninstall. Technically a breaking change but I think one we can live with since it's just an alias for `mise uninstall` and will still do what `mise uninstall` does—just more.

In terms of `mise clear` I dunno if I like it or not. It seems useful. Then again the commands to do the inverse are... not my favorites. Technically we support `mise local` and `mise global` which have been hidden since almost the initial release of rtx. I don't like that it's not one command to do those things and I hate that they're not verbs which they should be.

So then we have another naming problem: what would the inverse of `mise clear` be? Can't be `mise set`—we already have that for env vars.

**Comment by jdx** [comment]
well, perhaps it could be `mise set` if we overload it so it behaves differently if it's an env var or tool:

```
mise set NODE_ENV=production
mise set node@20
```

could work

**Comment by BoscoDomingo** [comment]
Hi @jdx this is a feature I've long wanted (I rarely edit the global config file since `use` is so convenient). Having an `unuse` to go with it would be amazing. Any chance it will come out soon?

**Comment by shinebayar-g** [comment]
+1 for `mise remove` to indicate it's removing from the config?
