### ISSUE TITLE
Go package support to go with Cargo, NPM

### ISSUE THREAD

**Issue by endigma** [jdx/mise#1468]
Another pretty common package source that isn't asdf, npm or cargo is `go install`, this works pretty well with just the go toolchain but updating and uninstalling is a bad story there. Mise support would be good here.

**Comment by endigma** [comment]
https://github.com/jdx/mise/discussions/1250 exists

**Comment by jdx** [comment]
I could definitely use some help with this if you could spend some cycles. It's really not a lot of work (I don't think) but I've got other more high priority things to work on so I think it will be a while for me to get to it

**Comment by endigma** [comment]
#1470 , wrote before seeing the comment lol
