### ISSUE TITLE
.tool-versions which overrides the global config, though `asdf_compat = false`

### ISSUE THREAD

**Issue by yssource** [jdx/mise#1487]
``` fish
mise use -g go@latest
mise go is defined in ~/.tool-versions which overrides the global config (~/.config/mise/config.toml)
mise ~/.config/mise/config.toml tools: go@1.21.6
```
~/.tool-versions
`golang 1.17`

~/.config/mise/settings.toml
`asdf_compat = false`

The .tool-versions overrides the global config, though I disabled the asdf compatible.

The actual result is
`go version` 
go version go1.17 linux/amd64

But the expected result should be `go@1.21.6`

**Comment by jdx** [comment]
`~/.tool-versions` is a _local_ config file since it's in the hierarchy. You'll need to delete go from it to get it to behave the way you want.

**Comment by yssource** [comment]
I come from asdf, making a trick to define the user global tools in ~/.tool-versions.
Oh, ~/.tool-versions works under mise is a local config, which is different.

**Comment by yssource** [comment]
Actually my current directory is `/tmp/`, not under the user home path.
I think it is more reasonable that `~/.config/mise/settings.toml` has higher priority then `~/.tool-versions`.

**Comment by yssource** [comment]
what I understand about `asdf_compat = false` is to disable the `.tool-versions` for mise, isn't it?

**Comment by jdx** [comment]
no, `asdf_compat = false` is the default behavior. mise always reads `.tool-versions` files.
