### ISSUE TITLE
Shims vs shell functions

### ISSUE THREAD

**Issue by HaleTom** [jdx/mise#1492]
The [section on shims](https://mise.jdx.dev/dev-tools/shims.html) only seems to list a benefit (use in IDEs).

Why not use shims all the time then?  Are there any disadvantages?

I'm looking for a compare and contrast of both approaches (with pros and cons for each) - I can't seem to find that in the doco at the moment.

**Comment by hahuang65** [comment]
@HaleTom the drawback is speed, mentioned in https://mise.jdx.dev/dev-tools/comparison-to-asdf.html#performance

I've done a simple test, running `go version` using shims vs using the executable directly. See for yourself.

Direct:
```
$ hyperfine "~/.local/share/mise/installs/go/1.21.6/go/bin/go version"
Benchmark 1: ~/.local/share/mise/installs/go/1.21.6/go/bin/go version
  Time (mean ± σ):      47.3 µs ± 186.9 µs    [User: 637.1 µs, System: 1047.5 µs]
  Range (min … max):     0.0 µs … 1592.6 µs    400 runs
```

Shims:
```
$ hyperfine "~/.local/share/mise/shims/go version"
Benchmark 1: ~/.local/share/mise/shims/go version
  Time (mean ± σ):       8.6 ms ±   1.8 ms    [User: 6.0 ms, System: 9.6 ms]
  Range (min … max):     5.7 ms …  14.3 ms    173 runs
```

6ms vs 600 microseconds is a 10x difference.

**Comment by HaleTom** [comment]
Thanks for taking the time to provide this data.

Personally, I con't care about a 5.4ms difference when loading something if it makes for much more concise config files.

I've learnt that one major reason to use shell functions would be to read environment setup files, like `.mise.toml`.

**Comment by hahuang65** [comment]
@HaleTom it might depend on your OS. Like @jdx mentioned in the performance link, he experiences 120ms using shims. I believe he's on macOS.

My benchmarks were made on my Arch laptop.

I believe `asdf` is MUCH slower on my work macOS laptop compared to my Arch. I can give that a go and report back as well.

**Comment by hahuang65** [comment]
> @hahuang65 see `Shorter config for zsh / bash` #1498 for how I'm doing it now.

But you're NOT using shims in that example... I'm a little confused.
