### ISSUE TITLE
`mise activate --shims` from getting started tip doesn't work

### ISSUE THREAD

**Issue by HaleTom** [jdx/mise#1493]
https://mise.jdx.dev/getting-started.html says:

> TIP
> You can also run mise activate --shims which will do the above for you.

```
% mise activate --shims
error: unexpected argument '--shims' found

  tip: to pass '--shims' as a value, use '-- --shims'

Usage: mise activate [OPTIONS] [SHELL_TYPE]

For more information, try '--help'.
```

`mise activate zsh --shims`  and `mise activate zsh -- --shims` didn't work either.

**Comment by jdx** [comment]
use the latest version

**Comment by HaleTom** [comment]
Cheers!
