### ISSUE TITLE
Question: using `mise` from within neovim

### ISSUE THREAD

**Issue by hahuang65** [jdx/mise#1497]
I'd like to use `mise` without shims. However, this breaks my neovim configuration, since the LSP system there depends on `/usr/bin/env <tool>` sometimes. I understand this is because there's no prompt as it's not an interactive tty.

Are there any suggestions to work around this, or will I simply have to use shims?

**Comment by jdx** [comment]
you'll need to use shims but perhaps there is a way to configure neovim to use them without using them outside of neovim

**Comment by hahuang65** [comment]
Curious if I could use the shebangs... 

Is the primary advantage of not using shims just the fact that the executables resolve to an exact path, rather than thru the shims?

**Comment by hahuang65** [comment]
@jdx looks like if I simply

```
export PATH="$HOME/.local/share/mise/shims:$PATH"
eval "$(mise activate bash)"
```

I will have absolute paths in my shell, since the priority for those paths precede the shims... and the shims will work in neovim as a fallback, since they're in my `$PATH`.

Can you think of any drawbacks to this method?

**Comment by jdx** [comment]
you won't be able to modify the version of anything in your global config

**Comment by Jomik** [comment]
Slightly annoying, but I did this in my init.lua 
```lua
vim.env.PATH = vim.env.HOME .. "/.local/share/mise/shims/:" .. vim.env.PATH
```
It does add the shims to my terminal opened _within_ neovim, but not outside. And the actual binaries will go ahead of the shims anyway, so no worries there.

My actual only issue with this is that I have a (stupid) legacy project that uses node12, and a `.tool-versions` specifying that. Shims are clever enough to find that file, and thus it results in the lsp not working, as it needs node18.
Haven't looked into it more than this though.

**Comment by jdx** [comment]
^^ that's what I would do

**Comment by Jomik** [comment]
> If either of you want to, this would be a great contribution to the IDE section of the docs
I might get the time to write something quick tomorrow, couldn't immediately see where your docs live, can you point towards them / or contribution guidelines for them?

**Comment by jdx** [comment]
https://github.com/jdx/mise-docs/blob/main/ide-integration.md

**Comment by Jomik** [comment]
https://github.com/jdx/mise-docs/pull/27

**Comment by jdx** [comment]
thanks for that @Jomik! this'll be a great help to folks
