### ISSUE TITLE
Shorter config for zsh / bash

### ISSUE THREAD

**Issue by HaleTom** [jdx/mise#1498]
Rather than including the whole output of `mise activate $SHELL` and bloating shell config with about 50 lines, I'd propose a shorter, cleaner version:

    command -v mise &> /dev/null && eval "$(mise activate "${SHELL##*/}")"
    
 This will check if `mise` is a binary, and only activate it if so.
 
 [Yes, I source .bashrc from .zshrc]

**Comment by jdx** [comment]
this is longer than the example. and "$SHELL" is not standard.

**Comment by HaleTom** [comment]
Thanks, you're right!  My brain-fart.
