### ISSUE TITLE
`mise install mise`

### ISSUE THREAD

**Issue by HaleTom** [jdx/mise#1499]
My distro's package of mise lags behind the latest release, and I'm using Arch, so I assume it's only much worse for others.

It would be great to be able to do `mise install mise` to use mise to bootstrap to the latest (or a selected, eg if debugging) version.

**Comment by jdx** [comment]
I'm not entirely sure if I want to add this. I get why it could be useful in some narrow cases but I think using install.sh is a much better solution.
