### ISSUE TITLE
Jetbrains Rubymine - Error configuring SDK

### ISSUE THREAD

**Issue by Peredery** [jdx/mise#1531]
Can't add mise as version manager to sdk

```
Error configuring SDK: Could not get RubyGems environment for ruby-3.3.0-p0: ver.3.3.0p0 (/Users/peredery/.local/share/mise/shims/ruby). Please make sure that /Users/peredery/.local/share/mise/shims/ruby is a valid home path for this SDK type.
```

<img width="466" alt="Screenshot 2024-01-26 at 1 34 01 PM" src="https://github.com/jdx/mise/assets/41237931/8cef2bdd-dd52-4b54-8928-0b5073646b02">

**Comment by vadimvera** [comment]
Did you try with the path for the actual SDK under `$HOME/../mise/installs/..`?

**Comment by Peredery** [comment]
> Did you try with the path for the actual SDK under `$HOME/../mise/installs/..`?

add `export PATH="/Users/peredery/.local/share/mise/installs/:$PATH"` to .zprofile but still not work

**Comment by vadimvera** [comment]
`IntelliJ` is looking for a proper SDK.

I meant that you needed to find the Ruby SDK within `$HOME/../mise/installs/path/to/ruby/sdk/with/the/version/you/installed/`, rather than just providing the link the executable (inside `../shims/`).

**Comment by Peredery** [comment]
> `IntelliJ` is looking for a proper SDK.
> 
> I meant that you needed to find the Ruby SDK within `$HOME/../mise/installs/path/to/ruby/sdk/with/the/version/you/installed/`, rather than just providing the link the executable (inside `../shims/`).

but in asdf the same thing works with shim... and the official instructions say you should add `export PATH="$HOME/.local/share/mise/shims:$PATH"
`, so it's a bug? https://mise.jdx.dev/ide-integration.html

**Comment by jdx** [comment]
It's asking for the SDK, not the binary

**Comment by Peredery** [comment]
https://youtrack.jetbrains.com/issue/RUBY-32015

**Comment by jdx** [comment]
my understanding is rubymine natively supports mise now
