### ISSUE TITLE
Is it possible to specify virtualenv when running "mise use python"?

### ISSUE THREAD

**Issue by leemars** [jdx/mise#1552]
I hope that there's some way to specify virtualenv options when running "mise use python"

For example, by this way:
```sh
$ mise use python@3.11 --virtualenv .venv
```

then I would like to get:
```sh
$ cat .mise.toml
[tools]
python = {version="3.11", virtualenv=".venv"}
```

For now I need to run "mise use python@3.11" then modify .mise.toml by hand to add options.

**Comment by jdx** [comment]
you should be able to do this now with `mise use python[virtualenv=.venv]` though I haven't tested. I hope you don't have a path with a comma or bracket in it though because is not something the logic can handle lol
