### ISSUE TITLE
Q: Support other origin sources .i.e mirror setup

### ISSUE THREAD

**Issue by janderssonse** [jdx/mise#1555]
As an old user of asdf-vm, looking at mise, one thing that always bugged me about asdf-vm was that is does not have way of with an easy conf change host, i.e as an organisation I would like to have the option to use an internal registry, a quite common enterprise practice.
It this possible with mise, (did i miss it in the docs), and if not, it is planned for the future? Cheers!

**Comment by jdx** [comment]
my suggestion is to use tool aliases https://mise.jdx.dev/dev-tools/aliases.html#aliased-backends

**Comment by janderssonse** [comment]
Will see if it is right for us, thanks.
