### ISSUE TITLE
Support for enterprise use with all http calls through internal mirrors/caches

### ISSUE THREAD

**Issue by sgtsquiggs** [jdx/mise#1556]
Mirroring the request over at https://github.com/asdf-vm/asdf/issues/1574

For companies with internal proxies this would be a huge help - we’d be able to use it with on prem cicd!

**Comment by jdx** [comment]
this isn't realistic. This is something that needs to be for each plugin individually—some already have support for this. Completely mirroring everything really isn't something I think is possible especially once you start talking about different backends.

**Comment by sgtsquiggs** [comment]
Maybe some api so plugins can support it the same way across the board would work

**Comment by Ajpantuso** [comment]
I'm a little confused about the goal here.

If your enterprise requirements are that plugin/tool binaries are only installed from trusted sources then you should be restricted to your enterprise package management solution.

Even if mise/asdf had a unified repository/strategy for storing/retrieving these artifacts on an internal network your security team should be the ones vetting/uploading them not a third-party open-source tool.

I think a more generic solution here is to setup machines with all binary versions in the install locations for mise(which is configurable) and then use mise to manage the shims/env/etc... for each project.

Each language's package management tools should let you then redirect to use your internal artifact repository for libraries.

**Comment by jdx** [comment]
I'm going to close this since I don't really understand how it would be done. I'd be happy to reopen if someone had a more concrete plan and was willing to do the development for it. Otherwise this just reads like a vague pipe dream and as @Ajpantuso I think the value is questionable anyways.
