### ISSUE TITLE
turn scripts into mise tasks

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1568]
The [scripts](https://github.com/jdx/mise/blob/main/scripts) should be converted into mise tasks

Related #1567

**Comment by km-tr** [comment]
@jdx 
Does this mean moving things under the .mise directory?
https://mise.jdx.dev/tasks/script-tasks.html

**Comment by jdx** [comment]
yeah

**Comment by jdx** [comment]
if you take this on, I'd probably start with just 1. Trying to do all of them at once is probably too likely to cause problems.

**Comment by km-tr** [comment]
Thanks for the advice. I'll start by focusing on one task at a time and go from there.

**Comment by Adirelle** [comment]
Looking at these scripts, it seems some of them are used specifically in (and would only work in the context of) the github workflows while some others should be used inside the packaging containers. I am not sure moving them as mise tasks is a good idea in the cases. IMO it would be better to move them in dedicated folders of the `.github` and `packaging` folders, respectively.

**Comment by jdx** [comment]
I'm wanting to clean up some old issues and I think this one just doesn't have enough value to stick around so I'm closing.
