### ISSUE TITLE
Disable default languages

### ISSUE THREAD

**Issue by kyhyco** [jdx/mise#1574]
Hello!

Is there a way to disable default languages in `mise`? I am in a state where I have to use `pyenv` but want to use `mise` for everything else.

I got a large set of repos with various languages that use `rbenv`, `nvm` and `pyenv`. I want to switch to `mise` for all of them but it will have to be done gradually as there are setup commands that rely on legacy language version managers.

Thank you!

**Comment by jdx** [comment]
https://mise.jdx.dev/configuration.html#disable-tools
