### ISSUE TITLE
Rebuild old rtx ohmyzsh plugin as new mise plugin

### ISSUE THREAD

**Issue by Nezteb** [jdx/mise#1606]
At some point after the rename from `rtx` to `mise`, the `ohmyzsh` project removed its plugin: https://github.com/ohmyzsh/ohmyzsh/pull/12143/files#diff-4795f21377c3841679af65bc3fea466e10d2278c61964c966c709d7bbf51e5e6

> This is a BREAKING CHANGE because the rtx plugin will no longer exist. I decided to not implement any transition logic because the author hasn't provided any wrappers for rtx to continue working once mise is installed. I feel that ohmyzsh shouldn't provide that.

The `ohmyzsh` maintainers would prefer if a maintainer of `mise` contributed that plugin. I figured there should be a GH issue to track that idea. 😄

**Comment by jdx** [comment]
I don't use ohmyzsh or zsh
