### ISSUE TITLE
Unable to select a specific ruby version if config contains a different version

### ISSUE THREAD

**Issue by DmitryPogrebnoy** [jdx/mise#1628]
**Describe the bug**
The problem is that when I have a config file in the directory with some ruby version. I can't select the other ruby version in mise. 

**To Reproduce**
Suppose you have a config file (`.ruby-version` in my case) in the directory.
Open that directory in the console.
Mise selects the ruby version according config file automatically.
Now try to select a different ruby version in mise. After the change, it changes back to the version from the config.

**Expected behavior**
Generally auto-switching to the config version is ok and might be helpful. But I expect that mise will not change the version of ruby, if I specified it manually. I believe that is the preferable way to how it should work.

**`mise doctor` output**

```text
mise version:
  2024.2.5 macos-arm64 (59362f2 2024-02-06)

build:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Tue, 6 Feb 2024 14:26:35 +0000
  Rust Version: rustc 1.75.0 (82e1608df 2023-12-21)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin23.0)

mise dirs:
  data: /Users/dmitry.pogrebnoy/.local/share/mise
  config: /Users/dmitry.pogrebnoy/.config/mise
  cache: /Users/dmitry.pogrebnoy/Library/Caches/mise
  state: /Users/dmitry.pogrebnoy/.local/state/mise
  shims: /Users/dmitry.pogrebnoy/.local/share/mise/shims

mise environment variables:
  MISE_SHELL=zsh

settings:
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cargo_binstall = true
  color = true
  disable_default_shorthands = false
  disable_tools = []
  experimental = false
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  node_compile = false
  not_found_auto_install = true
  paranoid = false
  plugin_autoupdate_last_check_duration = "7d"
  python_compile = false
  python_default_packages_file = "/Users/dmitry.pogrebnoy/.default-python-packages"
  python_pyenv_repo = "https://github.com/pyenv/pyenv.git"
  python_venv_auto_create = false
  raw = false
  trusted_config_paths = []
  quiet = false
  verbose = false
  yes = false
  ci = false
  debug = false
  trace = false
  log_level = "info"

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false


activated: yes
shims_on_path: no
config files:
  ~/.ruby-version
  ~/.mise.toml

plugins:
  bun      (core)
  deno     (core)
  go       (core)
  java     (core)
  node     (core)
  python   (core)
  ruby     (core)

toolset:
  ruby@3.3.0

1 problem found:
new mise version 2024.2.6 available, currently on 2024.2.5
```

**Additional context**
his issue affects the issue about proper support of mise in RubyMine IDE - https://youtrack.jetbrains.com/issue/RUBY-32015/Support-the-mise-ex-rtx-ruby-tool-version-manager.

**Comment by jdx** [comment]
> Now try to select a different ruby version in mise. After the change, it changes back to the version from the config.

I don't know what this means

**Comment by DmitryPogrebnoy** [comment]
Yep, about `mise use` and about `mise shell`. Let me explain it in more detail. The same steps work also for `.mise.toml` files, let suppose that we have `.mise.toml` for simplicity.

Complete steps for the reproduction:
1. Install ruby@3.3.0 in mise.
2. Create empty directory.
3. Create `.mise.toml` file with content `3.2.0` in the directory from the previous step.
4. Open that directory in the console.
5. Run `ruby -v`. Output is `ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin23]` - system ruby.
6. Run `mise list ruby`. Output is:
```text
Plugin  Version  Config Source                     Requested
ruby    3.2.0    ~/Desktop/mise_example/.mise.toml 3.2.0    
ruby    3.3.0                                                                                                                             
```
So the version is automatically selected by 3.2.0. because it is stated in the config file. It is expected.
Now suppose you would like to use some other version of ruby in the console. Then your next step is the following:
7. Run `/Users/dmitry.pogrebnoy/.local/bin/mise shell ruby@3.3.0`.
On that step I expect that now I have ruby 3.3.0 enabled. Let's check:
8. Run `ruby -v`. Output is `ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin23]` - still system ruby.
9. But! If I call `mise shell ruby@3.3.0`, then the version will change to 3.3.0.
10. Let's check. Run `ruby -v`. Output is `ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]`.

Could you please explain why it works as it is? I expect that it should work the same in both cases.

**Comment by DmitryPogrebnoy** [comment]
@jdx Also, some kind of a related question is why `mise use ruby@<something>` changes not only the currently selected ruby version, but also a value in `.mise.toml` config file? If I want to use some other ruby version just for several commands, I don't want to change the value in config.

**Comment by jdx** [comment]
> Run ruby -v. Output is ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin23] - still system ruby

Because `mise shell` is a shell function that sets environment variables. A CLI cannot do that.

> If I want to use some other ruby version just for several commands, I don't want to change the value in config.

that's what `mise shell` is for. mise needs to change something (an env var or config file) so it knows which version to use.

**Comment by DmitryPogrebnoy** [comment]
Thank you for the clarification!
