### ISSUE TITLE
Option to install python headers

### ISSUE THREAD

**Issue by PhML** [jdx/mise#1633]
I try to install a package that needs C++ compilation with python headers (development files).

I tried :

`env PYTHON_CONFIGURE_OPTS="--enable-shared" mise install --verbose python@3.10.13`

As suggested in [pyenv wiki](https://github.com/pyenv/pyenv/wiki#how-to-build-cpython-with---enable-shared).

But it doesn’t seem to work.

Is there a way to have those headers with mise ?

**Comment by jdx** [comment]
are you using precompiled binaries?

**Comment by PhML** [comment]
In fact, python3.11 changed some headers so the package I try to compile needs an update.
With an older python version it works.

I close this issue, thank you.
