### ISSUE TITLE
Not able to install Python 3.12.2 (brand new version)

### ISSUE THREAD

**Issue by gbbirkisson** [jdx/mise#1634]
I cannot install newest version of python because it is missing. It has been out for [2 days now](https://github.com/python/cpython/tags). I am not using pre-compiled binaries, so I assume that we are fetching available versions from this url:

```
$ curl -s http://mise-versions.jdx.dev/python | grep 3.12.
pypy2.7-7.3.12-src
pypy3.9-7.3.12-src
pypy3.10-7.3.12-src
3.12.0
3.12-dev
3.12.1
```

What causes the holdup?

**Comment by jdx** [comment]
python-build

**Comment by gbbirkisson** [comment]
Excuse my ignorance, can you elaborate?

**Comment by jdx** [comment]
https://mise.jdx.dev/lang/python.html

**Comment by gbbirkisson** [comment]
I see, thanks for the clarification. And thanks a lot for mise, awesome stuff :heart:
