### ISSUE TITLE
Option to define --features when using the rust cargo backend

### ISSUE THREAD

**Issue by queckezz** [jdx/mise#1635]
If I read the [rust cargo backend source](https://github.com/jdx/mise/blob/main/src/forge/cargo.rs)  correctly, there is currently no way to define the `--features` flag (or any install flags) when installing a cargo lib right? Just making sure, i would be open to create a PR.

A use case is installing [`spotifyd`](https://github.com/Spotifyd/spotifyd/blob/master/Cargo.toml#L53) with some specified features.

**Comment by jdx** [comment]
not currently, no. It's probably a use-case for tool options.
