### ISSUE TITLE
`mise en`

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1655]
I had an idea reading rvm's documentation and its similar (but not the same as what I'm proposing here) as their `rvm in` [command](https://rvm.io/set/do).

We already have support for `rvm in` with `mise -C some/dir x` but I have been thinking lately that people would probably benefit from a convenient way to perform `mise x -- $SHELL`—which gives you a nice way to launch into the mise environment without needing to use `mise activate` in your shell rc file—notably the way I like to use mise. I think in places like IDEs it can often be a lot easier to set things up this way as well.

I'm thinking `mise en` could be a nice shorthand for that, so you could just do `mise en .` and it would be effectively like doing `cd .` but it'll setup all of your tools and everything.

Of course this doesn't enable anything new since you can just run `mise -C some/dir x -- $SHELL` and it does the same thing (perhaps via a `mise_en` alias), but having a top-level command is a good way to teach people how best to use mise and I think this is a pattern a lot of people would benefit from knowing about.

**Comment by booniepepper** [comment]
Poetry has a similar thing with `poetry shell` that launches your current shell but with a (poetry-managed) virtual env activated.

For more ideas, see also Nix's [`nix-shell`](https://nixos.org/manual/nix/stable/command-ref/nix-shell) (spawn shell from nix file) and [`nix shell`](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-shell) (spawn shell from cli args)

**Comment by booniepepper** [comment]
Also strongly suggesting it should be `mise en .`

**Comment by jdx** [comment]
I think this would be fairly easy to implement if anyone wants to have at it, I think we can just call [`Exec::run()`](https://github.com/jdx/mise/blob/main/src/cli/exec.rs) with "$SHELL" after changing the current directory

**Comment by pepicrft** [comment]
I like the idea. When using it from Xcode project scripts it'd just be one line of code. I'd check if it works fine with `sandbox-env`, which is the tool that Xcode uses to sandbox the execution of the script.

I'm not Xcode developers will entirely understand what the command is for, but the copy and pasting that they'll most likely do has more chances to work.

Have you considered `mise shell`? As someone not familiar with `rvm in`, I wouldn't be able to guess what the command is for.

**Comment by jdx** [comment]
well, we already have a command `mise shell`. It's a bit different though in that it only works inside of a session where `mise activate` has already been executed.
I thought for a bit maybe we could merge the 2 and have `mise shell` do the same thing as `mise en` if it's not inside of a `mise activate` session, but I think they work so differently that it makes more sense to have separate commands.

**Comment by pepicrft** [comment]
Naming is hard 😬. I'd expect `mise shell` to take the role of `mise en`, and the current `mise shell` to be more like `mise load/set` to mean that a tool is being loaded into the activated session.

**Comment by jdx** [comment]
I think I want to implement this just not because of how useful it would be, but because I just want a `mise en` command to exist
