### ISSUE TITLE
mise active doesn't work if installed thru homewbrew

### ISSUE THREAD

**Issue by ytc338** [jdx/mise#1662]
**Describe the bug**
when restert the shell session, it would outpu this error
/Users/username/.zshrc:116: no such file or directory: /Users/username/.local/bin/mise

**To Reproduce**
On a Apple Silicone mac. Install homebrew and install mise thru homebrew
eval "$(mise activate zsh)"
restart the shell session 
see the issue

**Expected behavior**
No error message and `node` command would work

**`mise doctor` output**

```text
REPLACE WITH OUTPUT OF `mise doctor`
```

**Additional context**
It's because homebrew install mise to it's own path. i need to manually change the mise bin path in .zshrc to `/opt/homebrew/bin/mise`

**Comment by andrewthauer** [comment]
This almost sounds like an `PATH` ordering issue. Homebrew installed  binaries on macOS arm64 are installed to `/opt/homebrew/bin`, but this is not on the path by default. Normally you'd have something like `eval "$(/opt/homebrew/bin/brew shellenv)"` in your zshrc to set the path.

I would double check the path to homebrew is set before doing the mise activate. You could also doing check the path resolution before calling it with `which -a mise`.

**Comment by ytc338** [comment]
Yeah right actually I found out this should be just a document improvement. I copied `echo 'eval "$(~/.local/bin/mise activate zsh)"' >> ~/.zshrc` from Quickstart. Now I see I need to replace the path with the bin path on my computer. That's just default. Would it be better if change the command to `echo 'eval "$(mise activate zsh)"' >> ~/.zshrc`. And tell the user to make sure mise is in PATH before calling active.

**Comment by jdx** [comment]
I don't see how the documentation could be clearer:

> # note this assumes mise is located at ~/.local/bin/mise
> # which is what https://mise.run does by default

**Comment by jdx** [comment]
oh I suppose that note is only in the readme

**Comment by andrewthauer** [comment]
I had a look at the docs, and while there is is a note about this I can see how someone might overlook this as folks often follow the first thing they may see.

Id say 2b from getting started could probably be broken into 2 options to be slightly clearer perhaps. One for when you use the absolute path to mise and one where you have mise in your path?

**Comment by jdx** [comment]
if it's not in that location they're not actually following the quickstart

**Comment by andrewthauer** [comment]
Hmm. Maybe possible confusion is the link to `Alternate installation methods` links far below. Which doesn't directly include the activation logic. Then the `Shells` section talks about this. So from my perspective there is a bit of overlap and jumping around. I personally didn't find this confusing when I ran through it myself, but I can see how it might trip up some folks. I can understand the need for quick start separate, but TBH, even installing with homebrew etc. is a pretty simple 2 step process which could be considered a quick start.
