### ISSUE TITLE
Limit Python versions to precompiled binaries

### ISSUE THREAD

**Issue by rik** [jdx/mise#1684]
Precompiled binaries are really nice but because the latest versions are not available right away, it would be nice to have `mise use python@3.12` install `3.12.1` quickly rather than build `3.12.2` (.2 is not available at the time of writing).

Because not everyone would like this behaviour, it probably should be an opt-in setting.

**Comment by jdx** [comment]
we could probably turn python_compile into a 3-way switch so an explicit "false" would mean to always use precompiled

**Comment by Adirelle** [comment]
By the way, what happen if python-build is not available ?

**Comment by jdx** [comment]
Mise downloads python-build. I think I prefer the current logic where nothing means use precompiled or not but "false" will always use precompiled. I think that will be more easily understood without referencing the docs.
