### ISSUE TITLE
Show more install logs (ruby in this case)

### ISSUE THREAD

**Issue by erickguan** [jdx/mise#1711]
Hello,

When I build ruby, I would like to see more information during configuration. Currently, `mise` shows a collapsed log:

`mise ruby@3.2.3 -> ./configure "--prefix=$HOME/.local/share/mise/installs/ruby/3.2.3" --with-openssl-dir=/opt/homebrew/opt/openssl@3 --enable-shared --with-readline-dir=/opt/hom ⠐ 13s`

This is super cool and I like more advanced UX. Though I would need to validate the configuration when I skim through the logs.

The specific reason is that I need to enable yjit. I run `CONFIGURE_OPTS="--enable-yjit" mise install ruby@3.2.3`. In this case, I would need to validate that yjit option is part of the configure options:
`-> ./configure "--prefix=$HOME/.local/share/mise/installs/ruby/3.2.3" --with-openssl-dir=/opt/homebrew/opt/openssl@3 --enable-shared --with-readline-dir=/opt/homebrew/opt/readline --with-libyaml-dir=/opt/homebrew/opt/libyaml --with-gmp-dir=/opt/homebrew/opt/gmp --with-ext=openssl,psych,+ --enable-yjit`

This is shown when the build fails of course. But it is great that I can see them when the build is running smoothly.

**Comment by jdx** [comment]
just use `--verbose`

**Comment by erickguan** [comment]
Thanks! My bad. I didn't understand what the verbose would do in this case. Very cool that `mise` matches my intuitive habits. I made a small PR for some text update.
