### ISSUE TITLE
Add `without_pip` option to `_.python.venv`

### ISSUE THREAD

**Issue by sbidoul** [jdx/mise#1720]
Hi,

The new `_.python.venv` mechanism sounds very good.

Would it make sense to add a `without_pip` option for creation, mirroring `python -m venv --without-pip` ?

Virtual environment without pip are viable nowadays, since pip has a `--python` option.

**Comment by Aeron** [comment]
It’s particularly viable when `pip` is not used at all. Because `uv` is upon us and all that 😄
