### ISSUE TITLE
Expose a `python_venv_default_packages_file`

### ISSUE THREAD

**Issue by noirbizarre** [jdx/mise#1725]
There is a [python-default-packages-file](https://mise.jdx.dev/lang/python.html#python-default-packages-file) setting allowing to install some common packages when installing a Python version.

However, it is useless if you use virtualenv. I propose adding a `python_venv_default_packages_file` setting on the same model which would contain a list of packages to install on `venv` creation.

**Comment by fullstopslash** [comment]
I'd like to add that it seems the documentation is currently a bit unclear regarding this feature.  I thought for sure I was doing something wrong with setting my `MISE_PYTHON_DEFAULT_PACKAGES_FILE` environment variable in zsh. I spent far too long thinking this would set up dependencies _inside_ the virtual environment that gets set up in a project, much like many other virtual environment managers that use the `requirements.txt` file that is common among python projects. I'm glad to see this is a tracked issue.

**Comment by jdx** [comment]
Sounds like a reasonable idea to me

**Comment by jdx** [comment]
I feel like the pipx backend is a better solution for this

**Comment by noirbizarre** [comment]
Not really, and actually `pipx` purpose is the opposite of this:
- `pipx` provide sandboxed Python tooling. Anything installed with `pipx` won't be share and accessible in a virtualenv
- here, the idea was to be able to install my personal tooling in the current venv

Classical use cases:
- I want my prefered tooling (`ipython`, `pudb`...) installed
- I need some tool installed for my IDE (`debugpy`)

With `pipx`, those tools won't be able to use dependencies from the current venv, and vice-versa.

Note that I already use `pipx` for Python tooling I don't want in the current virtualenv, and I'd like it to remain this way or else it will mess with the virtualenv
