### ISSUE TITLE
Cannot install TruffleRuby

### ISSUE THREAD

**Issue by sschuberth** [jdx/mise#1737]
I was following the instructions at https://www.graalvm.org/latest/reference-manual/ruby/ which refer to `asdf`, hoping that I could just use `mise` as a drop-in replacement and run

    mise install ruby truffleruby-dev

but that gets me

```
0.190 [DEBUG] ARGS: mise install ruby truffleruby-dev                                                                                                                                                  
0.190 [DEBUG] Config {                                                                                                                                                                                 
0.190     Config Files: [],                                                                                                                                                                            
0.190 }                                                                                                                                                                                                
0.190 [DEBUG] Toolset: 
0.199 [DEBUG] GET http://mise-versions.jdx.dev/ruby
0.199 [DEBUG] starting new connection: http://mise-versions.jdx.dev/
0.384 [DEBUG] GET http://mise-versions.jdx.dev/ruby 200 OK
0.389 Error: 
0.389    0: No repository found for plugin truffleruby-dev
0.389 
0.389 Location:
0.389    src/plugins/external_plugin.rs:103
0.389 
0.389 Version:
0.389    2024.2.19 linux-x64 (fd83356 2024-02-28)
0.389 
0.389 Suggestion: Run with --verbose or MISE_VERBOSE=1 for more information.
0.389 
0.389 Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
0.389 Run with RUST_BACKTRACE=full to include source snippets.
```

Maybe this is related to the more general https://github.com/jdx/mise/issues/1286, but as it's working with `asdf` I thought I'd file this separately.

**Comment by roele** [comment]
With #1854 fixed, `truffleruby` is now also shown by the core plugin with `mise ls-remote ruby`. The version semantics follows practices used in asdf (for compatabilty) and can be found for other tools such as Java, Python etc.

**Comment by roele** [comment]
@ylluminate Not with the core plugin and we do not intend to add support for vendor version syntax. Something like this could be achieved by implementing your own asdf plugin which only lists and installs truffleruby tough.

**Comment by jdx** [comment]
I think some support was put into the codebase recently that allows each core plugin to do its own resolving logic making it possible to support things like `ruby@truffleruby+graalvm-24` which wouldn't require globally modifying the resolver for all core plugins

**Comment by roele** [comment]
@jdx How i understand this, the requirement would be to have `truffelruby+graalvm` or `truffelruby` as a tool name which would be possible with a custom asdf plugin. Hashicorp is doing something in this direction, providing a single plugin for all its tools where the plugin name defines what tool it deals with (see https://github.com/asdf-community/asdf-hashicorp?tab=readme-ov-file#installation).

**Comment by jdx** [comment]
@ylluminate might be asking for that but I don't think he actually has any need for it. I think the more important gap in mise is that you can't run `mise install ruby@truffleruby+graalvm-24` but have to specify `mise install ruby@truffleruby+graalvm-24.0.2` because the resolver can't figure out how to make `truffleruby+graalvm-24` point to `truffleruby+graalvm-24.0.2`—but that issue could be fixed by overriding these functions:

https://github.com/jdx/mise/blob/d161afe843694020f22fc981537f81e5ea7f2896/src/backend/mod.rs#L275-L282

I have laid some groundwork for this but I think a tiny bit more refactoring would be needed in order to share the `fuzzy_match_filter` function which I think would need to be called in ruby.rs.

**Comment by roele** [comment]
I see, i remember having dealt with fuzzy matching in context of Java (which also has vendor prefixes) but decided to copy the `fuzzy_match_filter` function instead of exposing/sharing it.

**Comment by jdx** [comment]
yeah we should probably put `fuzzy_match_filter` on the backend so we don't need to do that

**Comment by roele** [comment]
I might find some time later today to have a look at this. I have the feeling that the code from Java can be used since they share the same vendor version semantics.

**Comment by roele** [comment]
With the fixes in PR #2581, `mise i ruby@truffelruby+graalvm' will install the latest version, likewise will `mise i ruby@truffelruby-24` install the latest 24.x version.

**Comment by roele** [comment]
@ylluminate Yes this should download/install the latest `truffleruby+graalvm` version, which it does on my machine.

```
mise --verbose i ruby@truffleruby+graalvm
[DEBUG] ARGS: /Users/roele/.local/bin/mise --verbose i ruby@truffleruby+graalvm
[DEBUG] Config {
    Config Files: [
        "~/.config/mise/config.toml",
    ],
}
[DEBUG] ToolRequestSet.build(66.5µs): ToolRequestSet: go@latest java@temurin-21 maven@latest node@latest rust@latest usage@latest

[DEBUG] install_versions: ruby@truffleruby+graalvm
[DEBUG] $ /Users/roele/Library/Caches/mise/ruby/ruby-build/bin/ruby-build --version
[DEBUG] GET https://api.github.com/repos/rbenv/ruby-build/releases/latest
[DEBUG] starting new connection: https://api.github.com/
[DEBUG] proxy(http://127.0.0.1:64097) intercepts 'https://api.github.com/'
[DEBUG] GET https://api.github.com/repos/rbenv/ruby-build/releases/latest 200 OK
running ruby-build
[DEBUG] $ ~/Library/Caches/mise/ruby/ruby-build/bin/ruby-build --verbose truffleruby+graalvm-24.1.0 /Users/roele/.local/share/mise/installs/ruby/truffleruby+graalvm-24.1.0
cd /var/folders/pn/7y1cts750dbgghdb3q14hprw0000gn/T/ruby-build.20240924120614.89677.CGxGMG
==> Downloading truffleruby-jvm-24.1.0-macos-aarch64.tar.gz...
```

**Comment by roele** [comment]
I am also seeing build errors from `ruby-build`, it seems the tool has some dependencies. After installing them (in my case `libayml`) via Homebrew it seems to work fine though.

```
==> Installing truffleruby+graalvm-24.1.0...
-> ./lib/truffle/post_install_hook.sh
Recompiling the OpenSSL C extension (against the installed libssl)
Could not find libyaml headers, install via Homebrew or MacPorts or set LIBYAML_PREFIX
external command failed with status 1
BUILD FAILED (macOS 15.0 on arm64 using ruby-build 20240917)
You can inspect the build directory at /var/folders/pn/7y1cts750dbgghdb3q14hprw0000gn/T/ruby-build.20240924121031.89956.qDKKjx
[ERROR] ~/Library/Caches/mise/ruby/ruby-build/bin/ruby-build failed
Error:
   0: ~/Library/Caches/mise/ruby/ruby-build/bin/ruby-build exited with non-zero status: exit code 1

Location:
   src/cmd.rs:400

Version:
   2024.9.7 macos-arm64 (743b7a7 2024-09-23)

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets
```

**Comment by eregon** [comment]
ruby-build requires you to install dependencies first, see https://github.com/rbenv/ruby-build/wiki#suggested-build-environment

**Comment by eregon** [comment]
I would suggest to try installing some CRuby version then, probably it fails the same way.
I would guess either the C toolchain is broken (happens with macOS updates), or the openssl from Homebrew has some issue.
If installing CRuby succeeds then please file a truffleruby issue, maybe macOS 15.0 broke something,

**Comment by machadogadiel** [comment]
Guys, I hope this helps anyone, but somewhere in here it's written as `truffel` when the name is `truffle`, just be careful when copying and pasting, took me a few tries to figure it out!

**Comment by eregon** [comment]
Good catch, that's a typo from https://github.com/jdx/mise/issues/1737#issuecomment-2351658308 and explains why https://github.com/jdx/mise/issues/1737#issuecomment-2370347592 failed and later attempts went further.
