### ISSUE TITLE
Add java jetbrainsruntimes

### ISSUE THREAD

**Issue by MustCodeAl** [jdx/mise#1738]
add the ability to download these [java versions](https://github.com/JetBrains/JetBrainsRuntime)

**Comment by adamglin0** [comment]
This is very useful when developing desktop applications like Swing.

**Comment by roele** [comment]
@adamglin0 Jetbrains Runtime is available since a couple months.

**Comment by adamglin0** [comment]
@roele Although jbr exists on ls-remote, some jbr cannot be installed.

```
mise install java@jetbrains-21.0.6b895.109
mise To enable macOS integration, run the following commands:
sudo mkdir /Library/Java/JavaVirtualMachines/jetbrains-21.0.6b895.109.jdk
sudo ln -s /Users/adamglin/.local/share/mise/installs/java/jetbrains-21.0.6b895.109/Contents /Library/Java/JavaVirtualMachines/jetbrains-21.0.6b895.109.jdk/Contents

mise ERROR failed to install core:java@jetbrains-21.0.6b895.109
mise ERROR failed to execute command: ~/.local/share/mise/installs/java/jetbrains-21.0.6b895.109/bin/java -version
mise ERROR No such file or directory (os error 2)
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

**Comment by roele** [comment]
I'm afraid this is an issue with `mise` randomly picking the wrong package (debug ending with `_diz`) which contains binaries ending with `.diz`.

**Comment by adamglin0** [comment]
> I'm afraid this is an issue with `mise` randomly picking the wrong package (debug ending with `_diz`) which contains binaries ending with `.diz`.

I hava created a related discussion. https://github.com/jdx/mise/discussions/4969
