### ISSUE TITLE
Automatically install missing versions

### ISSUE THREAD

**Issue by danieleformichelli** [jdx/mise#1742]
Ciao 👋 

Have you considered automatically installing a tool version configured in `mise` config?

For example, when switching to a different branch using a different `tuist` version, it might fail to generate the project if I forgot to `mise install` first.

It could be a configurable option in case it could break some workflows, but I think it's very useful and in line with `mise` objective of ensuring you are using the right version of each tool.

Thank you! 🙏

**Comment by jdx** [comment]
there is a setting for this now for `mise x` and `mise run`

**Comment by danieleformichelli** [comment]
> there is a setting for this now for `mise x` and `mise run`

Could you please point to the documentation for future (and present) reference? 🙏
