### ISSUE TITLE
Allow ignore missing plugin

### ISSUE THREAD

**Issue by robsonpeixoto** [jdx/mise#1748]
When I run the command `mise install` it will ask if the tool should be installed or not, but when the answer is `NO` it stop the install process and do not ask for the next tool:

```text
❯ mise current
mise mkcert@latest is specified in ~/tmp/missing-plugin/.mise.toml, but not installed
mkcert latest
mise go@1.22.0 is specified in ~/tmp/missing-plugin/.mise.toml, but not installed
go 1.22.0

❯ mise install
mise ⚠️ mkcert is a community-developed plugin
mise url: https://github.com/salasrod/asdf-mkcert
 Would you like to install mkcert? No
mise [mkcert] plugin not installed
mise Run with --verbose or MISE_VERBOSE=1 for more information
```

May could have 3 options:
- yes (install and continue)
- no (do not install and ask for the next tool)
- quit (do not install and stop)

And/or add a option `--ignore-missing-plugin` to `mise install` command.

Thanks for this amazing tool :heart:

**Comment by jdx** [comment]
related to #2099
