### ISSUE TITLE
Ruby gets installed during `mise install` although it's already installed on CI machine

### ISSUE THREAD

**Issue by mflknr** [jdx/mise#1765]
**Describe the bug**
Hey, 
when I run `mise install` on our CI environment it installs all tools successfully. However in contrast to our local development machines (all MacOS) `mise` also installs and downloads ruby when installing `tuist`. As far as I can tell it does not need to install another ruby version because the exact same version is already installed on the CI machine (location: `/Users/vagrant/.asdf/shims/ruby`). 

This is the current script we are using:
```sh
curl https://mise.run | sh
eval "$(mise activate zsh --shims)"
mise install
```

I also tried to add `export PATH="$HOME/.local/bin:$PATH"` and `echo "eval \"\$(/Users/vagrant/.local/bin/mise activate zsh)\"" >> "/Users/vagrant/.zshrc"` which didn't do much (which I did not expect tbh.).

Also this issue does not seem to occur on Xcode Cloud. We are using [Bitrise](https://bitrise.io). If you need any information in regards to the CI machines or the environment I can try to provide them.

**To Reproduce**
Run the mentioned script on bitrise. Since this is probably hard to reproduce for you I am not even sure if this is a bug or a miss-configuration on my end.

**Expected behavior**
I would expect that the already installed ruby version on the machine is used and not downloaded and installed additionally.

**`mise doctor` output**

```text
+ mise doctor
version: 2024.3.1 macos-arm64 (0d95fde 2024-03-04)
activated: no
shims_on_path: yes
build_info: 
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Mon, 4 Mar 2024 22:02:06 +0000
  Rust Version: rustc 1.76.0 (07dca489a 2024-02-04)
  Profile: release
shell: 
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin22.0)
dirs: 
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/Library/Caches/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims
config_files: 
  ~/.tool-versions
  ~/git/Gemfile
  ~/git/.mise.toml
plugins: 
  bun     (core)
  deno    (core)
  go      (core)
  java    (core)
  node    (core)
  python  (core)
  ruby    (core)
toolset: 
  tuist@4.4.0         (missing)
  swiftlint@0.54.0    (missing)
  swiftformat@0.53.3  (missing)
  sourcery@2.1.7      (missing)
  ruby@3.2.3          (missing)
  go@1.21.8           (missing)
  node@18.19.1        (missing)
env_vars: 
  (none)
settings: 
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cargo_binstall = true
  color = true
  disable_default_shorthands = false
  disable_tools = []
  experimental = false
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  node_compile = false
  not_found_auto_install = true
  paranoid = false
  plugin_autoupdate_last_check_duration = "7d"
  python_compile = false
  python_default_packages_file = "/Users/vagrant/.default-python-packages"
  python_pyenv_repo = "https://github.com/pyenv/pyenv.git"
  raw = false
  trusted_config_paths = []
  quiet = false
  verbose = false
  yes = true
  ci = true
  debug = false
  trace = false
  log_level = "info"
  python_venv_auto_create = false
  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false
No problems found
```

**Additional context**
Our .toml file looks like this:
```
[tools]
tuist = "4.4.0"
swiftlint = "0.54.0"
swiftformat = "0.53.3"
sourcery = "2.1.7"
```

**Comment by jdx** [comment]
mise doesn't care about what is already on the system
