### ISSUE TITLE
`jq` Installed Using x86_64 on Apple Silicon Using Mise

### ISSUE THREAD

**Issue by Blackjacx** [jdx/mise#1767]
### Describe the bug

[Mise](https://github.com/jdx/mise) uses [ASDF plugins](https://github.com/asdf-vm/asdf-plugins) to install development tools. For jq it installs the Intel version of `jq`. 

### To Reproduce

1. Create empty folder
1. Install mise using `curl https://mise.run | sh`
1. Create a config folder structure: `mkdir -p .config/mise`
1. Add [these](https://github.com/Blackjacx/Scripts/tree/main/bootstrap/config_dirs/mise) Mise config files to the created folder
1. Run `mise install`
1. Compare `file ${HOME}/.local/share/mise/installs/fzf/0/bin/fzf` with `file ${HOME}/.local/share/mise/installs/jq/1/bin/jq`

### Expected behavior

Mise should install the arm64 version of `jq` instead of the x86_64 one, like it does for for [fzf](https://github.com/junegunn/fzf), mise installs the arm64 vesion correctly.

When installing `jq` via Homebrew the arm version gets installed.

### Environment (please complete the following information)

- macOS 14.3.1 (23D60)
- Mise: 2024.3.1 macos-arm64 (0d95fde 2024-03-04)
- jq 1.7.1

**Comment by roele** [comment]
The command `mise plugin ls-remote -u | grep asdf-jq` reveals that `https://github.com/lsanwick/asdf-jq` is used. Looking at the repository there is an open [pull request](https://github.com/lsanwick/asdf-jq/pull/8) regarding ARM builds wich is likely the cause of this issue.

**Comment by jdx** [comment]
forked to https://github.com/mise-plugins/asdf-jq if anyone wants to take this on. If people think kc-workspace/asdf-jq is better I'd be happy to switch to that as our base.

**Comment by roele** [comment]
Did a rewrite of the plugin with https://github.com/mise-plugins/asdf-jq/pull/1 which hopefully is much simpler and works a bit better than what's currently out there for `jq`.

Once thats signed off we can update the shorthand and use this variant for mise.
