### ISSUE TITLE
Excessive RAM usage building with the release profile

### ISSUE THREAD

**Issue by barraponto** [jdx/mise#1775]
**Describe the bug**
Under archlinux, the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mise) runs `cargo build --frozen --release` and it uses up to 10GB RAM for the build. Is there something we can do to optimize this much RAM usage?

**To Reproduce**
clone the repo, cd to the repo
```sh
  export RUSTUP_TOOLCHAIN=stable
  export CARGO_TARGET_DIR=target
  cargo build --frozen --release
```

**Expected behavior**
Compile with a reasonable amount of RAM usage.

**Comment by jdx** [comment]
disable lto

**Comment by barraponto** [comment]
to tell you the truth, i didn't know how to file it either. it is not a feature request or a security issue, afaict.

I believe `cargo build --release` is pretty common, although from what i see in the CI files it seems like mise releases do not use the release profile and never see this issue. But `lto` is set to true in mise's `Cargo.toml` so maybe that's something we could (or should) change?
