### ISSUE TITLE
Add support for optional env files

### ISSUE THREAD

**Issue by mrjk** [jdx/mise#1777]
### Use case

When you want to distribute your `.mise.toml` and let user creates creates their own env files as such:
```
$ cat .mise.toml
[[env]]
_.file = '.env'          # Commited file
[[env]]
_.file = '.env.secrets'  # Git ignored file
[[env]]
_.file = '.env.local'    # Git ignored file
```

If one of these file is missing, you'll get:
```
mise failed to parse dotenv file: /work/.env.secrets
mise No such file or directory (os error 2)
mise No such file or directory (os error 2)
mise Run with --verbose or MISE_VERBOSE=1 for more information
```

Unless I'm wrong, I don't feel `MISE_ENV` variable can fill the gap here. Also, direnv also implement a such option: https://github.com/direnv/direnv/blob/master/stdlib.sh#L273 .

### Proposal

I suggest the following implementation to stick to the existing conventions:
```
$ cat .mise.toml 
[[env]]
_.file = '.env'                   # Commited file
[[env]]
_.file_optional = '.env.secrets'  # Git ignored file
[[env]]
_.file_optional = '.env.local'    # Git ignored file
```
### Sidenote proposal

On the proposal take, the toml syntax is ... hmm how to say ... Can we imagine something more like this instead ?
```
$ cat .mise.toml 
[env]
_.file = '.env'                                    # Commited file
_.file_optional = ['.env.secrets', '.env.local']   # Git ignored file
```
But I don't know at all the implication of such change. If this can be a thing, I'll make another issue on that.

### Workaround1: Failed

Let's say I only want to use mise, you could try to come up with:
```
$ cat .mise.toml
[[env]]
_.file = '.env'
[[env]]
_.file = '.env.secrets'
[[env]]
_.file = '.env.local'

[tasks.fix_missing_env]
description = 'Ensure project is correctly setup'
run = """
#!/usr/bin/env bash

echo "I will never be able to run anyway if one of the file I want to touch is missing"
touch .env.secrets
"""
```

but unfortunately It will not work and fail with:
```
$ mise task run fix_missing_env
mise failed to parse dotenv file: /work/.env.secrets
mise No such file or directory (os error 2)
mise No such file or directory (os error 2)
mise Run with --verbose or MISE_VERBOSE=1 for more information
mise failed to parse dotenv file: /work/.env.secrets
mise No such file or directory (os error 2)
mise No such file or directory (os error 2)
mise Run with --verbose or MISE_VERBOSE=1 for more information
```

I guess I could create an issue for that.

### Workaround2: Works

I currently use this temporary workaround:
```
$ cat .mise.toml 
[env]
_.source = "./scan_env.sh"          # Commited file
```
And the `scan_env.sh` actually do the `.env.*` loading logic if files exists without throwing an error. But it looks like a beautiful anti-pattern and this completely defeat the mise legitimacy in this case.

Ho, and I forgot, thanks for this amazing project :) :+1: :heart:

**Comment by jdx** [comment]
I could see adding this, however we do have [`MISE_ENV_FILE`](https://mise.jdx.dev/configuration.html#mise-env-file) which makes this possible today I think

**Comment by mrjk** [comment]
Ho, interesting, but how would you do with the `MISE_ENV_FILE`? I do not expect the user to do prior tuning or commands to make this to work, I like plug and plays stuffs ^^

**Comment by edvardm** [comment]
Could it be something like this? What's really nice in direnv is that you can create chain of overrides, quick example on how I tend to use it:

```bash
dotenv defaults.env      # this is in version control, typically contains values that work for local development
dotenv_if_exists .env    # not in version control, but allow overriding values in defaults.env
```

so maybe something like

```toml
[env]
_.file = 'defaults.env'   # in version control
_.optional_file = '.env'  # not in version control
```

meaning I'd take more opinionated route in a sense that if many files can be declared as optional. Just pick one,
and make everyone happy ;) (cf. Golang philosophy)

Also, thanks _a lot_ for great tool. I've been looking for a tool that would improve local devexp without need to add multiple tools, and the fact that you created more convenient asdf wrapper _and_ included a savvy task runner too there, is just amazing. Love it already!

**Comment by jdx** [comment]
I think this would be better:

```toml
[[env]]
_.file = {path = 'defaults.env'}   # in version control
[[env]]
_.file = {path = '.env', optional = true}  # not in version control
```

that way if we add other options they can be used together

**Comment by edvardm** [comment]
> I think this would be better:

Fully agree, you're suggestion is cleaner. Also just learned that [12factor guide](https://12factor.net/config) even advices against using multiple variables, and I'd agree if it went as crazy as described in the post. So I still think ability to override /add to base config would be useful, nothing wrong in two files.

**Comment by hinricht** [comment]
Looking forward to this! Out team want to migrate from direnv to mise but this lacking feature makes it harder for us.

**Comment by idletea** [comment]
> I could see adding this, however we do have [`MISE_ENV_FILE`](https://mise.jdx.dev/configuration.html#mise-env-file) which makes this possible today I think. Though I admit it's a bit different.

I think it'd make sense to have the same behaviour already used when that env var is set, just available as a 'real' config value.

I've actually be using

```
[env]
MISE_ENV_FILE='.env'
```

as a discount version of this feature, that only thing about it that's not nice is that it never work on the first `cd` into a project since the first run of the mise hook only sets the env var, it doesn't actually use it until the next prompt draw.

**Comment by joshuataylor** [comment]
With this being closed, does this still mean it should no longer warn when the file does not exist?

e.g, if `.missingenv` does not exist, `.mise.toml`:

```toml
[env]
mise.file = ".missingenv"
```

or
```toml
[env]
_.file = ".missingenv"
```

```sh
$ cd dev/missing
DEBUG ARGS: mise hook-env -s zsh
DEBUG config: ~/dev/missing/.mise.toml
DEBUG config: ~/.config/mise/config.toml
DEBUG glob: "/home/josh/dev/missing/.missingenv"
DEBUG EnvResults { env_files: ["/home/josh/dev/missing/.missingenv"] }
Error:
   0: No such file or directory (os error 2)

Location:
   src/hook_env.rs:132

Version:
   2024.11.36 linux-x64 (0461143 2024-11-29)

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 2 frames hidden ⋮
   3: mise::cli::hook_env::HookEnv::build_watch_operation::hba1b6a4724e54c19
      at <unknown source file>:<unknown line>
   4: mise::cli::hook_env::HookEnv::run::heeba92ec8f0eab8a
      at <unknown source file>:<unknown line>
   5: mise::cli::Cli::run::he3b097384a86ca7b
      at <unknown source file>:<unknown line>
   6: mise::main::hbb15ddbd45c7fee8
      at <unknown source file>:<unknown line>
   7: std::sys::backtrace::__rust_begin_short_backtrace::h830745692faa355e
      at <unknown source file>:<unknown line>
   8: main<unknown>
      at <unknown source file>:<unknown line>
   9: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>
  10: _start<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
DEBUG ARGS: mise hook-env -s zsh
DEBUG config: ~/dev/missing/.mise.toml
DEBUG config: ~/.config/mise/config.toml
DEBUG glob: "/home/josh/dev/missing/.missingenv"
DEBUG EnvResults { env_files: ["/home/josh/dev/missing/.missingenv"] }
Error:
   0: No such file or directory (os error 2)

Location:
   src/hook_env.rs:132

Version:
   2024.11.36 linux-x64 (0461143 2024-11-29)

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 2 frames hidden ⋮
   3: mise::cli::hook_env::HookEnv::build_watch_operation::hba1b6a4724e54c19
      at <unknown source file>:<unknown line>
   4: mise::cli::hook_env::HookEnv::run::heeba92ec8f0eab8a
      at <unknown source file>:<unknown line>
   5: mise::cli::Cli::run::he3b097384a86ca7b
      at <unknown source file>:<unknown line>
   6: mise::main::hbb15ddbd45c7fee8
      at <unknown source file>:<unknown line>
   7: std::sys::backtrace::__rust_begin_short_backtrace::h830745692faa355e
      at <unknown source file>:<unknown line>
   8: main<unknown>
      at <unknown source file>:<unknown line>
   9: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>
  10: _start<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```
