### ISSUE TITLE
Add plugin specific ENV?

### ISSUE THREAD

**Issue by h3adache** [jdx/mise#1798]
Is it possible to override ENV for just one specific plugin?
I am facing an issue where an older version of `teleport-ent` was not built for `darwin-amd64`.

This results in an error when we try to just run `mise install`

```
mise install
curl: (22) The requested URL returned error: 404
mise ~/.local/share/mise/plugins/teleport-ent/bin/download failed
* Downloading teleport-ent release 11.3.11...
curl: (22) The requested URL returned error: 404
asdf-teleport-ent: Could not download https://cdn.teleport.dev/teleport-ent-v11.3.11-darwin-arm64-bin.tar.gz
mise ~/.local/share/mise/plugins/teleport-ent/bin/download exited with non-zero status: exit code 1
mise Run with --verbose or MISE_VERBOSE=1 for more information
```

The workaround is to run with `ARCH`
```
ARCH=amd64 mise install teleport-ent 11.3.11
```

But it could be nice for this and future scenarios if env could be targeted to plugins. e.g.
```
[env]
TELEPORT_ENT_ARCH=amd64
```

**Comment by jdx** [comment]
this is impossible. mise would need to wrap every command but that simply is not how it works

**Comment by jdx** [comment]
I think we should have a tool option for env:

```toml
[tools]
teleport-ent = { version = "11.3.11", env = { ARCH = "amd64" } }
```
