### ISSUE TITLE
Add variable for specific mise version during installation

### ISSUE THREAD

**Issue by Its-Alex** [jdx/mise#1800]
Hello :wave: I would like to be able to install a specific version of `mise` with the official install script (https://mise.run/).

Is it possible to create an environment variable, for example `MISE_VERSION` that can be defined during installation [here](https://github.com/jdx/mise/blob/4f13c6329f358bb0ff9dc750984ddeef14d1f4e4/packaging/standalone/install.envsubst#L151) ?

Thanks in advance.

**Comment by jdx** [comment]
I'd accept a PR. I think we could either configure it via an env var or with `curl https://mise.run | sh -s -- --version xxx`

Here's an example of how to do it if anyone wants to contribute: https://github.com/crablang/crablang-site/blob/b4f3a38b30fad69902c188085c92566ef577e365/public/crabup-init.sh#L26

**Comment by Its-Alex** [comment]
@jdx I made a PR, tell me if you want me to change something
