### ISSUE TITLE
allow setting MISE_RUBY_INSTALL and other ruby configs in toml file

### ISSUE THREAD

**Issue by glyh** [jdx/mise#1808]
For now I have to put this in my fish config, which is not ideal.

**Comment by glyh** [comment]
BTW it would also be nice if user can set mirrors for the cache site.

**Comment by jdx** [comment]
you can use universal variables in fish

**Comment by glyh** [comment]
Yes and that's how it work on my machine. What if someday I decided to switch to another shell?

**Comment by jdx** [comment]
this is possible by using settings now
