### ISSUE TITLE
Ruby ls-remote not showing alternative implementations

### ISSUE THREAD

**Issue by tycooon** [jdx/mise#1854]
When I run `mise ls-remote ruby`, I only receive MRI version list for some reason. Howerver, other versions are available and work properly, for example I can run `mise shell ruby@truffleruby-24.0.0` and use TruffleRuby.

**Comment by roele** [comment]
The core plugin uses `rbenv/ruby-build` under the hood to get the definitions but filters explicitly for semantic versions.

https://github.com/jdx/mise/blob/c99a39fa9768b88d6f79a978bf7a5493eb632ea4/src/plugins/core/ruby.rs#L169

I'm quite sure excluding the others was a conscious decision by @jdx as non-semantic versions usually cause headaches.

**Comment by jdx** [comment]
I actually have no idea why I did that. I thought maybe asdf-ruby did the same but no:

https://github.com/asdf-vm/asdf-ruby/blob/master/bin/list-all#L13

I would be curious if topaz-dev still exists, if not, then we should just list everything coming from ruby-build.

**Comment by roele** [comment]
> I would be curious if topaz-dev still exists, if not, then we should just list everything coming from ruby-build.

`ruby-build` does not list `topaz-dev` (anymore) from what i can see.

**Comment by jdx** [comment]
Yeah let's just get rid of that filter
