### ISSUE TITLE
Target mise releases with automated tools

### ISSUE THREAD

**Issue by darthbanana13** [jdx/mise#1860]
Hi,

With my workflow I noticed that it's difficult to target mise, for automated installation & download because of the period '.' in the name of the assets.

For example , given the latest assets present on the GitHub releases page:

```
mise-v2024.4.0-linux-arm64
mise-v2024.4.0-linux-arm64-musl
mise-v2024.4.0-linux-arm64-musl.tar.gz
mise-v2024.4.0-linux-arm64-musl.tar.xz
mise-v2024.4.0-linux-arm64.tar.gz
mise-v2024.4.0-linux-arm64.tar.xz
mise-v2024.4.0-linux-armv6
mise-v2024.4.0-linux-armv6-musl
mise-v2024.4.0-linux-armv6-musl.tar.gz
mise-v2024.4.0-linux-armv6-musl.tar.xz
mise-v2024.4.0-linux-armv6.tar.gz
mise-v2024.4.0-linux-armv6.tar.xz
mise-v2024.4.0-linux-armv7
mise-v2024.4.0-linux-armv7-musl
mise-v2024.4.0-linux-armv7-musl.tar.gz
mise-v2024.4.0-linux-armv7-musl.tar.xz
mise-v2024.4.0-linux-armv7.tar.gz
mise-v2024.4.0-linux-armv7.tar.xz
mise-v2024.4.0-linux-x64
mise-v2024.4.0-linux-x64-musl
mise-v2024.4.0-linux-x64-musl.tar.gz
mise-v2024.4.0-linux-x64-musl.tar.xz
mise-v2024.4.0-linux-x64.tar.gz
mise-v2024.4.0-linux-x64.tar.xz
mise-v2024.4.0-macos-arm64
mise-v2024.4.0-macos-arm64.tar.gz
mise-v2024.4.0-macos-arm64.tar.xz
mise-v2024.4.0-macos-x64
mise-v2024.4.0-macos-x64.tar.gz
mise-v2024.4.0-macos-x64.tar.xz
SHASUMS256.asc
SHASUMS256.txt
SHASUMS512.asc
SHASUMS512.txt
```

It is difficult with an automated script to target an executable for x86_64 systems because most extension extracting functions in programming languages, including Rust with the `extension()` method from `std::path::Path` would interpret `mise-v2024.4.0-linux-x64` as having a `0-linux-x64` extension and `mise-v2024.4.0-linux-x64-musl` as having a `0-linux-x64-musl` extension.

Workarounds are not easy, relying on unknown extensions being executables is problematic. Having the file on disk, an alternative would involve opening the file and reading the headers to determine what type of file it is. This is considerably harder to do and comes with the added downside that a wrong file might have been downloaded initially.

Please, replace the the period in the name with another character like dash '-' or underscore '_', or simply using no character for the date and one character to segregate the version like `mise-v202404-0-linux-x64`. Any alternative that would not use periods would be better.

**Comment by jdx** [comment]
This doesn't seem like a very big problem to me but the fix would require a breaking change I think would create a far worse problem.
