### ISSUE TITLE
`mise shell --unset` should not need currently the currently set version number

### ISSUE THREAD

**Issue by yggdr** [jdx/mise#1868]
Currently, I need to `mise shell -u python@3.9.18` to remove it from my $PATH, when a simple `mise shell -u python` should suffice, as the version can be deduced.

**Comment by jdx** [comment]
I haven't looked at the code for this in a while but I suspect the reason for this is if you have multiple versions specified it wouldn't be able to know which one to remove. Of course, we could just have logic for that that simply removes if there is only one version specified.

**Comment by yggdr** [comment]
How can you have multiple versions specified per environment variables? If I `mise shell python@3.9.18` it overwrites the previously set `mise shell python@2.7.18`. In fact, it now seems to me that mise completely ignores the version given, I can `mise shell python@$V1` and then `mise shell -u python@$ANY_OTHER_VALID_VERSION`. So long as the underlying python-build script knows the version, it works in deactivating it. Why python-build is even involve in `mise shell -u` is however a mystery to me.
