### ISSUE TITLE
mise use python@3.12.3 (or 3.11.9) hanging

### ISSUE THREAD

**Issue by mscrivo** [jdx/mise#1884]
**Describe the bug**
new python patch releases were released recently for 3.11 & 3.12. Upon trying to upgrade to them with `mise use python @3.12.3` for example, it is often hanging during build indefinitely (could be hours if you leave it running). The strange thing is that it will sometimes succeed if you cancel it and try again.

**To Reproduce**

`mise use python@3.12.3 --verbose`

Note that it always get stuck with this as the last line in the output: 

```
checking for python3.12... python3.12
```

**Expected behavior**
build should be completed within a reasonable time or be cancelled immediately if something is wrong.

**`mise doctor` output**

```text
version: 2024.4.3 macos-arm64 (2024-04-09)
activated: no
shims_on_path: yes

build_info:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS
  Built: Tue, 9 Apr 2024 18:38:48 +0000
  Rust Version: rustc 1.77.1 (7cf61ebde 2024-03-27) (Homebrew)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin23.0)

dirs:
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/Library/Caches/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims

config_files:
  ~/.config/mise/config.toml
  ~/.mise.toml

plugins:
  bun     (core)
  deno    (core)
  go      (core)
  java    (core)
  node    (core)
  pnpm    https://github.com/jonathanmorley/asdf-pnpm.git#305baff
  python  (core)
  ruby    (core)

toolset:
  python@3.12.3
  node@20.12.1
  ruby@3.3.0
  pnpm@8.15.6

env_vars:
  (none)

settings:
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cargo_binstall = true
  color = true
  disable_default_shorthands = false
  disable_tools = []
  experimental = false
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  node_compile = false
  not_found_auto_install = true
  paranoid = false
  plugin_autoupdate_last_check_duration = "7d"
  python_compile = false
  python_default_packages_file = "/Users/michaelscrivo/.default-python-packages"
  python_pyenv_repo = "https://github.com/pyenv/pyenv.git"
  raw = false
  trusted_config_paths = []
  quiet = false
  verbose = false
  yes = false
  ci = false
  debug = false
  trace = false
  log_level = "info"
  python_venv_auto_create = false

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false

No problems found
```

**Additional context**

I'm not sure if this a problem with mise particularly or with the python plugin, but we never had such problems when using adsf.

**Comment by mscrivo** [comment]
One other thing to note, is that when it fails, it seems to leave the previous python installation in a broken state. ie. if I go back to 3.12.2 with `mise use python@3.12.2` and try to use a pip installed pkg, it tells me it can't find it. reinstalling pkgs with pip does not fix it as it thinks they are already installed. So I had to completely remove all python installations with `mise remove python@3.12 --all`, reinstall, pip install -r requirements and reshim before they would again.

**Comment by roele** [comment]
Using the `--verbose` flag will deadlock as already reported with #1830 but i assume the issue also occurs without the flag, correct?

**Comment by mscrivo** [comment]
Yes that's correct, you just get no output at all

**Comment by roele** [comment]
`mise` installs a precompiled version as per `curl http://mise-versions.jdx.dev/python-precompiled` if available, otherwise tries to build from source which requires some dependencies as mentioned at https://mise.jdx.dev/lang/python.html#python-build. Might be that some are missing or that something changed in the build process of newer versions.

**Comment by mscrivo** [comment]
on a related note, a nice feature addition might be the ability to install/upgrade to only versions that have a precompiled binary.

**Comment by mscrivo** [comment]
Thanks @kevinji glad to have confirmation it's not just our setup. And your hypothesis seems sound to me.

**Comment by jdx** [comment]
deadlocking certainly sounds like a possibility when attempting to install the same tool. mise uses some lockfiles that should prevent such a situation that I believe will output extra information if the log level is set to trace we could use to confirm this situation.

Race conditions are notoriously difficult problems to prevent against and I have not tested those situations thoroughly or even done more than a naive best-effort trying to mitigate them so us having problems there doesn't surprise me.

It may be worth attempting something like this to see what happens:

```
$ mise install python@3.11.9 & --trace
$ mise install python@3.11.9 --trace
```

**Comment by mscrivo** [comment]
I will play around with those and see if I can get any more info, but I think a bigger question here might be, is mise trying to be overly helpful here with it's ability to build a tool when it sees it doesn't exist? 

In my opinion, only user initiated actions like `mise use\install\upgrade` should be building a tool if it doesn't exist or is not up to date. Just calling python when the tool is not there, should not trigger an install, it should just fail with "python not found". That would then prevent this whole class of issues altogether and we wouldn't have to come up with workarounds for race conditions.

**Comment by kevinji** [comment]
I believe this is controlled by [`MISE_NOT_FOUND_AUTO_INSTALL`](https://mise.jdx.dev/configuration.html#mise-not-found-auto-install-true) which defaults to true.

**Comment by pdecat** [comment]
Perhaps [MISE_NOT_FOUND_AUTO_INSTALL](https://mise.jdx.dev/configuration.html#mise-not-found-auto-install-true) should be disabled by default for `mise upgrade` commands to avoid deadlocks during installation of packages that invoke themselves.
