### ISSUE TITLE
`mise activate` switch between interactive script and shims

### ISSUE THREAD

**Issue by texastoland** [jdx/mise#1886]
I found a [dead simple pattern](https://github.com/texastoland/dotfiles/blob/6d0be43c7ceb954765806773556617371b366fa1/.zshrc#L22-L25) (confirmed in both zsh and bash):

```sh
if [[ -t 0 ]]; then # terminal has stdin i.e. interactive
  eval "$(mise activate "$SHELL_NAME")"
else
  eval "$(mise activate --shims)"
fi
```

Explained in [my tweets](https://x.com/texastoland/status/1776030275023094159):

> Modern editors either receive their environment from the command line or more often read it similar to `zsh -ilc` env. That session is "interactive" (and login) in order to trigger all user configs. But that broke my dotfile's assumption. But how to check "interactive"? AFAICT `[[ -t 0 ]]` might be what I'm looking for because it fails (`false`) when editors are reading the environment

Would you be interested in either PR:

- an `--auto` flag that checks if stdin is readable internally (or)
- adding the above to the website

**Comment by kjkent** [comment]
if it helps anyone, `$shell_name` (I use lowercase vars in scripts to avoid global env clashes) can be pulled from `$SHELL` with:

```Shell
echo -n "$SHELL" | sed 's>.*/>>'
```
I believe `-n`  (no newline) isn't portable, but I'm unsure if it's necessary.

My `.zshenv` includes:
```Shell
if type mise &> /dev/null; then
        if [[ -t 0 ]]; then # terminal has stdin i.e. interactive
                shell_name="$(echo "$SHELL" | sed -E 's>.*/>>')"
                eval "$(mise activate "$shell_name")"
        else
                eval "$(mise activate --shims)"
        fi
fi
```

Thanks for the tip :)

**Comment by texastoland** [comment]
> `$shell_name` ... can be pulled from `$SHELL`

Yeah there are a few ways but I chose the following in my `.zshrc`:

```sh
SHELL_NAME=${ZSH_VERSION:+zsh}${BASH_VERSION:+bash} # sourced in .bashrc
```

A hypothetical `--auto` flag might be able to do that too.

**Comment by jdx** [comment]
there's been improvements in `mise activate` such that changing directory will update PATH so you may find that shims are not necessary—but it depends on what you're doing since there are non-interactive situations that still won't work correctly without shims. Given that, the choice is actually more complex now. I wouldn't be in favor of something like this at least right now.

**Comment by texastoland** [comment]
I just read the latest docs. They recommend configuring IDEs for each binary or else prefixing `mise x`/`r` otherwise. Is that current best practice?

**Comment by jdx** [comment]
I haven't changed the guidance because there are too many caveats. I'm just saying that under the hood changes have been made that makes some use-cases compatible with `mise activate` where previously shims were required.
