### ISSUE TITLE
core java plugin - inconsistent version resolution

### ISSUE THREAD

**Issue by mpern** [jdx/mise#1887]
**Describe the bug**

Version resolution is inconsistent between JVM vendors.
Root cause being that the versions aren't consistent between vendors.

**To Reproduce**

Make sure to run this with no local installs of java

```sh
> mise use java@17
...
mise ~/foo/.mise.toml tools: java@17.0.2
> java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
```
✅ You get the latest openjdk 17 release

```
> mise use java@sapmachine-17
...
mise ~/foo/.mise.toml tools: java@sapmachine-17
> java -version
openjdk version "17" 2021-09-14 LTS
OpenJDK Runtime Environment SapMachine (build 17+35-LTS-sapmachine)
OpenJDK 64-Bit Server VM SapMachine (build 17+35-LTS-sapmachine, mixed mode)
```
❌  You get the initial sapmachine 17 release, not the most recent which would be 17.0.10 at the time of writing

```
❯ mise ls-remote java@sapmachine-17
sapmachine-17
sapmachine-17.0.1
...
sapmachine-17.0.10
sapmachine-17.0.4-snapshot.0
sapmachine-17.0.7-snapshot.1
```

**Expected behavior**

Regardless of the vendor, if I use just the major version, I get the latest patch release for said version as per "fuzzy matching"

**`mise doctor` output**

<details>
<summary>`mise doctor`</summary>

```text
version: 2024.4.0 macos-arm64 (2024-04-02)
activated: yes
shims_on_path: yes

build_info:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS
  Built: Tue, 2 Apr 2024 01:55:39 +0000
  Rust Version: rustc 1.77.1 (7cf61ebde 2024-03-27) (Homebrew)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin23.0)

dirs:
  data: ~/.../.mise
  config: ~/.../.mise
  cache: ~/.../.mise
  state: ~/.../.mise
  shims: ~/.../.mise/shims

config_files:
  ~/.../.mise/config.toml
  ~/.../foo-mise-java/.mise.toml

plugins:
  bun     (core)
  deno    (core)
  go      (core)
  gradle  https://github.com/rfrancis/asdf-gradle.git#ffc271c
  java    (core)
  maven   https://github.com/halcyon/asdf-maven.git#83fb4db
  node    (core)
  python  (core)
  ruby    (core)
  vault   https://github.com/asdf-community/asdf-hashicorp.git#197e3ec

toolset:
  java@sapmachine-17
  maven@3.9.6
  node@18.20.1

env_vars:
  MISE_DIR=/Users/.../.mise
  MISE_CONFIG_DIR=/Users/.../.mise
  MISE_CACHE_DIR=/Users/.../.mise
  MISE_STATE_DIR=/Users/.../.mise
  MISE_DATA_DIR=/Users/.../.mise
  MISE_SHELL=zsh

settings:
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cargo_binstall = true
  color = true
  disable_default_shorthands = false
  disable_tools = []
  experimental = false
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  node_compile = false
  not_found_auto_install = true
  paranoid = false
  plugin_autoupdate_last_check_duration = "7d"
  python_compile = false
  python_default_packages_file = "/Users/I327130/.default-python-packages"
  python_pyenv_repo = "https://github.com/pyenv/pyenv.git"
  raw = false
  trusted_config_paths = []
  quiet = false
  verbose = false
  yes = false
  ci = false
  debug = false
  trace = false
  log_level = "info"
  python_venv_auto_create = false

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false

1 problem found:

1. new mise version 2024.4.3 available, currently on 2024.4.0
```
</details>

**Additional context**

Honestly I'm not quite sure if this should be a bug or a feature.

Interestingly enough, the problem is already recognized, at least for `openjdk` where major versions _are_ normalized already:

https://github.com/jdx/mise/blob/main/src/plugins/core/java.rs#L70-L71

otherwise `mise use java@17` would behave the same (incorrect) way 😄

**Comment by roele** [comment]
This looks inconsistent indeed, will need to dig into this since it works for some and not for others. In the meantime i would have suggested to use the workaround using a `prefix:` scope but it looks that is also not working as expected with #1888.

**Comment by roele** [comment]
Behaviour is consistent in the sense that it uses the "exact" match if found, otherwise falls back to newest available version (fuzzy) matching the provided version. The `@17` version is a shorthand for `openjdk` which behaves a bit differently as you have pointed out.

```
17 --> openjdk-17.0.2
openjdk-17 --> openjdk-17
sapmachine-17 --> sapmachine-17
liberica-17 --> liberica-17.0.10+13 (no liberica-17 version, so newest 17.x is installed)
oracle-17 --> oracle-17
```

**Comment by mpern** [comment]
to make it even more fun:

```sh
❯ mise use java@sapmachine-17.0.11
...
OpenJDK Runtime Environment SapMachine (build 17.0.11+9-LTS)
OpenJDK 64-Bit Server VM SapMachine (build 17.0.11+9-LTS, mixed mode, sharing)
mise java@sapmachine-17.0.11 ✓ installed
mise ~/foo/.mise.toml tools: java@sapmachine-17.0.11

❯ mise use java@sapmachine-17
mise ~/foo/.mise.toml tools: java@sapmachine-17.0.11
```

**Comment by mpern** [comment]
I humbly suggest to nnormalilze all versions when ingesting data for https://rtx-java-metadata.jdx.dev

**Comment by roele** [comment]
Interestingly this does not happen if `sapmachine-17` is already installed.

```bash
  ❯ mise i java@sapmachine-17

  ❯ mise use java@sapmachine-17.0.11
...
OpenJDK Runtime Environment SapMachine (build 17.0.11+9-LTS)
OpenJDK 64-Bit Server VM SapMachine (build 17.0.11+9-LTS, mixed mode, sharing)
mise java@sapmachine-17.0.11 ✓ installed
mise ~/foo/.mise.toml tools: java@sapmachine-17.0.11

  ❯ mise use java@sapmachine-17
mise ~/foo/.mise.toml tools: java@sapmachine-17
```

**Comment by mpern** [comment]
How about this:

Instead of making the version resolution logic more complicated, normalize the input data.

If java versions where consistent (major.minor.patch) across all vemdors in rtx-java-metadata, all of this would go away and you could even drop the secret sauce to make `java@21` work as expected.

Happy to help if that's the route you want to take.

**Comment by roele** [comment]
@mpern Agree that this might be a better solution but i assume this will be quite some effort. I'm not familiar with the java-metadata repo in detail but historic metadata would need to be updated manually as it is not updated automatically (only new versions are added AFAIK).

@jdx What is your take on this?

**Comment by jdx** [comment]
I'll let you decide, I don't have a strong preference.

**Comment by roele** [comment]
Okey, i'm clearly in favour of having a consistent solution by normalizing the versions in rtx-java-metadata.

**Comment by roele** [comment]
@mpern with PR https://github.com/jdx/rtx-java-metadata/pull/2 merged, this should be resolved now. After `mise cache clear` the command `mise ls-remote java` should show no more semantically incorrect versions.
