### ISSUE TITLE
mise panics if prefix: is used on certain core plugins

### ISSUE THREAD

**Issue by roele** [jdx/mise#1888]
**Describe the bug**
When using `prefix:` on certain plugins (bun, deno, java, ruby,..) the installation panics with following error.

**To Reproduce**
`mise i java@prefix:sapmachine-17`

**Expected behavior**
Installation is successful with latest version matching the prefix.

**Additional context**
Most likely related to following assertion used in the mentioned plugins.

```rust
 fn install_version_impl(&self, ctx: &InstallContext) -> Result<()> {
 ...
    assert!(matches!(
        &ctx.tv.request,
        ToolVersionRequest::Version { .. }
    ));
...
```

**Comment by roele** [comment]
@jdx Shouldn't be possible to use scopes via version suffix as well or was this only intended for configuration files?

**Comment by jdx** [comment]
I am not sure why that check is there. I think maybe I expect that the version was resolved at that point or something so if it was ToolVersionRequest::Prefix in the past it should at this point be resolved to ToolVersionRequest::Version. I would try adding ToolVersionRequest::Prefix and seeing if everything works, if so we can add that to the assertion

**Comment by roele** [comment]
Other core plugins like `go`, `node`, `python` don't have this assertion. Adding Prefix to the assertion works, question is if other scopes also would need to be supported and removal of the assertion would make more sense.
