### ISSUE TITLE
somehow avoid "incomplete" Python builds

### ISSUE THREAD

**Issue by egnor** [jdx/mise#1890]
(I honestly don't know whether this is best addressed in `mise`, in `python-build`, or in `cpython` itself... but this keeps coming up for me, and mise is the surface of the issue.)

When using Python, and a precompiled version is not available, mise will build Python. The Python build's `configure` script will detect local libraries that are available (openssl, zlib, bz2, sqlite, etc). If some of those aren't available, it will build Python without support for that functionality, e.g. if there are no ssl libs, you won't be able to `import ssl`.

That all makes sense but can be quite irritating, because `mise install` seems to succeed, but somewhere later down the line something fails with a somewhat confusing error message like `ModuleNotFoundError: No module named '_lzma'` and it often takes a while to track down and say "heyyyyy [make sure to set up the recommended build environment](https://github.com/pyenv/pyenv/wiki#suggested-build-environment)!" And it's not consistent and depends on whether a precompiled version happens to be available for whatever the latest minor version is when they set up their source tree, etc..

I view the point of mise as to provide consistent tooling and minimize exactly this kind of weird "works on my system, not yours" glitches so this is a bummer. The solution isn't obvious but I can think of a few fixes/workarounds?

1. Have a way to mandate precompiled binaries (which are always "complete") as suggested in https://github.com/jdx/mise/issues/1684

2. Have the ability to specify which optional stdlib modules MUST be present, and somehow pass that down to Python's `configure` script. (I actually can't find an obvious way to tell the cpython configure "if you can't build `_ssl`, fail".)

3. Have some sort of post-build qualification test that will say "hayyyy `python-build` succeeded but with the binary it made I can't `import _lzma` so ERROR ERROR, here's a helpful pointer to system-dependencies instructions". A little janky and if you forget to check for a specific thing you're back on square 1, but we could try to enumerate all the optional modules that Python might decide not to include? Or check `config.status` from cpython's configure directly??

4. Some other way that when, down the line, an import fails, you at least get a more helpful error message? Like... uh... add something to the end of `$PYTHONPATH` that includes stubs for such modules that raises a more informative exception message?

Some of these I could do as my own wrapper, but it feels like a more general problem-- do other people not run into this?

**Comment by ocervell** [comment]
+1 just stumbled into this and it took me a good amount of time to figure it out.

**Comment by Fury1** [comment]
I just ran into this as well. The easy solution for me was to just install the dependencies for building all of python. A production build could have more specificity later on I suppose.

I'm on Linux and it varies for each distro, source:
https://devguide.python.org/getting-started/setup-building/index.html#install-dependencies

**Comment by egnor** [comment]
Yes, that is the fix, once you find your way to the root of this issue. ([This is probably a better link](https://github.com/pyenv/pyenv/wiki#suggested-build-environment) for setting up dependencies.) This bug is about how this can lead to surprising downstream failures that are difficult to trace back to this issue, so it would be good to nab earlier rather than later.

**Comment by Fury1** [comment]
Yea I can see that. I sorta expected mise to just work but it didn't on Fedora (Arch worked just by luck of my previously installed packages) .

If complete python binaries are not available for download I think the user should be at least notified that python will be built with a link to build dependencies for pyenv or something before building. I wasn't even aware mise uses pyenv underneath as a new user.  Messages/instructions are often given with homebrew for example when working with packages.

**Comment by jdx** [comment]
doesn't pyenv already emit warnings about this visible under `mise install`?

**Comment by egnor** [comment]
Not in my experience, at least not very obvious ones.

**Comment by jdx** [comment]
seems it does:
```
root@eb8ce2fc0e60:/# MISE_ALL_COMPILE=true /root/.local/bin/mise install python
Downloading Python-3.12.4.tar.gz...
-> https://www.python.org/ftp/python/3.12.4/Python-3.12.4.tgz
Installing Python-3.12.4...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.local/share/mise/installs/python/3.12.4/lib/python3.12/bz2.py", line 17, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.local/share/mise/installs/python/3.12.4/lib/python3.12/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
WARNING: The Python curses extension was not compiled. Missing the ncurses lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.local/share/mise/installs/python/3.12.4/lib/python3.12/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
WARNING: The Python ctypes extension was not compiled. Missing the libffi lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'readline'
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.local/share/mise/installs/python/3.12.4/lib/python3.12/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/root/.local/share/mise/installs/python/3.12.4/lib/python3.12/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.local/share/mise/installs/python/3.12.4/lib/python3.12/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
WARNING: The Python lzma extension was not compiled. Missing the lzma lib?
Installed Python-3.12.4 to /root/.local/share/mise/installs/python/3.12.4
mise python@3.12.4 ✓ installed                                                             root@eb8ce2fc0e60:/#
```
