### ISSUE TITLE
Docs clarification: shims

### ISSUE THREAD

**Issue by kjkent** [jdx/mise#1892]
Hi there, and thanks to @jdx and the devs for their awesome work on mise. 

I'm trying to understand more about shims (their purpose and how they work), but the [docs](https://mise.jdx.dev/dev-tools/shims.html) say to consult the [beginner's guide](https://dev.to/jdxcode/beginners-guide-to-rtx-ac4)  for more info on what shims are and how they work -- and the beginner's guide says to read the docs for this info. A good ol' circular reference.

Apologies if I'm being dense here; but, I thought this worth pointing out as it seems shims hold importance for non-interactive use of mise.

Many thanks.

**Comment by jdx** [comment]
I wrote a blog post that might be helpful: https://jdx.dev/posts/2024-04-13-shims-how-they-work-in-mise-en-place/

**Comment by kjkent** [comment]
@jdx that's absolutely what I was looking for -- thank you!
