### ISSUE TITLE
where is the public GPG key signing releases?

### ISSUE THREAD

**Issue by rbauduin** [jdx/mise#1910]
It's great you sign the SH256SUM file published with releases on Github, but I didn't find the public GPG key published anywhere, meaning I can't verify the authenticity. It would be good to publish it to a location separated from Github. If it is already published somewhere, I missed it (which might be my fault....)

**Comment by chadlwilson** [comment]
Probably could be better documented, but that would be https://keyserver.ubuntu.com/pks/lookup?search=8B81C9D17413A06D&fingerprint=on&op=index I believe, based on

https://github.com/jdx/mise/blob/e79187f11814b8aefbd2046df5d05715afd96207/scripts/release.sh#L49-L50

**Comment by jdx** [comment]
I probably could add them somewhere but if nothing else you can find them here https://api.github.com/users/mise-en-dev/gpg_keys

**Comment by jdx** [comment]
if someone wants to add this somewhere to the [docs](https://github.com/jdx/mise-docs) I'd appreciate it
