### ISSUE TITLE
Cargo backend doesn't fetch the latest version

### ISSUE THREAD

**Issue by dParikesit** [jdx/mise#1931]
**Describe the bug**
There might be an edge case in the version fetching function that isn't handled. An example of it is for zellij (https://github.com/zellij-org/zellij). Zellij has a latest version of 0.40.0 which was released a week ago. But when I do `mise ls-remote cargo:zellij` or `mise use -g cargo:zellij` it only shows until version 0.39.2

```
✦ ❯ mise ls-remote cargo:zellij
0.0.1
0.1.0
0.1.1
0.2.0
0.2.1
0.3.0
0.3.1
0.3.2
0.3.3
0.5.0-beta
0.5.0
0.5.1
0.6.0
0.7.0
0.8.0
0.9.0
0.10.0
0.11.0
0.12.0
0.12.1
0.13.0
0.14.0
0.15.0
0.16.0
0.17.0
0.18.0
0.18.1
0.19.0
0.20.0
0.20.1
0.21.0
0.22.0
0.22.1
0.23.0
0.24.0
0.25.0
0.26.0
0.26.1
0.27.0
0.28.0
0.28.1
0.29.0
0.29.1
0.30.0
0.31.0
0.31.1
0.31.2
0.31.3
0.31.4
0.32.0
0.33.0
0.34.3
0.34.4
0.35.0
0.35.1
0.35.2
0.36.0
0.37.0
0.37.1
0.37.2
0.38.0
0.38.1
0.38.2
0.39.0
0.39.1
0.39.2
```

**Comment by roele** [comment]
I am unable to reproduce this. 

```bash
mise ls-remote cargo:zellij
0.0.1
...
0.40.0
```

Have you tried clearing the cache via `mise cache clear`?

**Comment by dParikesit** [comment]
`mise cache clear` indeed solve the problem. It also turns out that a lot of my cargo app need update. Maybe something's wrong with the cache on the cargo backend? Thanks anyway
