### ISSUE TITLE
Add support for extra arguments on cargo backend

### ISSUE THREAD

**Issue by bellini666** [jdx/mise#1952]
When moving my cargo packages to use the new cargo backend I could not migrate `taplo-cli` because I need to pass `--features lsp` to it.

For this example and others, and maybe for other backends as well, would be nice to have a way to pass extra arguments to `cargo install`

**Comment by roele** [comment]
Duplicate of #1635

**Comment by bellini666** [comment]
Oh, thanks for that. Going to close it
