### ISSUE TITLE
`mise ls --json --current` returns an array with a single object

### ISSUE THREAD

**Issue by notpeelz** [jdx/mise#1968]
`mise ls --json --current` returns an array for each tool (even though there can only be one), e.g.:

```json
{
  "node": [
    {
      "version": "18.19.0",
      "requested_version": "18.19.0",
      "install_path": "/home/peelz/.local/share/mise/installs/node/18.19.0",
      "source": {
        "type": "legacy-version-file",
        "path": "/home/peelz/path/to/project/.nvmrc"
      },
      "installed": false,
      "active": false
    }
  ],
  "rust": [
    {
      "version": "stable",
      "requested_version": "stable",
      "install_path": "/home/peelz/.local/share/mise/installs/rust/stable",
      "source": {
        "type": ".mise.toml",
        "path": "/home/peelz/.config/mise/config.toml"
      },
      "installed": true,
      "active": true
    }
  ]
}
```

Wouldn't it make more sense to have a `"tool": {}` mapping instead?

**Comment by notpeelz** [comment]
Oh my bad. I forgot about that :sweat_smile:

**Comment by jdx** [comment]
there can be multiple active versions

**Comment by notpeelz** [comment]
How does it decide which version to run? Sorry I haven't looked too in depth into the docs.

**Comment by notpeelz** [comment]
I'm updating my zsh config to display the versions of the tools in my prompt. Basically, I just want to list the tools and (their versions) that are overridden in the current environment. Sorry about the dumb questions, the terminology is confusing me :sweat_smile:
