### ISSUE TITLE
Error while installing inside Termux (android)

### ISSUE THREAD

**Issue by 80avin** [jdx/mise#1969]
I tried installing inside [Termux](https://termux.dev/en/), the script completes but I'm not able to run `mise`

Getting following error
```
~ $ curl https://mise.run | MISE_DEBUG=1 sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5897  100  5897    0     0   3383      0  0:00:01  0:00:01 --:--:--  3385
mise: installing mise...
> curl -#fLo /data/data/com.termux/files/usr/tmp/tmp.yZp8zhQJPQ/mise-v2024.4.8-linux-arm64.tar.gz https://github.com/jdx/mise/releases/download/v2024.4.8/mise-v2024.4.8-linux-arm64.tar.gz
######################################################################## 100.0%
mise-setup: tarball=/data/data/com.termux/files/usr/tmp/tmp.yZp8zhQJPQ/mise-v2024.4.8-linux-arm64.tar.gz
validating checksum
mise: installed successfully to /data/data/com.termux/files/home/.local/bin/mise
mise: run the following to activate mise in your shell:
echo "eval \"\$(/data/data/com.termux/files/home/.local/bin/mise activate bash)\"" >> ~/.bashrc

mise: this must be run in order to use mise in the terminal
mise: run `mise doctor` to verify this is setup correctly
~ $ ~/.local/bin/mise
bash: /data/data/com.termux/files/home/.local/bin/mise: cannot execute: required file not found
```

If I install using 
```
curl https://mise.jdx.dev/mise-latest-linux-armv7 > ~/.local/bin/mise
```
I get following error on running mise
```
~ $ ~/.local/bin/mise
bash: /data/data/com.termux/files/home/.local/bin/mise: Bad address
```

## System info
```
~ $ uname -a
Linux localhost 4.14.186-27095505 #1 SMP PREEMPT Fri Dec 29 13:19:18 KST 2023 aarch64 Android
```

**Comment by avoidik** [comment]
I was curious why it doesn't work, in my case the reason is

```
executable's TLS segment is underalignment: alignment is 16, needs to be at least 64 for ARM64 Bionic
```

**Comment by mehanoid** [comment]
Same error

```sh
  ~                                                                                                                                                                       1m 57s u0_a446@localhost   18:23:40
❯ curl https://mise.run | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6323  100  6323    0     0  25531      0 --:--:-- --:--:-- --:--:-- 25495
mise: installing mise...
######################################################################## 100.0%
mise: installed successfully to /data/data/com.termux/files/home/.local/bin/mise
mise: run the following to activate mise in your shell:
echo "eval \"\$(/data/data/com.termux/files/home/.local/bin/mise activate zsh)\"" >> "/data/data/com.termux/files/home/.zshrc"

mise: this must be run in order to use mise in the terminal
mise: run `mise doctor` to verify this is setup correctly
  ~                                                                                                                                                                           6s u0_a446@localhost   18:23:48
❯ ls ~/.local/bin
 mise
  ~                                                                                                                                                                               u0_a446@localhost   18:23:52
❯ ~/.local/bin/mise doctor
zsh: no such file or directory: /data/data/com.termux/files/home/.local/bin/mise
  ~                                                                                                                                                                               u0_a446@localhost   18:23:59
❯ bash
~ $ ~/.local/bin/mise doctor
bash: /data/data/com.termux/files/home/.local/bin/mise: cannot execute: required file not found
```

**Comment by 80avin** [comment]
@avoidik Understood. Looks like the issue is still open upstream and will get hopefully fixed one day.

> mise metadata server will be missing android catalog entirely
Don't know since mise is already broken on android, but I guess android will be using `aarch64` architecture mostly. `uname -m` gives same.

**Comment by avoidik** [comment]
Long story short, mise doesn't support Android, because there's no packages specifically created for it.

Every tool provided by mise has a corresponding manifest file with a list of supported operating systems, architectures, links, and so on, and there's no Android as class. You may try to convince mise to detect Android as a Linux, but again -- it wouldn't work due to lack of interoperability between Android and Linux binaries in most of the cases.

Unless package vendors would consider android compiled binaries (read it as never). Just forget about it.

**Comment by onedr0p** [comment]
That's a bummer, I run a ton of rust based CLI apps on Termux, fish, starship, minijinja-cli and more without an issue. Hopefully someday mise can be supported too.

**Comment by 80avin** [comment]
@onedr0p  That works really well.

I know I am commenting on a closed issue, but I want to add that fixing this issue is also a minimal effort.
We should replace the sys-info crate with sysinfo crate. Rationale
* [sys-info](https://crates.io/crates/sys-info) hasn't been updated for years, but [sysinfo](https://crates.io/crates/sysinfo) is regularly updated.
* [sys-info](https://crates.io/crates/sys-info) is used only to [get linux os name](https://github.com/jdx/mise/blob/fd6aa1eccf23f97e82ff166ff8950721c236239b/src/env.rs#L457), that too only to [identify alpine and nixos](https://github.com/jdx/mise/blob/fd6aa1eccf23f97e82ff166ff8950721c236239b/src/config/settings.rs#L68). I guess [sysinfo's name](https://docs.rs/sysinfo/latest/sysinfo/struct.System.html#method.name) is all we need, though I don't have access to alpine/nixos and cannot verify myself. But certainly, there can be many easy ways to detect alpine/nixos.

**Comment by onedr0p** [comment]
```
mise WARN  Error getting latest version for aqua:helmfile/helmfile: error sending request for url (https://api.github.com/repos/helmfile/helmfile/releases): client error (Connect): error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2104: (unable to get local issuer certificate): error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2104:
```

**Comment by avoidik** [comment]
@onedr0p this error does look like a problem with the local CA certificates

**Comment by onedr0p** [comment]
@avoidik I'm not having any issues with other CLI tools like git, curl, wget, etc... in termux


Was anything changed with the past couple months with mise in regards to how it retrieves system certificates, or maybe a 3rd party dep update caused a regression?

I would try to iterate thru releases and see which version the issue started happening but it would take a long time for that discovery.

**Comment by onedr0p** [comment]
Guess my question should be relayed to @jdx then. I know termux support probably isn't a primary concern but it would nice if it did work.

**Comment by vrozaksen** [comment]
@onedr0p nice to see you here :)
I got different error after your's setup:
u0_a687@localhost ~> mise
> error: "/data/data/com.termux/files/home/.local/bin/mise" has unexpected e_type: 2

Sorry for formatting I'm on my mobile rn.

**Comment by avoidik** [comment]
@vrozaksen this is an example of a binary compatibility issue I have mentioned before, depending on what underlying runtime you have (Android or Linux or something else) an Android runtime is only able to run a binary compiled as a shared object file (ET_DYN)

In your case, you were trying to execute a binary compiled as an executable file (ET_EXEC) which Android runtime doesn't support.

Here's a link to Android runtime library where this check happens:
- https://cs.android.com/android/platform/superproject/+/master:bionic/linker/linker_phdr.cpp;l=267

**Comment by Vinfall** [comment]
Hi, I managed to solve it. Fundamentally it's actually Termux's fault. I'll post longer explanation later but here is the TLDR.

1. Install linux-arm64-musl binary of mise (so you don't have the elf issue above), confirmed working on latest version (2025.3.3)
2. Run these commands to symlink CA certificates into the right place (this part is a bit ill-advised, but it works perfectly):

```sh
cd $PREFIX/etc/tls
mkdir certs
ln -s cert.pem certs.pem
ln -s cert.pem certs/ca-certificates.crt
```

3. Add this function to your shell rc (only tested on Bash/Zsh, I don't use fish):
```sh
mise () {
    proot -b "$PREFIX/etc/resolv.conf:/etc/resolv.conf" -b "$PREFIX/etc/tls:/etc/ssl" mise "$@"
}
```

Now mise would just work fine.

```sh
$ mise -V
              _                                        __              
   ____ ___  (_)_______        ___  ____        ____  / /___ _________                                                            
  / __ `__ \/ / ___/ _ \______/ _ \/ __ \______/ __ \/ / __ `/ ___/ _ \                                                           
 / / / / / / (__  )  __/_____/  __/ / / /_____/ /_/ / / /_/ / /__/  __/                                                           
/_/ /_/ /_/_/____/\___/      \___/_/ /_/     / .___/_/\__,_/\___/\___/                                                            
                                            /_/                                                                                   
2025.3.3 linux-arm64 (2025-03-14)
$ mise doctor
# no error
$ mise use -g usage
mise Installed executable into /data/data/com.termux/files/home/.local/share/mise/installs/usage/2.0.5/usage
mise usage@2.0.5 ✓ installed                                                                                                      mise ~/.config/mise/config.toml tools: usage@2.0.5
```

Noted that installing via mise works do not mean other backends would automatically fix themselves, chances (like cargo backend with cargo.binstall=true) are many would still require additional effort to use.

**Comment by Vinfall** [comment]
I wish to keep it short but there are too many issues, I want to go through one by one.

### Variant

> [!TLDR]
> Use linux-arm64-musl

Like I said above, you should use linux-arm64-musl binary as Android use bionic libc instead of de-facto glibc. Musl-libc shares many features like Termux so it has a higher chance to work here.

### DNS

> [!TLDR]
> The suggestion in https://github.com/jdx/mise/issues/1969#issuecomment-2556250067 is still needed.

The suggestion from @80avin in https://github.com/jdx/mise/issues/1969#issuecomment-2559283486 is still valid. It can be avoided on mise side.

I have more detailed explanation on this behavior in https://github.com/cargo-bins/cargo-binstall/issues/1057#issuecomment-2687797240, and I hope you don't mind checking on that instead.

The proot hack is still needed.

If I remove that part, installing via mise still does not work:

```sh
mise () {
    proot -b "$PREFIX/etc/tls:/etc/ssl" mise "$@"
}

$ mise use -g jq
mise ERROR failed to install aqua:jqlang/jq@1.7.1
mise ERROR error sending request for url (https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-arm64)
mise ERROR client error (Connect)
mise ERROR dns error: failed to lookup address information: Try again
mise ERROR failed to lookup address information: Try again
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

<details><summary>Verbose output and rust backtrace</summary>
<p>

```rust
$ RUST_BACKTRACE=full mise --verbose use -g jq
DEBUG ARGS: mise --verbose use -g jq
DEBUG config: ~/.config/mise/config.toml
DEBUG install_some_versions: jq@latest
INFO  jq@1.7.1        install
DEBUG GET https://api.github.com/repos/jqlang/jq/releases/tags/jq-v1.7.1
DEBUG starting new connection: https://api.github.com/
INFO  jq@1.7.1        download jq-linux-arm64
DEBUG GET Downloading https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-arm64 to ~/.local/share/mise/downloads/jq/1.7.1/jq-linux-arm64
DEBUG GET https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-arm64
DEBUG starting new connection: https://github.com/
Error: 
   0: failed to install aqua:jqlang/jq@1.7.1
   1: error sending request for url (https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-arm64)
   2: client error (Connect)
   3: dns error: failed to lookup address information: Try again
   4: failed to lookup address information: Try again

Location:
   src/http.rs:64

Version:
   2025.3.3 linux-arm64 (2025-03-14)

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 2 frames hidden ⋮                               
   3: mise::http::Client::get_async::{{closure}}::{{closure}}::{{closure}}::hb909d8dbb7a640ae
      at <unknown source file>:<unknown line>
   4: mise::http::Client::get_async::{{closure}}::h76f4005227d3f6d0
      at <unknown source file>:<unknown line>
   5: mise::http::Client::download_file::{{closure}}::h1f8631e805dfa9db
      at <unknown source file>:<unknown line>
   6: tokio::runtime::park::CachedParkThread::block_on::h0921498fa31159f5
      at <unknown source file>:<unknown line>
   7: mise::http::Client::download_file::h86114792d4e61fd6
      at <unknown source file>:<unknown line>
   8: <mise::backend::aqua::AquaBackend as mise::backend::Backend>::install_version_::hee11413e9388e236
      at <unknown source file>:<unknown line>
   9: mise::backend::Backend::install_version::h5b1a17f9a14626d0
      at <unknown source file>:<unknown line>
  10: std::sys::backtrace::__rust_begin_short_backtrace::he9bd72fdd24b6cde
      at <unknown source file>:<unknown line>
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}::hc81aca54adbad0ff
      at <unknown source file>:<unknown line>
  12: std::sys::pal::unix::thread::Thread::new::thread_start::haf2a8b7712fcde43
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```

</p>
</details> 


### CA Certificates

> [!TLDR]
> See my comment above.

This one is very tricky, it looks like Termux does not install `ca-certificates` like normal Linux.

On Void Linux, `ca-certificates` gets installed into:
- `/etc/ssl/certs` (and `/etc/ssl/certs.pem` is a symlink to `/etc/ssl/certs/ca-certificates.crt`
- `/usr/share/ca-certificates`
- and GNUstep would install another one into `/usr/lib/GNUstep/Libraries/gnustep-base/Versions/1.30/Resources/GSTLS`

On Termux, after checking [termux-packages](https://github.com/termux/termux-packages/blob/master/packages/ca-certificates/build.sh#L12-L14), it does not get installed into `$PREFIX/etc/ssl` or `$PREFIX/share/ca-certificates`, but `$PREFIX/etc/tls` (why???).

The only *normal* one I found via fzf inside `$PREFIX` is the one provided by GNUstep:

```sh
lib/GNUstep/Libraries/gnustep-base/Versions/1.31/Resources/GSTLS/ca-certificates.crt
```

However, (I guess) `gnustep-base` is not always installed so I choose to make symlinks instead.

```sh
cd $PREFIX/etc/tls
mkdir certs
ln -s cert.pem certs.pem
ln -s cert.pem certs/ca-certificates.crt
```

Note it's the opposite of a regular Linux, here `$PREFIX/tls/certs/ca-certificates.crt` is a symlink to `$PREFIX/etc/tls/cert.pem`. Anyway it just works so I don't bother to do further debugging.

### Solution

In the end we have this:

```sh
mise () {
    proot -b "$PREFIX/etc/resolv.conf:/etc/resolv.conf" -b "$PREFIX/etc/tls:/etc/ssl" mise "$@"
}
```

Side note: from the log I think mise does get the latest version of jq from GitHub API? It just cannot fetch the release, which is a bit weird for me but I don't care now that it works.

**Comment by onedr0p** [comment]
@Vinfall thanks for the solution and excellent write up on the issue, works fine here on `v2025.3.3`!

**Comment by Vinfall** [comment]
Glad it worked for you! I almost decided to start bisecting until I find last working version. Fortunately I got the inspiration from your previous comment and the fix magically works (I thought I'd need to add all those Mozilla certs to make it work).

It's a bit annoying shell completion via `usage` does not work out of box, but at least it removes a huge blocker with working ubi backend.
