### ISSUE TITLE
Never compile python option

### ISSUE THREAD

**Issue by Adirelle** [jdx/mise#1970]
There is a [setting](https://mise.jdx.dev/lang/python.html#python-compile) to disable the installation of precompiled python binaries and to force compilation. However, there is no setting to always use these precompiled binaires.

Would it possible to change this settings to be a 3-value instead of a bool?
 
* `never`: never use python-build, install available precompiled binairies.
* `avoid` (default) : if the requested version is available as a precompiled package, install it, else use python-build (same behavior as `false` currently).
* `always`: always use python-build (same behavior as `true` currently).

**Comment by jdx** [comment]
yes https://github.com/jdx/mise/issues/1684

**Comment by Adirelle** [comment]
I just saw it. My bad.
