### ISSUE TITLE
Feature Request: manage the absence of xz for python builds.

### ISSUE THREAD

**Issue by kenbankspeng** [jdx/mise#1978]
After choosing to build python@3 locally on Apple Silicon M2 using `mise settings set python_compile 1`, the command `mise use --global python@3` gives the following error. `ModuleNotFoundError: No module named '_lzma' when building python...`

This occurs because the python3 build process does not have `xz` as a build dependency as it does for `openssl` and `readline`. 

I don't fully appreciate why Python would not have `xz` as a build dependency, but maybe Mise could install xz first? 

Or if that doesn't make sense, could Mise check for the presence of xz and warn the user suggesting it be installed manually first? 

My workaround is to use Mise to remove the python just built, install xz myself, and then build python3 again.

**Comment by jdx** [comment]
I'm not sure mise should do anything more here. mise certainly shouldn't be installing system dependencies and this is an optional one for python so mise should continue. I'm not sure if I would have a good way to reliably detect if xz is available either.
