### ISSUE TITLE
Python environments activating, but zsh prompt not updated

### ISSUE THREAD

**Issue by max-santiago** [jdx/mise#2027]
Usually, when activating a Python virtual environment (whether manually or with virtual environment management tools such as `direnv` or `autoenv`), the `VIRTUAL_ENV` environment variable is set, and the `PS1` variable will be overridden to display the virtual environment name in the shell.

<img width="363" alt="image" src="https://github.com/jdx/mise/assets/12837448/f39634bd-8f5a-4834-8f5c-9c520bcbd3df">

I noticed that the auto-activation logic from `jdx` will correctly set `VIRTUAL_ENV` and point the `python` command to the correct executable, **but** it won't update the `PS1` variable to show the environment name in the shell prompt, which is what I would expect to happen when activating an environment (whether manually or automatically with tools such as direnv or autoenv).

I think the relevant code snippet from the generic `activate` script is the following:

```
if ([ "$OSTYPE" = "cygwin" ] || [ "$OSTYPE" = "msys" ]) && $(command -v cygpath &> /dev/null) ; then
    VIRTUAL_ENV=$(cygpath -u "$VIRTUAL_ENV")
fi
export VIRTUAL_ENV

_OLD_VIRTUAL_PATH="$PATH"
PATH="$VIRTUAL_ENV/bin:$PATH"
export PATH

if [ "x" != x ] ; then
    VIRTUAL_ENV_PROMPT=""
else
    VIRTUAL_ENV_PROMPT=$(basename "$VIRTUAL_ENV")
fi
export VIRTUAL_ENV_PROMPT

# unset PYTHONHOME if set
if ! [ -z "${PYTHONHOME+_}" ] ; then
    _OLD_VIRTUAL_PYTHONHOME="$PYTHONHOME"
    unset PYTHONHOME
fi

if [ -z "${VIRTUAL_ENV_DISABLE_PROMPT-}" ] ; then
    _OLD_VIRTUAL_PS1="${PS1-}"
    PS1="(${VIRTUAL_ENV_PROMPT}) ${PS1-}"
    export PS1
fi
```

It would be nice to have `mise` update `PS1` and restore it back to normal as it activates and deactivates Python environments whenever I switch directories on the shell.

**Comment by jdx** [comment]
I'm personally not a big fan of tools updating my PS1. I'd be open to this being optional functionality, but for me personally this is something I'd rather have configured in custom PS1 logic in my own rc file or with something like starship.

**Comment by max-santiago** [comment]
Got it! Thanks for the clarification. Ideally, I'd like the PS update logic to run _on activation/deactivation of the environment_ rather than when starting up the shell or on changing directories. I actually had a custom rc file which did this in a single step, and I was able to, e.g. reference the VIRTUAL_ENV variable after it was set within my code when updating PS1. 

It is unclear to me how/where I could add a "hook" that updates PS1 after `mise` activates/deactivates the environment. Apologies in advance if this is a bit basic.

**Comment by swirle13** [comment]
when I have pyenv and pyenv-virtualenv activate my environment, those are done with commands added to my zshrc or zprofile. The commands are

.zprofile:
```
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```

.zshrc:
```
eval "$(pyenv virtualenv-init -)" 
```

Are there similar commands we could use to enable this behavior in our rc and profile files?

**Comment by jdx** [comment]
I don't see why mise needs to be involved here. You're wanting to display the value of VIRTUAL_ENV in your prompt. In zsh that's as easy as this:

```zsh
precmd() {
  PROMPT="${VIRTUAL_ENV} $"
}
```

you may need to add some logic like `basename $VIRTUAL_ENV` and handle cases like when it's not available but this doesn't seem like something relevant to mise, it's about your shell configuration.
