### ISSUE TITLE
pipx backend packages not updating

### ISSUE THREAD

**Issue by bellini666** [jdx/mise#2028]
Have some `"pipx:<some_package>": "latest"` in my config, but when doing `mise upgrade` they are not getting updated

**Comment by russelldavis** [comment]
I have the same issue with `npm` backend packages.

`mise list` shows:
```
npm:tsx                       4.7.1              ~/.config/mise/config.toml latest
```

The latest version on npm is 4.9.3, but when I run `mise upgrade npm:tsx` it says `All tools are up to date`

**Comment by russelldavis** [comment]
Update: If I run `mise uninstall npm:tsx` then `mise install npm:tsx`, it still installs the outdated version. If I force the new version by running `mise install npm:tsx@4.9.3`, it works, but `mise list` shows the version as `4.9.3 (outdated)`.

**Comment by roele** [comment]
Tried to reproduce this without much success yet.

```bash
  ❯ mise i npm:tsx@4.7.1
Reshimming mise latest...
mise npm:tsx@4.7.1  ✓ installed

  ❯ mise use npm:tsx@latest
mise ~/foo/.mise.toml tools: npm:tsx@4.7.1

  ❯ mise ls
Plugin                 Version                 Config Source               Requested
npm:tsx                4.7.1 (outdated)        ~/foo/.mise.toml latest

  ❯ mise upgrade npm:tsx
Reshimming mise latest...
mise npm:tsx@4.9.3  ✓ installed
mise npm:tsx@4.7.1  ✓ removing ~/Library/Caches/mise/npm-tsx/4.7.1

  ❯ mise ls
Plugin                 Version                 Config Source               Requested
npm:tsx                4.9.3                   ~/foo/.mise.toml latest
```

Could this possibly be an issue related to version caching? Have you tried clearing the cache with `mise cache clear`?

**Comment by jdx** [comment]
as far as pipx, it doesn't support listing versions which would be the cause of this

**Comment by jdx** [comment]
mise appears to be calling itself, understand that backends like npm and pipx are still very much experimental features and bugs should be expected
