### ISSUE TITLE
cargo backend issues when trying to update a package

### ISSUE THREAD

**Issue by bellini666** [jdx/mise#2029]
Have some `"cargo:<package_name>": "latest"` in my config. When trying to `mise upgrade` they will fail like this:

`mise Error getting latest version for cargo:<package>: cargo is not installed. Please install it in order to install <package>`

obs.I have `rust: "latest"` in my config 

edit: just noticed it is actually happening even on install... maybe some regression?

**Comment by roele** [comment]
This looks similar to #1999 and #2000 where dependencies are not (yet) on the PATH. I assume you don't have shims on the path either? My guess is that it would work with shims enabled but not yet without.

**Comment by lunks** [comment]
I'm having a similar issue with the recently released version:

```
~ $ eval "$(~/.local/bin/mise activate zsh)"

mise failed to resolve version of cargo:fd-find from ~/.config/mise/config.toml: cargo is not installed. Please install it in order to install fd-find
mise failed to resolve version of cargo:starship from ~/.config/mise/config.toml: cargo is not installed. Please install it in order to install starship
mise failed to resolve version of cargo:eza from ~/.config/mise/config.toml: cargo is not installed. Please install it in order to install eza
~ $ mise --version
2024.5.5 linux-x64 (7e8dab5 2024-05-12)
```
