### ISSUE TITLE
Problems installing with `curl https://mise.run | sh` on an `raspberry pi 3 model b+`.

### ISSUE THREAD

**Issue by dominik-schwabe** [jdx/mise#2035]
**Describe the bug**

Installing mise with `curl https://mise.run | sh` and running it with any command gives the following error:

```sh
mise --version
# bash: /home/pi/.local/bin/mise: cannot execute: required file not found
```

**To Reproduce**

Have a Raspberry Pi 3 Model B+ and install archlinuxarm on it (http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-armv7-latest.tar.gz).

**Expected behavior**

`mise --version` should output its version.

**`mise doctor` output**

Not possible

**Additional context**

```sh
uname -a
# Linux pipi 6.6.28-2-rpi #1 SMP Fri Apr 19 12:18:22 MDT 2024 armv7l GNU/Linux
```

```sh
curl https://mise.run | MISE_DEBUG=true sh
# mise: installing mise...
# > curl -#fLo /tmp/tmp.5hD9ZrH6FQ/mise-v2024.5.2-linux-armv7.tar.gz https://github.com/jdx/mise/releases/download/v2024.5.2/mise-v2024.5.2-linux-armv7.tar.gz
# ######################################################################## 100.0%
# mise-setup: tarball=/tmp/tmp.5hD9ZrH6FQ/mise-v2024.5.2-linux-armv7.tar.gz
# validating checksum
# mise: installed successfully to /home/pi/.local/bin/mise
# mise: run the following to activate mise in your shell:
# echo "eval \"\$(/home/pi/.local/bin/mise activate bash)\"" >> ~/.bashrc
#
# mise: this must be run in order to use mise in the terminal
# mise: run `mise doctor` to verify this is setup correctly
```

```sh
ls -al $HOME/.local/bin/mise
# -rwxr-xr-x 1 pi pi 20443788 May  2 04:07 .local/bin/mise
```

```sh
ldd /bin/ls
#       linux-vdso.so.1 (0xbef84000)
#       libcap.so.2 => /usr/lib/libcap.so.2 (0xb6f40000)
#       libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xb6f10000)
#       libc.so.6 => /usr/lib/libc.so.6 (0xb6d70000)
#       /lib/ld-linux-armhf.so.3 => /usr/lib/ld-linux-armhf.so.3 (0xb6f99000)
```

Output of all latests mise builds:

```sh
/home/pi/mise_installs/mise-v2024.5.2-linux-arm64 --version
# bash: /home/pi/mise_installs/mise-v2024.5.2-linux-arm64: cannot execute binary file: Exec format error
/home/pi/mise_installs/mise-v2024.5.2-linux-arm64-musl --version
# bash: /home/pi/mise_installs/mise-v2024.5.2-linux-arm64-musl: cannot execute binary file: Exec format error
/home/pi/mise_installs/mise-v2024.5.2-linux-armv6 --version
# bash: /home/pi/mise_installs/mise-v2024.5.2-linux-armv6: cannot execute: required file not found
/home/pi/mise_installs/mise-v2024.5.2-linux-armv6-musl --version
# mise 2024.5.2 linux-arm (2576af6 2024-05-02)
/home/pi/mise_installs/mise-v2024.5.2-linux-armv7 --version
# bash: /home/pi/mise_installs/mise-v2024.5.2-linux-armv7: cannot execute: required file not found
/home/pi/mise_installs/mise-v2024.5.2-linux-armv7-musl --version
# mise 2024.5.2 linux-arm (2576af6 2024-05-02)
/home/pi/mise_installs/mise-v2024.5.2-linux-x64 --version
# bash: /home/pi/mise_installs/mise-v2024.5.2-linux-x64: cannot execute binary file: Exec format error
/home/pi/mise_installs/mise-v2024.5.2-linux-x64-musl --version
# bash: /home/pi/mise_installs/mise-v2024.5.2-linux-x64-musl: cannot execute binary file: Exec format error
/home/pi/mise_installs/mise-v2024.5.2-macos-arm64 --version
# bash: /home/pi/mise_installs/mise-v2024.5.2-macos-arm64: cannot execute binary file: Exec format error
/home/pi/mise_installs/mise-v2024.5.2-macos-x64 --version
# bash: /home/pi/mise_installs/mise-v2024.5.2-macos-x64: cannot execute binary file: Exec format error
```

**Comment by seuros** [comment]
Which kernel/distro you have ?  Bookwork throw a Floating point exception

**Comment by dominik-schwabe** [comment]
Archlinuxarm (http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-armv7-latest.tar.gz) with the `core/linux-rpi` kernel (https://github.com/raspberrypi/linux)

**Comment by seuros** [comment]
the mise should be linked to /home/pi/mise_installs/mise-v2024.5.2-linux-armv7-musl

**Comment by roele** [comment]
I assume the [condition](https://github.com/jdx/mise/blob/main/packaging/standalone/install.envsubst#L47) for libc does not match in this case, not setting the `-musl` suffix.

**Comment by dominik-schwabe** [comment]
```sh
getconf GNU_LIBC_VERSION
# glibc 2.35
```
```sh
ldd --version
# ldd (GNU libc) 2.35
# Copyright (C) 2022 Free Software Foundation, Inc.
# This is free software; see the source for copying conditions.  There is NO
# warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# Written by Roland McGrath and Ulrich Drepper.
```

**Comment by jdx** [comment]
everything seems to be saying libc ¯\_(ツ)_/¯

**Comment by dominik-schwabe** [comment]
I updated the system and now glibc is the latest version but this did not fix the issue.

```sh
getconf GNU_LIBC_VERSION
# glibc 2.39
```

```sh
ldd --version
# ldd (GNU libc) 2.39
# Copyright (C) 2024 Free Software Foundation, Inc.
# This is free software; see the source for copying conditions.  There is NO
# warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# Written by Roland McGrath and Ulrich Drepper.
```

I also searched for some rust applications on https://github.com/rust-unofficial/awesome-rust that use a similar installation script and tried to install them.
Maybe this can help you in deciding what to do.

### doesn't have precompiled binaries for armv7:
- https://github.com/bytecodealliance/wasmtime
- https://github.com/datanymizer/datanymizer
- https://github.com/dotenv-linter/dotenv-linter
- https://github.com/casey/just
- https://github.com/metalbear-co/mirrord
- https://github.com/wasmerio/wasmer

### installs wrong binary:
- https://github.com/denoland/deno

### installs working binary:
- https://github.com/ducaale/xh
  Detected target: arm-unknown-linux-gnueabihf
- https://github.com/ajeetdsouza/zoxide
  Detected architecture: armv7-unknown-linux-musleabihf

**Comment by jdx** [comment]
I'm not going to diagnose this.

**Comment by mpalmer** [comment]
Hunting down a similar problem, I suspect the problem is that the Debian `armhf` arch provides a different dynamic linker (`/lib/ld-linux-armhf.so.3` rather than the `/lib/ld-linux.so.3` of `armel`), and so the linker isn't being found during execution.  The problem _could_ be worked around if the mise install script checked for the expected linker when deciding whether to use the static-linked ("musl") binary, rather than just asking "does /bin/ls link against musl?" (so something like `ldd /bin/ls | grep -q '/lib/ld-linux.so.3'` for armv7), although that does require the install script to keep a map of arch/linker for each arch.  A slightly easier option would be to allow users to force using the static binary (via, say, setting `MISE_STATIC_BINARY`).

**Comment by kivikakk** [comment]
I believe @mpalmer's analysis is correct (after running into this myself and noting the dynamic linker the binary wanted wasn't found!). I grabbed `mise-v2025.9.18-linux-armv7-musl` from the [releases page](https://github.com/jdx/mise/releases) and wrote it over the installed `~/.local/bin/mise` and it's running OK now!
