### ISSUE TITLE
mise tasks: machine-readable (json) output

### ISSUE THREAD

**Issue by mkhl** [jdx/mise#2043]
I know tasks are experimental and this is probably coming anyway but just to be sure:
I'd love `mise tasks` to be able to generate machine-readable output, like the json output of `mise env` (so other tools can pick up the listing and invoke tasks through mise)

**Comment by jdx** [comment]
there are probably several commands that would benefit from this, `mise plugins` is another one that came up today. This is really easy to implement if someone wants to learn a bit of rust, see https://github.com/jdx/mise/blob/main/src/cli/outdated.rs for a good example on --json output.
