### ISSUE TITLE
fallback to rust-toolchain.toml when no mise.toml present?

### ISSUE THREAD

**Issue by khimaros** [jdx/mise#2052]
rust-toolchain.toml is the standard way for rust projects to define the recommended rust version. it would be handy if mise could handle these as a default when no explicit mise config is present.

i can see how this could get out of hand trying to support all of the various configs for all languages, but having mise be "polyglot" in terms of toolchain configuration would also make mise more attractive as a tool for users.

alternatively, is there a way i could tap into mise to make this work correctly for specific cases i have?

**Comment by jdx** [comment]
this isn't the right place for this, ask in https://github.com/code-lever/asdf-rust
