### ISSUE TITLE
Command to delete missing plugin from `mise ls` after uninstalling?

### ISSUE THREAD

**Issue by glhrmv** [jdx/mise#2055]
Hi all, simple question:

I had installed the `gleam` plugin and then proceeded to uninstall it with the corresponding `mise` commands. 

When I run `gleam plugins`, I no longer see Gleam there, as expected. But my `gleam ls` output still shows the following:

```
Plugin   Version            Config Source              Requested
gleam    latest (missing)   ~/.mise.toml               latest
```

Is there a command that removes the plugin from this list? I searched the documentation and nothing I tried worked. 

What I ended up doing was manually removing the line for `gleam` in the TOML file referenced in the output above (in this case, `~/.mise.toml`) but this ticket serves to ask if I missed something that would have done that for me? Or is it possibly a bug with the uninstallation of this particular plugin? 

Thank you very much.

**Comment by jdx** [comment]
[this i](https://github.com/jdx/mise/issues/1465)
