### ISSUE TITLE
GITHUB_TOKEN for cargo and ubi backends

### ISSUE THREAD

**Issue by Adirelle** [jdx/mise#2067]
The cargo-binstall and ubi backends delegates the work to the tool binaries, which may have to query the GitHub API to fetch the informations about the latest releases.  Right now, mise itself can use the content of the GITHUB_API_TOKEN variable to access the API but these tools expect the token to be stored in a variable named GITHUB_TOKEN.

The backends could use GITHUB_API_TOKEN to set GITHUB_TOKEN when it is not defined.

**Comment by jdx** [comment]
👍
