### ISSUE TITLE
mise self-update fails with mise ReleaseError: No asset found for target: `macos-arm64`

### ISSUE THREAD

**Issue by bbapplications** [jdx/mise#2086]
**Describe the bug**
running mise doctor

show warning
No warnings found
1 problem found:

1. new mise version 2024.5.9 available, currently on 2024.5.5

running mise self-update fails

mise self-update
Checking target-arch... macos-arm64
Checking current version... v2024.5.5
Checking latest released version... v2024.5.10
New release found! v2024.5.5 --> v2024.5.10
New release is compatible
mise ReleaseError: No asset found for target: `macos-arm64`

**To Reproduce**
on a silicon mac

- run mise doctor
- run mise self-update

**Expected behavior**

**`mise doctor` output**

mise doctor
version: 2024.5.5 macos-arm64 (7e8dab5 2024-05-12)
activated: yes
shims_on_path: no

build_info:
  Target: aarch64-apple-darwin
  Features: DEFAULT, GIT2, NATIVE_TLS, OPENSSL
  Built: Sun, 12 May 2024 00:57:23 +0000
  Rust Version: rustc 1.78.0 (9b00956e5 2024-04-29)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin23.0)

dirs:
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/Library/Caches/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims

config_files:
  ~/.config/mise/config.toml

backends:
  cargo
  go
  npm
  pipx
  ubi

plugins:
  bun      (core)
  dart     https://github.com/PatOConnor43/asdf-dart.git#d14ad3b
  deno     (core)
  flutter  https://github.com/oae/asdf-flutter.git#d7ae5ad
  go       (core)
  java     (core)
  node     (core)
  python   (core)
  ruby     (core)
  usage    https://github.com/jdx/mise-usage.git#fe3888a

toolset:
  node@20.12.1
  python@3.10.14
  java@21.0.2
  ruby@3.2.3
  go@1.21.9
  flutter@3.7.1-stable
  bun@1.1.2
  usage@0.1.18

env_vars:
  MISE_SHELL=zsh

settings:
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cargo_binstall = true
  color = true
  disable_default_shorthands = false
  disable_tools = []
  experimental = false
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  node_compile = false
  not_found_auto_install = true
  paranoid = false
  plugin_autoupdate_last_check_duration = "7d"
  python_compile = false
  python_default_packages_file = "/Users/bb/.default-python-packages"
  python_pyenv_repo = "https://github.com/pyenv/pyenv.git"
  raw = false
  trusted_config_paths = []
  quiet = false
  verbose = false
  yes = false
  ci = false
  debug = false
  trace = false
  log_level = "info"
  python_venv_auto_create = false

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false

No warnings found
1 problem found:

1. new mise version 2024.5.9 available, currently on 2024.5.5

**Additional context**

**Comment by jdx** [comment]
this is what happens if a release is in process
