### ISSUE TITLE
feat: automatic "mr" alias?

### ISSUE THREAD

**Issue by egnor** [jdx/mise#2095]
(Just a thought, feel free to mark will-not-fix)

Maybe `mise hook-not-found` could support `mr` and/or `mrun` as aliases for `mise run`? (I know, we can add the alias ourselves, but this way we could use it in directions we give people.)

OR EVEN support running tasks directly by name? So a task `build` could just be invoked by running `build`, if there were no other `build` command understood by the shell?

**Comment by jdx** [comment]
definitely will not be doing this, mise shouldn't create things so likely to conflict even in a safe way like this. Also, the code in those not found handlers is extremely fragile and past changes have caused a ton of regressions so I am not going to touch that code unless absolutely necessary.

That said, there is a task for cross-shell aliases that at least would help make it easier to setup custom aliases like this: #2034
