### ISSUE TITLE
Support non-hidden configuration paths

### ISSUE THREAD

**Issue by rsyring** [jdx/mise#2096]
For ease of discoverability, I think visible configuration files are better than hidden.  All Mise's configuration paths are prefixed with a dot which causes them to be hidden:

- .mise.toml
- .mise/config.toml
- .config/mise.toml
- .config/mise/config.toml

would be nice if their non-hidden versions were also supported making the list, assuming you want visible to take precedence over non-visible:

- mise.toml
- mise/config.toml
- config/mise.toml
- config/mise/config.toml
- .mise.toml
- .mise/config.toml
- .config/mise.toml
- .config/mise/config.toml

Obviously, env-specific files would also need to be considered.

**Comment by jdx** [comment]
I'm in favor

**Comment by rsyring** [comment]
Thank you!
