### ISSUE TITLE
confirm all plugins

### ISSUE THREAD

**Issue by jdx** [jdx/mise#2099]
it's a bit annoying if you have a bunch of plugins to install since mise keeps prompting. We should have an extra button in addition to "Yes/No" for "All" to stop prompting:

![CleanShot 2024-05-13 at 22 16 44@2x](https://github.com/jdx/mise/assets/216188/0163fd95-9748-4829-9eb4-5f6201cb0b6d)

I think this will require first adding the feature to [demand](https://github.com/jdx/demand).

**Comment by roele** [comment]
@jdx Opened https://github.com/jdx/demand/issues/53 to address this. I guess a new `Dialog` component is the best option to not break backwards compatibility. `Confirm` can be deprecated at some point as `Dialog` will provide more functionality.
