### ISSUE TITLE
Upgrading via Homebrew failed

### ISSUE THREAD

**Issue by kapitoshka438** [jdx/mise#2153]
**Describe the bug**

We upgrade mise to the latest version on CI by running `brew bundle`. mise is listed in Brewfile. 

We started getting this error on CI a couple of days ago:

```
$ brew bundle
Using sonar-scanner
Upgrading mise
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
Upgrading mise has failed!
Homebrew Bundle failed! 1 Brewfile dependency failed to install.
```

**Comment by jdx** [comment]
looks like you're attempting to run brew under rosetta

**Comment by kapitoshka438** [comment]
It has been working like that since the beginning of the year. 
It may be elated to the fact that we are working with GitLab CI, which runner cli doesn't support zsh.
But something changed in mise archs I believe. 
Anyway, we decided to switch to recommended way of installing mise (curl ... | sh). It seems to be working.
