### ISSUE TITLE
mise task run: no color in interleaved output

### ISSUE THREAD

**Issue by mustafa0x** [jdx/mise#2163]
Even with `export CLICOLOR_FORCE=1`. This used to work. related: #1836

Single tasks (ie without interleave) are colored properly.

**Comment by jdx** [comment]
this seems to be working for me now

**Comment by AtomToast** [comment]
Hello I was wondering how this is supposed to be resolved. As soon as I run tasks in parallel with interleaved output, I lose color. When using `--jobs=1` or running running the simple simple tasks individually they work fine.

(running mise 2025.3.0 linux-x64 (2025-03-01))
