### ISSUE TITLE
Support python 3.13 beta (with free threading builds)

### ISSUE THREAD

**Issue by jankatins** [jdx/mise#2169]
[Python 3.13 betas are out](https://docs.python.org/3.13/whatsnew/3.13.html) and can be build with free threading support ("no gil"). It would be nice if mise could install those version.

I tried to follow where the supported versions are, but ended up at http://mise-versions.jdx.dev/python-precompiled. Not sure if https://github.com/indygreg/python-build-standalone/issues/263 is relevant here.

**Comment by thomasaarholt** [comment]
I just successfully installed Python 3.13.0rc2 using `mise use python@3.13.0rc2`, following the [release done here](https://github.com/indygreg/python-build-standalone/releases) two weeks ago!
This was on a Macbook Air M3.
<img width="1698" alt="image" src="https://github.com/user-attachments/assets/0374ff63-f678-4128-beb0-704d07fe577d">
