### ISSUE TITLE
mise reshim always links to ~/.local/bin/mise instead of /usr/local/bin/mise

### ISSUE THREAD

**Issue by radiosilence** [jdx/mise#2171]
1. I delete my shims dir
2. `which mise`:  `/usr/local/bin/mise`
3. `mise reshim`
4. `ls -lha ~/.local/share/mise/shims`
5. Everything points to `~/.local/bin/mise`

I have found a fix is to do `ln -s /usr/local/bin/mise ~/.local/bin/mise` but it's annoying.

**Comment by jdx** [comment]
you're probably running a mise that is in that path

**Comment by radiosilence** [comment]
Yeah I'm using mise from homebrew. Is this the expected behaviour in that situation?

**Comment by radiosilence** [comment]
Weirdly, I've just nuked the shims dir and reshimmed and they're now pointing to `/usr/local/bin/mise` so that's good! Perhaps it is fixed or just was being odd.
