### ISSUE TITLE
Per-project Python default packages _for virtualenv_ (happy to submit a PR)

### ISSUE THREAD

**Issue by egnor** [jdx/mise#2194]
The [default python packages](https://mise.jdx.dev/lang/python.html#default-python-packages) system is handy enough but it's global with all the issues that entails. (It also only updates when any given python runtime is actually installed.)

Since mise can set up a local virtualenv, it makes sense that when doing so it would be able to add some default packages, which would be specified somewhere in settings:
```
[settings]
experimental = true
python_compile = false
python_venv_auto_create = true
python_venv_default_packages = ["pyserial"]
```

In an ideal world it could even install a local package as editable (`pip install -e .`) but maybe that's too esoteric to ask for.

**Comment by rsyring** [comment]
Related: https://github.com/jdx/mise/issues/323

**Comment by jdx** [comment]
see my comment on #323, looking for more information. It's not clear to me why you wouldn't be putting this into pypackage.toml.

**Comment by egnor** [comment]
does seem like this is basically a dup of #323, closing
