### ISSUE TITLE
Default task for a task group

### ISSUE THREAD

**Issue by kapitoshka438** [jdx/mise#2212]
I have a group of tasks defined in `.mise`:
```bash
.mise
└── tasks
    └── gen
        ├── gen
        ├── gen1
        └── gen2
```
We usually run the most common task `mise run gen:gen` and sometimes need to run the others - `mise run gen:gen1`.
It would be great if a task group was able to work with a default task. It could be a task file named `default`:
```bash
.mise
└── tasks
    └── gen
        ├── default
        ├── gen1
        └── gen2
```
Which would allow to run the default task just by `mise run gen`.

**Comment by jdx** [comment]
yeah I suppose you can't name it `gen` because that's the name of the directory. As a stopgap, you could add it to mise.toml but I see why organizing by files that isn't ideal.

**Comment by jdx** [comment]
I'm thinking of `_default` or `_index` so it doesn't conflict and shows up first alphabetically
