### ISSUE TITLE
"mise run" tasks and zsh autocomplete with : delimiters tricks zsh into thinking that grouped tasks are descriptions

### ISSUE THREAD

**Issue by simonpercivall** [jdx/mise#2242]
mise 2024.5.28 if it matters
zsh 5.9

The zsh `_arguments` completion helper, when given an action in double parentheses, accepts completions on the format `word:description`. With mise tasks using `:` for grouping, this breaks completion.

If `_mise` is modified to use single parentheses for `_arguments`, it works (but, of course, breaks all the other completions that _do_ have descriptions).

Example:
```
[tasks."lint:ruff:check"]
...

[tasks."lint:ruff.format"]
...
```

`usage` correctly completes the tasks:
```
> usage complete-word --shell zsh -s "$(mise usage)" -- mise run lin
lint:ruff:check
lint:ruff:format
```

`zsh` autocomplete, however, gives only:
```
> mise run <tab>
lint                -- ruff:check
lint                -- ruff:format
```

and autocompletes only "lint".

**Comment by simonpercivall** [comment]
Something like this seems to work, instead of the `_arguments`:
```zsh
_arguments -C "*: :->args"

case $state in
  (args)
    case $line[1] in
      (run)
        _arguments "*: :($(usage complete-word --shell zsh -s "$spec" -- "${words[@]}" ))"
        ;;
      (*)
        _arguments -C "*: :(($(usage complete-word --shell zsh -s "$spec" -- "${words[@]}" )))"
        ;;
    esac
esac
```

**Comment by powerman** [comment]
At a glance we can just use `/` as a group delimiter instead of `:` in task names as a workaround.

**Comment by powerman** [comment]
Looks like in bash it's broken too: it completes part before `:` but not after `:`.

**Comment by simonpercivall** [comment]
Since I'd guess both use https://github.com/jdx/usage, I guess the fix would be for it not to include the description in `complete-word`.

Using `/` as a workaround is possible, of course, but `mise` recommends it for task grouping: https://mise.jdx.dev/tasks/running-tasks.html#task-grouping

**Comment by AndydeCleyre** [comment]
`mise uninstall` similarly suffers:


https://github.com/user-attachments/assets/15beefa4-2877-463b-ae28-a790a8d74499

**Comment by kj** [comment]
> Looks like in bash it's broken too: it completes part before `:` but not after `:`.

This is my main issue with tasks now (so many quirks have already been dealt with recently). Bash doesn't like `:` in tab completion:

https://stackoverflow.com/a/25481191

Using `/` instead of `:` works fine for TOML tasks, including with wildcards, but file tasks are still named with the `:` delimiter, and I use file tasks quite often.

**Comment by jdx** [comment]
this probably need some sort of escape https://github.com/jdx/usage/blob/da3e539a7618a226d848f6a5326c6ba938b84944/cli/src/cli/complete_word.rs#L48

**Comment by jdx** [comment]
I fixed the bash thing, wasn't easy, but @scop's fantastic [bash-completions](https://github.com/scop/bash-completion) project was a massive help

**Comment by kj** [comment]
@jdx I just tried this with Mise 2024.12.8 and Usage 1.5.2 and now I'm not getting any completions at all (even for subcommands). I also tested in a fresh Docker container and got the same result. Are the Bash completions working for you, and am I missing something? Also, is there a reason that `mise completion bash` seems to include the entire bash-completion script and not just the `_mise` completion function?

**Comment by hverlin** [comment]
Also getting an error with`zsh` on the latest version (and `usage` v1.3.5)
```sh
❯ mise
  × Invalid usage config
  [Failed to read contents for label `unsupported complete key descriptions` (offset: 101798, length: 17): OutOfBounds]
```

**Comment by davidolrik** [comment]
> Also getting an error with`zsh` on the latest version (and `usage` v1.3.5)

Have you tried `usage` 1.5.2? (`mise` didn't show it as outdated for me, but a manual `mise up usage` upgraded it to latest).

On `zsh` with `mise` 2024.12.8 and `usage` 1.5.2 - I can now use `:` as delimiter

**Comment by hverlin** [comment]
Ah right, it works with 1.5.2! Thanks! (Thought I was on the latest after using `mise up` 🤦)

**Comment by jdx** [comment]
> @jdx I just tried this with Mise 2024.12.8 and Usage 1.5.2 and now I'm not getting any completions at all (even for subcommands). I also tested in a fresh Docker container and got the same result. Are the Bash completions working for you, and am I missing something? Also, is there a reason that mise completion bash seems to include the entire /usr/share/bash-completion/bash_completion script and not just the _mise completion function?

yeah I can repro—this was working but obv something broke. I'm including bash_completion because I can't really know if the user installed it or not. I'm not sure if that's a good idea or I should just expect bash users to have it already installed.

**Comment by kj** [comment]
Yeah to be honest I don't know, although all of the scripts I do have in `~/.local/share/bash-completion/completions` leave it out, including:

```sh
deno completions bash
himalaya completions bash
pueue completions bash
```

**Comment by jdx** [comment]
Given the hacks I need to do in order to make bash emulate a modern shell (despite seeming to work well enough) I certainly wouldn't use it.

**Comment by davidolrik** [comment]
> I'm not sure if that's a good idea or I should just expect bash users to have it already installed.

Users should bring their own stuff, to avoid conflicts.

**Comment by jdx** [comment]
I agree, although conflicts are going to be inevitable since this is a global library. I'll put this behind a flag. Some users are going to struggle with this but at least I won't be mucking with people's setups.
