### ISSUE TITLE
Go backend: Infinite loop installing non-GitHub-hosted Go package

### ISSUE THREAD

**Issue by bhollis** [jdx/mise#2254]
I'm having trouble installing the [protoc-gen-connect-go](https://github.com/connectrpc/connect-go) Go package, which uses a package path that's not on github.com:

On my mac:
```
$ mise use --pin go:connectrpc.com/connect/cmd/protoc-gen-connect-go
go: unrecognized import path "connectrpc.com/connect/cmd/protoc-gen-connect-go": reading https://connectrpc.com/connect/cmd/protoc-gen-connect-go?go-get=1: 404 Not Found
go: unrecognized import path "connectrpc.com/connect/cmd": reading https://connectrpc.com/connect/cmd?go-get=1: 404 Not Found
mise go:connectrpc.com/connect/cmd/protoc-gen-connect-go@1.16.2 ✓ installed                                                                                                                                                                 mise ~/Documents/project/.mise.toml tools: go:connectrpc.com/connect/cmd/protoc-gen-connect-go@1.16.2
```

On my CI machine:

* mise runs `go list -m -versions -json connectrpc.com/connect/cmd/protoc-gen-connect-go` over and over until the machine runs out of memory (from https://github.com/jdx/mise/blob/main/src/backend/go.rs#L40).
* Running that command myself results in:

```
$ go list -m -versions -json connectrpc.com/connect/cmd/protoc-gen-connect-go
go: unrecognized import path "connectrpc.com/connect/cmd/protoc-gen-connect-go": reading https://connectrpc.com/connect/cmd/protoc-gen-connect-go?go-get=1: 404 Not Found
```

My Go version is `1.22.3`, also managed through `mise`. I would expect that either I wouldn't be able to install this in the first place, or that once installed, other machines would also be able to install it via `mise install`.

**Comment by bhollis** [comment]
Note that just running `go install connectrpc.com/connect/cmd/protoc-gen-connect-go` works with no message and places the `protoc-gen-connect-go` binary in `$GOBIN`.

**Comment by bhollis** [comment]
I'm not convinced this is caused by the loop at https://github.com/jdx/mise/blob/main/src/backend/go.rs#L40 - I'm seeing machines dying with hundreds of `npm view` commands, hundreds of `go list` commands, etc.

**Comment by jdx** [comment]
infinite loops are generally caused by shims calling themselves. Experimental backends are a work in progress so I'm still working through some of these problems.

**Comment by bhollis** [comment]
That makes sense. Would it work to set an environment variable whenever mise executes other commands that would disable some of the version resolution machinery, to avoid this infinite loop behavior?

**Comment by jdx** [comment]
maybe, but it's harder than it sounds. It's normal for shims to execute other shims.
