### ISSUE TITLE
Some responses from `mise-versions.jdx.dev` are outdated

### ISSUE THREAD

**Issue by shirayu** [jdx/mise#2265]
**Describe the bug**
The latest version of [typos](https://github.com/crate-ci/typos/releases) is ``1.22.3``.
However the latest version in ``http://mise-versions.jdx.dev/typos`` is ``1.21.0``.

**To Reproduce**

```console
$  mise list-all typos | sort -V | tail -n1
1.21.0

$ mise cache clear
$ # OR rm ~/.cache/mise/typos/remote_versions-*.msgpack.z

$  MISE_USE_VERSIONS_HOST=false mise list-all typos | sort -V | tail -n1
1.22.3
```

**Expected behavior**
Please update the list.
Other versions seems to be also outdated (eg. ``pnpm``)

**Additional context**

We can run ``mise install typos@1.22.3`` but it is considered outdated by mise.
This may need to be fixed.
 
```console
$  mise list
Plugin  Version            Config Source              Requested
typos   1.21.0                                                 
typos   1.22.3 (outdated)  ~/.config/mise/config.toml latest  
```

This issue may be related to #2245.

**Comment by kjjaeger** [comment]
I am also seeing this for at least two other tools: bun, gradle, and quarkus
bun 1.1.11 was released over a week ago, but https://mise-versions.jdx.dev/bun returns 1.1.10 as the last version
gradle 8.8 was released over a week ago, but https://mise-versions.jdx.dev/gradle returns 8.8-rc-2 as the last version
quarkus 3.11.1 was released 3 days ago, but https://mise-versions.jdx.dev/quarkus returns 3.11.0 as the last version
This seems to be a problem with updates on the mise-versions.jdx.dev web server and not the mise tool itself
