### ISSUE TITLE
Cannot use installed version of Go from Mise in VS Code

### ISSUE THREAD

**Issue by assembly-winston** [jdx/mise#2270]
It gives me the below error message:

`Failed to run '/opt/homebrew/Cellar/mise/2024.6.2/bin/mise env. The config change may not be applied correctly.`

```
2024-06-08 23:39:55.745 [info] Failed to run '/opt/homebrew/Cellar/mise/2024.6.2/bin/mise env' (cwd: /Users/winston/Developer/assembly/search-server): Error: Command failed: /opt/homebrew/Cellar/mise/2024.6.2/bin/mise env -json GOPATH GOROOT GOPROXY GOBIN GOMODCACHE
error: unexpected argument '-j' found
```

**Comment by roele** [comment]
VS Code should be looking for the `go` binary and not `mise`. Correctly configured, VS Code should show something like "go.goroot setting (/Users/<USER>/.local/share/mise/installs/go/latest) will be applied and set the GOROOT environment variable." 

So you should either have `go` installed and available globally or for your project. Additionally to get binaries working reliably in IDEs you might need to enable shims (`$HOME/.local/share/mise/shims`) by adding them to your PATH.

Please attach the output of `mise doctor` for a more detailed answer regarding your current setup.

**Comment by assembly-winston** [comment]
```
❯ mise doctor
version: 2024.6.2 macos-arm64 (87957bc 2024-06-07)
activated: yes
shims_on_path: no

build_info:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Fri, 7 Jun 2024 02:14:15 +0000
  Rust Version: rustc 1.78.0 (9b00956e5 2024-04-29)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin23.0)

dirs:
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/Library/Caches/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims

config_files:
  ~/.tool-versions
  ~/.config/mise/config.toml

backends:
  cargo
  core
  go
  npm
  pipx
  spm
  ubi

plugins:
  bun     (core)
  deno    (core)
  erlang  (core)
  go      (core)
  java    (core)
  node    (core)
  python  (core)
  ruby    (core)

toolset:
  bun@1.1.10            (missing)
  zig@0.13.0            (missing)
  go@1.22.4
  rust@latest           (missing)
  ruby@3.2.2            (missing)
  node@21.6.1           (missing)
  java@temurin-22.0.1+8  (missing)

env_vars:
  MISE_SHELL=zsh

settings:
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cargo_binstall = true
  color = true
  disable_default_shorthands = false
  disable_tools = []
  experimental = false
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  http_timeout = 30
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  node_compile = false
  not_found_auto_install = true
  paranoid = false
  plugin_autoupdate_last_check_duration = "7d"
  python_default_packages_file = "/Users/winston/.default-python-packages"
  python_pyenv_repo = "https://github.com/pyenv/pyenv.git"
  raw = false
  trusted_config_paths = []
  quiet = false
  verbose = false
  yes = false
  ci = false
  debug = false
  trace = false
  log_level = "info"
  python_venv_auto_create = false

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false

No warnings found
No problems found
```

**Comment by assembly-winston** [comment]
The `failed to run opt/homebrew` thing was something VS Code pulled on its own, not something i pointed it to. Not sure why that happens.

**Comment by vrslev** [comment]
Hey there!

I fixed discovery of binaries that mise provides with using `mise hook-env`: https://github.com/vrslev/dotfiles/blob/55f02dda0b357ec71edf3b11c49a5e4ec3e60f62/config/fish/conf.d/0-login.fish#L26

**Comment by vrslev** [comment]
The approach recommended in the docs didn’t work. @jdk maybe, we should update the docs?

**Comment by roele** [comment]
@vrslev  I use Go in VS Code via mise without any issues but my setup might differ a bit. 

1. I activate mise myself and have the shims on my PATH
```shell
set -Ux MISE_FISH_AUTO_ACTIVATE 0

if type -q mise
    fish_add_path -m $HOME/.local/share/mise/shims
    mise activate --quiet fish | source
    set -x MISE_USE_TOML 1
else
    echo 'mise not found, see https://mise.jdx.dev for installation instructions'
    return 1
end
```
2. I set `go.gopath` and `go.goroot` in VS Code (Profile) Settings
```json
{

"go.gopath": "~/.local/share/mise/installs/go/latest/pgk",
"go.goroot": "~/.local/share/mise/installs/go/latest",

}
```

**Comment by vrslev** [comment]
Yes, I was trying to solve a different problem. 

With `mise activate --shims` [recommended](https://mise.jdx.dev/ide-integration.html) by the documentation, VS Code failed to detect binaries provided by mise. It works if I add `mise hook-env` instead, thus I suggested updating it.

**Comment by nixberg** [comment]
https://code.visualstudio.com/docs/editor/command-line#_how-do-i-detect-when-a-shell-was-launched-by-vs-code

>When VS Code starts up, it may launch a shell in order to source the "shell environment" to help set up tools. This will launch an **interactive login** shell and fetch its environment.

I’ve had success with

```fish
# ~/.config/fish/config.fish
if test "$VSCODE_RESOLVING_ENVIRONMENT" = 1
    mise activate fish --shims | source
else if status is-interactive
    mise activate fish | source
else
    mise activate fish --shims | source
end
```

Probably similar with other shells and IDEs.

**Comment by tsukimizake** [comment]
We call mise from direnv (see https://mise.jdx.dev/direnv.html), and load path to vscode by https://codeberg.org/mkhl/vscode-direnv . It's working very well.

**Comment by hverlin** [comment]
You can try  [intellij-mise](https://plugins.jetbrains.com/plugin/24904-mise) or [vscode-mise](https://marketplace.visualstudio.com/items?itemName=hverlin.mise-vscode). These extensions support configuring `go` automatically (even without having to activate mise or shims)
