### ISSUE TITLE
mise.run should install musl variant whenever this is available

### ISSUE THREAD

**Issue by autarch** [jdx/mise#2276]
Right now it looks like it will pick the musl variant if the system uses it, but it doesn't check whether the installed libc is recent enough. This leads to situations where you can install mise but it won't run because libc is too old.

I think the best solution to this is just to always use the musl version by default.

**Comment by jdx** [comment]
musl variant of what? I don't know of any logic that prefers one to the other

**Comment by autarch** [comment]
Wow, what a terribly bug report. Who wrote this? Oh, I did :cry: 

I think I was saying that the script https://mise.run/ should prefer the musl variant on Linux systems. Otherwise, it can end up installing a `mise` binary that requires a newer glibc than is available on a given system. Preferring the musl variant eliminates this issue.

**Comment by jdx** [comment]
Oh no you put that in the title but I suppose I missed that when I replied
