### ISSUE TITLE
Run a task when entering a directory

### ISSUE THREAD

**Issue by rmgpinto** [jdx/mise#2282]
I've checked the docs and I'm not 100% sure if this use-case is covered:

I want to automatically run a task (ie: `tmuxinator start`) when I enter a directory that has a `.mise.toml` file. It's useful to create/restore a tmux session with the configured layout everytime I switch to a project directory.
I currently use `direnv` to achieve this and wanted to just rely on `mise`.

**Comment by youcandanch** [comment]
Was just thinking about this today; in my use case, I'd love to be able to install a base set of dependencies into a Python .venv, basically stuff that devs would need to work with the repo itself (thinking things like task runner libs, parsing libs, etc.).

**Comment by youcandanch** [comment]
@jdx any thoughts around this one? I'm happy to pick it up as a first contribution, but wanted to spot-check whether or not you'd accept it as functionality before I start crackin' at it.

**Comment by jdx** [comment]
I'm open to it, but I'm not sure how easy it would be. I don't think we have a mechanism to know when a directory is entered right now.

**Comment by youcandanch** [comment]
Cool. If nothing else, I'm interested in contributing, and it seems like a good -- albeit potentially thorny -- way to get my hands dirty and start feeling out how this all works. If I make any progress on it I'll give ya a shout!
