### ISSUE TITLE
[feat] Parse package.json to get `engines.node` version

### ISSUE THREAD

**Issue by g4rcez** [jdx/mise#2284]
# Context
Some NodeJS/Javascript projects have the attribute `engines` in package.json. That enforces the version of NodeJS in the project. Ref: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines

Can mise parse the package.json files to grab the version from `engines.node`?

# Possible solutions

Accept a hook before setting the version of NodeJS.

```toml
[node]
preload = "~/.bin/node-pre-hook"
```

File: ~/.bin/node-pre-hook
```shell
#!/bin/bash
jq 'engines.node' package.json
```

With this solution, we can enable custom hooks to accept any custom methods to accept configuration

# Motivation

I was using [volta](https://volta.sh/) and all my projects use `volta.node` at package.json. This motivates me to configure volta projects to work with mise

I'm trying to do this just using zsh prehooks and I will share at this issue if I can get it.

**Comment by g4rcez** [comment]
I suggested to implement prehooks to parse version from a output of script, but for specific node stuff, I did this PR #2288

**Comment by jdx** [comment]
I feel strongly this is not a good idea. That field denotes compatibility, it should not be used to determine the ultimate version of node.
