### ISSUE TITLE
clear env set in _.source when cd out mise.toml dir

### ISSUE THREAD

**Issue by i18nsite** [jdx/mise#2299]
I think mise should monitor the environment variables added, deleted, and modified by the _.source, and restore them when exiting the directory.

I think the implementation is very simple.  directly save all the environment variables before modification as a hash dictionary. When exiting the directory, delete the newly added environment variables and restore the changed and deleted environment variables.

**Comment by jdx** [comment]
I don't understand, that's literally what `_.source` does
