### ISSUE TITLE
`mise use|install` tool options

### ISSUE THREAD

**Issue by jdx** [jdx/mise#2309]
while not heavily used, mise does support "tool opts", e.g.:

```
[tools]
# send arbitrary options to the plugin, passed as:
# MISE_TOOL_OPTS__FOO= bar
mytool = { version = '3.10', foo = 'bar' }
```

In general, I prefer using settings instead of this because usually these are things that are specific to the current system or user preferences and not the tool itself, however it does have some potential use-cases. This traditionally has not been documented (though I'm going to fix that today). It's also not supported by asdf so it would be mise-only functionality in asdf plugins.

The other barrier for this has been the lack of a CLI interface—it required manually modifying mise.toml. Adding support for this in `mise use` I think could be done, however because `mise use` accepts multiple tools we would need to find a way to make that work. I have not done this before but I think clap might support a way to do something like this:

```
mise use --opt1=a tool1 --opt2=b tool2
```

where in this case, "opt1" would be set only for tool1 and "opt2" would only be set for tool2 of course.

**Comment by powerman** [comment]
How to use MISE_TOOL_OPTS__FOO with ubi backend?

```
$ MISE_TOOL_OPTS__EXE=jv mise i -v ubi:santhosh-tekuri/jsonschema@6.0.0
...
DEBUG extracting binary from tarball at /tmp/.tmpoymueY/jv-v6.0.0-linux-amd64.tar.gz
DEBUG found tarball entry with path LICENSE
DEBUG found tarball entry with path jv
DEBUG could not find any entries named jsonschema
DEBUG Failed to install with ubi version 'v6.0.0': could not find any files named jsonschema in the downloaded tarball, trying with 'ubi:santhosh-tekuri/jsonschema@6.0.0'
DEBUG Parsed --project santhosh-tekuri/jsonschema = santhosh-tekuri / jsonschema
DEBUG exe name = jsonschema
DEBUG install path = /home/powerman/.local/share/mise/installs/ubi-santhosh-tekuri-jsonschema/6.0.0/bin/jsonschema
DEBUG adding GitHub token to GitHub requests
DEBUG starting new connection: https://api.github.com/
Error: 
   0: Failed to install ubi:santhosh-tekuri/jsonschema@6.0.0
   1: Failed to install with ubi 'ubi:santhosh-tekuri/jsonschema@6.0.0': could not find any files named jsonschema in the downloaded tarball

Location:
   src/backend/ubi.rs:123

Version:
   2024.11.2 linux-x64 (448e205 2024-11-06)
```
