### ISSUE TITLE
All URLs should be https

### ISSUE THREAD

**Issue by StingRayZA** [jdx/mise#2311]
There's a number of URL calls that aren't https. In some cases the web server will redirect that call to an https version, but in some cases a 'pure' http response will be served. 

These calls should all be upgraded to https.

**Comment by StingRayZA** [comment]
fix incoming (PR TBC)

**Comment by StingRayZA** [comment]
Hey @jdx 

Any reason why this is undesired?

**Comment by jdx** [comment]
https://github.com/jdx/mise/pull/2266
