### ISSUE TITLE
[FEATURE REQEST]  failed to open git repository at

### ISSUE THREAD

**Issue by cocoonkid** [jdx/mise#2324]
`failed to open git repository at "/opt/.mise/plugins/direnv": repository path '/opt/.mise/plugins/direnv/' is not owned by current user; class=Config (7); code=Owner (-36)`

But in my case this is intentional:

I have a shared /etc/mise/config.toml

and shared data /opt/mise/
On first "mise list" the messages appears and then it's okay. 
![image](https://github.com/jdx/mise/assets/43231640/3e0696f3-8fb5-4910-bb79-f5091a541ac7)

How can I silence it though?

**Comment by jdx** [comment]
I believe this fixed this issue:

https://github.com/jdx/mise/blob/8535827bd055c08a86e574fcec67efff842b2fa9/src/git.rs#L25
