### ISSUE TITLE
`mise i pnpm` fails

### ISSUE THREAD

**Issue by mustafa0x** [jdx/mise#2328]
```bash
$> mise p update pnpm
mise plugin:pnpm ✓ https://github.com/jonathanmorley/asdf-pnpm.git#305baff

$> mise install pnpm@9  # pnpm@latest doesn't work either
gzip: (stdin): trailing garbage ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now
mise ~/.local/share/mise/plugins/pnpm/bin/install failed
Downloading pnpm v9.4.0 from https://registry.npmjs.org/pnpm/-/pnpm-9.4.0.tgz
gzip: (stdin): trailing garbage ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Error: 
   0: ~/.local/share/mise/plugins/pnpm/bin/install exited with non-zero status: exit code 2

Location:
   src/plugins/script_manager.rs:178

Version:
   2024.6.6 macos-arm64 (409d6e4 2024-06-20)

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

---

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**`mise doctor` output**

```text
REPLACE WITH OUTPUT OF `mise doctor`
```

**Additional context**
Add any other context about the problem here. Consider running mise with `--debug` or `--trace` for extra debug info.

**Comment by kjkent** [comment]
@mustafa0x I can't reproduce your error -- can you edit your issue with the output of `mise doctor`? I followed your steps and pnpm installs fine. There has been commits to the plugin repo since your issue so perhaps an update and a retry might work?

As an aside, I think there's perhaps some crossover between the 'tools' and 'plugins' in mise, as after running `mise install pnpm`, pnpm does not list under `mise plugins ls`, and is instead listed under the main tools in `mise ls`. But it's there and it works! Huge fan of mise.

**Comment by mustafa0x** [comment]
Thanks. Not sure what's off with my machine. I reinstalled the plugin several times. :(

**Comment by amirasyraf** [comment]
@mustafa0x You closed the issue, did you resolve it? I'm facing the same issue

**Comment by egnor** [comment]
I think you wanted `mise use`, not `mise install`?

**Comment by mustafa0x** [comment]
I solved this by changing `~/.local/share/mise/plugins/pnpm/bin/install` to use wget instead of curl.

```diff
 echo "Downloading pnpm v${ASDF_INSTALL_VERSION} from ${TARBALL_URL}"
-curl --silent --fail --show-error --location "${TARBALL_URL}" |
+wget "${TARBALL_URL}" -O - |
   tar xzf - --strip-components=1 --no-same-owner -C "${ASDF_INSTALL_PATH}"
```

It's not clear why my curl is corrupting the tar file.

```
$> curl --version
curl 8.7.1 (x86_64-apple-darwin24.0) libcurl/8.7.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.63.0
Release-Date: 2024-03-27
```
