### ISSUE TITLE
Configure jobs per task

### ISSUE THREAD

**Issue by kj** [jdx/mise#2331]
I would like to be able to set `jobs=` on each task rather than just globally or via the command line. For some tasks I need the dependencies to run sequentially, but I don't want to lose parallel execution for every task.

```
[tasks.example]
jobs = 1
depends = [...]
```

**Comment by jdx** [comment]
if I'm understanding this request correctly it sounds super hard. It sounds like the behavior you're looking for would be that dependencies underneath that one would run sequentially but if run alongside other tasks those would run in parallel.

I think the better way to do this would just be to run the tasks manually:

```toml
[tasks.example]
run = ['mise run a', 'mise run b', 'mise run c']
```
