### ISSUE TITLE
Asdf plugin for elixir-ls not working

### ISSUE THREAD

**Issue by chargio** [jdx/mise#2332]
**Describe the bug**
Trying to install elixir-ls does not work

**To Reproduce**
mise install elixir-ls (after installing elixir and erlang)

**Expected behavior**
The installation works

**`mise doctor` output**

```text
version: 2024.6.6 macos-arm64 (2024-06-20)
activated: yes
shims_on_path: no

build_info:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS
  Built: Thu, 20 Jun 2024 17:07:53 +0000
  Rust Version: rustc 1.79.0 (129f3b996 2024-06-10) (Homebrew)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin23.0)

dirs:
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/Library/Caches/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims

config_files:
  ~/.config/mise/config.toml

backends:
  cargo
  core
  go
  npm
  pipx
  spm
  ubi

plugins:
  bun        (core)
  deno       (core)
  elixir     https://github.com/mise-plugins/mise-elixir.git#7b06439
  elixir-ls  https://github.com/juantascon/asdf-elixir-ls#faf921f
  erlang     https://github.com/asdf-vm/asdf-erlang.git#cf6ac67
  go         (core)
  java       (core)
  node       (core)
  python     (core)
  ruby       (core)
  rust       https://github.com/code-lever/asdf-rust.git#95acf4f

toolset:
  erlang@27.0
  elixir@1.17.1-otp-27
  rust@1.79.0

env_vars:
  MISE_SHELL=zsh

settings:
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cargo_binstall = true
  color = true
  disable_default_shorthands = false
  disable_tools = []
  experimental = false
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  http_timeout = 30
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  node_compile = false
  not_found_auto_install = true
  paranoid = false
  plugin_autoupdate_last_check_duration = "7d"
  python_default_packages_file = "/Users/socon/.default-python-packages"
  python_pyenv_repo = "https://github.com/pyenv/pyenv.git"
  raw = false
  trusted_config_paths = []
  quiet = false
  verbose = false
  yes = false
  ci = false
  debug = false
  trace = false
  log_level = "info"
  python_venv_auto_create = false

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false

1 warning found:

1. plugin erlang overrides a core plugin

No problems found
```

**Additional context**
Downloading from https://github.com/elixir-lsp/elixir-ls/releases/download/v0.22.0/elixir-ls-v0.22.0.zip
Archive:  /var/folders/5c/0y04dzc91n78r7qvt7208clw0000gp/T/tmp.5BTFheT4f8/elixir-ls-v0.22.0.zip
  inflating: quiet_install.exs
  inflating: language_server.bat
  inflating: installer.exs
  inflating: exec.zsh
  inflating: launch.sh
  inflating: exec.bash
 extracting: VERSION
  inflating: debug_adapter.sh
  inflating: debug_adapter.bat
  inflating: language_server.sh
  inflating: launch.fish
  inflating: launch.exs
cp: bin/elixir-ls-debugger: No such file or directory
Error:
   0: ~/.local/share/mise/plugins/elixir-ls/bin/install exited with non-zero status: exit code 1

Location:
   src/plugins/script_manager.rs:178

Version:
   2024.6.6 macos-arm64 (2024-06-20)

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by tyoc213** [comment]
Is there a way to solve this? for the moment I copied it by hand

<img width="758" alt="imagen" src="https://github.com/user-attachments/assets/58126c2b-5e5b-4d37-9175-8b186d601acd">

like this

<img width="253" alt="imagen" src="https://github.com/user-attachments/assets/7357a69b-872f-4031-aa61-dc522d272d6a">
