### ISSUE TITLE
Support alternative comment syntax for script task comments

### ISSUE THREAD

**Issue by kj** [jdx/mise#2333]
**Describe the bug**

Languages which do not use `#` as comment character cannot use comments like `# mise description=''` in a script task.

**To Reproduce**

Create a script task `.mise/scripts/foo`:

```
#!/usr/bin/env node

// mise description='Foo'

console.log('Foo');
```

**Expected behavior**
The description should appear in `mise tasks [ls]`, but it does not. If you change the comment character to `#`, the description appears, but of course you then get a syntax error when you run the task.

**`mise doctor` output**

```text
version: 2024.6.6 linux-x64 (2024-06-21)
...
```

**Comment by powerman** [comment]
Any chance this can be worked around using multiline comments (in languages which have it, of course)?

```js
#!/usr/bin/env node
/*
# mise description='Foo'
*/

console.log('Foo');
```

**Comment by jdx** [comment]
This was added for #USAGE, it wouldn't be hard to get it to work for mise too

**Comment by jdx** [comment]
it seems this already works, I added a test for it though

**Comment by kj** [comment]
Just confirming it's working for me now too. Thanks!
