### ISSUE TITLE
Introduce jetbrains mise plugin

### ISSUE THREAD

**Issue by 134130** [jdx/mise#2351]
### Description
- Hello, and thank you for maintaining this project.
- `mise` allows for managing environment variables and tool versions per project. However, JetBrains IDEA currently does not support loading environment variables from `mise` configuration files, causing a separation in the environment variable lists.
- Therefore, I have developed a new JetBrains plugin for `mise` that loads environment variables into the run configuration.
- Here is the plugin. thanks!
  - https://plugins.jetbrains.com/plugin/24904-mise/

+ Add
- Support for mise tools integrations for JDK and Go SDK

**Comment by jdx** [comment]
Might be worth adding to the IDE section of the docs

**Comment by hverlin** [comment]
Adding it in this MR: https://github.com/jdx/mise/pull/3765
