### ISSUE TITLE
Three suggestions for docs

### ISSUE THREAD

**Issue by hexWars** [jdx/mise#2352]
Three suggestions:

- Add a use case for non-interactive shell usage [here](https://mise.jdx.dev/faq.html)
- Or add a GitLab CI use case [here](https://mise.jdx.dev/continuous-integration.html)
- Or add some descriptions [here](https://mise.jdx.dev/getting-started.html#_3-adding-tools-to-mise)

When using mise, I had some questions about how to use mise in a non-interactive environment. I think this usage could be made more prominent, or perhaps there are better ways to address this. What do you think?

**Comment by hexWars** [comment]
Or add some descriptions [here](https://mise.jdx.dev/getting-started.html#_3-adding-tools-to-mise)

**Comment by jdx** [comment]
I think this has improved since this was written
