### ISSUE TITLE
Missing a way to ignore .tool-versions

### ISSUE THREAD

**Issue by DmitrySerovWise** [jdx/mise#2360]
I'm currently integrating mise into a Bitrise workflow.
Bitrise's stack on this workflow is using asdf for managing the environment (to install Go, Node and Ruby), meaning that there's a `~/.tool-versions` file always available.

I'm not using any of the dependencies declared with asdf in this file – it's just the way Bitrise preinstalls some tools in the stack. But this means that whenever I run `mise install`, it not only installs my dependencies declared in `.mise.toml`, but also installs those of the Bitrise stack (which I don't need), which takes quite a lot of time. Not to mention they are already installed with asdf in case I actually do need them.

It would be great if there was a way to tell mise not to consider `.tool-versions` at all. This will help in situations like these when this file cannot be removed. Or maybe there is already a way to do this with an existing config? I didn't manage to find one in the docs.

**Comment by roele** [comment]
Have you tried setting [MISE_DEFAULT_TOOL_VERSIONS_FILENAME](https://mise.jdx.dev/configuration.html#mise-default-tool-versions-filename) to something else?

**Comment by jdx** [comment]
I could be open to something that excluded particular filenames or something to that effect

**Comment by halostatue** [comment]
What about a setting in `.mise.toml` that indicates that fallback tool version files should not be used (`ignore_fallback_tool_config = true`)? (That would mean that environment-specific mise config files could be loaded as expected, but `.tool-versions` and language version files would be ignored.

**Comment by jdx** [comment]
`mise trust --ignore` should handle this use-case
