### ISSUE TITLE
Documentation for .mise.toml syntax for renovate manager

### ISSUE THREAD

**Issue by BeneHa** [jdx/mise#2365]
Hi,

the renovate bot team recently added support for upgrading mise configs: https://github.com/renovatebot/renovate/releases/tag/37.426.0
They do not support all possible configurations yet, e.g. the "prefix:x" syntax. I started a discussion with the developer about that here: https://github.com/renovatebot/renovate/discussions/30101. The question is, where can I find the authoritative documentation on the syntax of the .toml files? The "prefix" notation is mentioned in the mise docs but I do not see a clear definition there.
 
I think a complete support of the .mise.toml files would also benefit adoption of mise itself, so it would be great if someone can help me out here :)

Best regards
BeneHa

**Comment by jdx** [comment]
I don't know how to expand more than what is shown there
