### ISSUE TITLE
Latest mise releases not available via Homebrew

### ISSUE THREAD

**Issue by roele** [jdx/mise#2371]
Due to `libgit2` dependency issues in brew regarding https://github.com/Homebrew/homebrew-core/pull/166767, most recent `mise` versions `2024.7.1` (https://github.com/Homebrew/homebrew-core/pull/176664) and `2024.7.2` (https://github.com/Homebrew/homebrew-core/pull/177210) are not available via brew. 

This is caused by the ugprade to `git2-0.19.0` which uses `libgit2-1.8.1` which fixes issues especially on Linux.

A possible workaround could be to use arch/os specific dependencies and build mise with an "older" `git2` dependency for macOS until `libgit2` has been updated successfully in `brew`. Or it may be easier to use vendored libgit2-sys for brew?

**Comment by jdx** [comment]
I mentioned this in that other thread but I kind of just want to ditch libgit2 and use [gitoxide](https://github.com/Byron/gitoxide) which is pure rust

**Comment by roele** [comment]
Using a rust solution with no C lib dependencies would be ideal but as of now there is no checkout support in gitoxide and it brings in 145 additional crates.

**Comment by jdx** [comment]
yikes, well that certainly is a problem

**Comment by jdx** [comment]
I have a potential fix, but I think it's unlikely to work since homebrew probably respects the lockfile

**Comment by jdx** [comment]
it might be possible to work around this by adding some logic in the homebrew formula to pin the git2 version but there also isn't many mise changes this summer since I'm busy with other things so it's probably not the most important thing for us to ship. This likely is just to annoy people that they aren't able to run the latest version with brew.

**Comment by roele** [comment]
agree, these dependency issues should be resolved within the brew ecosystem at some point (hopefully doesn't take another 3 months). if someone needs to run the most recent version there is always the option to install via curl or cargo.

**Comment by roele** [comment]
Seems the homebrew team has re-run the PRs which were failing because of this 🙌🏻

**Comment by roele** [comment]
Closing this issue, now 2024.7.3 is available.
