### ISSUE TITLE
Project task directory

### ISSUE THREAD

**Issue by rsyring** [jdx/mise#2383]
Refs: https://github.com/jdx/mise/discussions/2206

I'd like to see a setting in mise.toml to control where tasks for the project are found.  E.g.:

```
[settings]
tasks_dir = './tasks'
```

I think this should only change the location mise looks for the current project root and "down."  But not "up" the path.  So, the location of mise tasks for my OS user would still be at `~/mise/tasks`.

There are other issues discussed in #2206, but I don't think they need to be resolved for this setting to be useful.

**Comment by rsyring** [comment]
Also refs #2604 and #2610

**Comment by rsyring** [comment]
I didn't see a PR associated with the close and no recent PRs look like they addressed this.  Assuming that means this is a won't fix and you are sticking with `mise-tasks` or `mise/tasks` (or hidden versions)?

Thanks.

**Comment by jdx** [comment]
I added this a while ago https://mise.jdx.dev/tasks/#task-configuration
