### ISSUE TITLE
Settings to automatically install missing version on `cd`

### ISSUE THREAD

**Issue by tcrawford-figure** [jdx/mise#2385]
Please correct me if this is already a feature that I missed in the docs, but when I `cd` into a directory, it doesn't automatically install the defined version of the tool that `mise` detects. Instead, I might see a message like:

```shell
mise missing: terraform@1.7.1
```

What I would like to have is a setting to automatically install the missing tool after I `cd` into a directory so that I don't have to worry about typing `mise i`.

**Comment by syhol** [comment]
Now hooks exist, you can add this to your mise config:
```
[hooks]
enter = "mise install"
```
