### ISSUE TITLE
mise-action with version=latest fails on windows

### ISSUE THREAD

**Issue by sxlijin** [jdx/mise#2399]
**Describe the bug**
mise@latest on Windows is unavailable: https://mise.jdx.dev/mise-latest-win32-x64 is a 404

**To Reproduce**

in a github action with `runs-on: windows-latest`, run `mise-action` with no args

logs: 
https://github.com/BoundaryML/baml/actions/runs/10053172528/job/27785535829

**Comment by sxlijin** [comment]
Ah, sorry, I now see that mise support for windows is still in a very early state.

**Comment by jeremy** [comment]
See also: https://github.com/jdx/mise-action/issues/114

**Comment by jeremy** [comment]
Looks like we'll need a tweak to harmonize node `process.platform` with [std::env::consts::OS](https://doc.rust-lang.org/std/env/consts/constant.OS.html): https://github.com/jdx/mise-action/blob/bd6a003a27a0f214a71fa6a246f5a05c8a19d5c7/src/index.ts#L127-L134
