### ISSUE TITLE
Mise install cue not working

### ISSUE THREAD

**Issue by happysalada** [jdx/mise#2437]
**Describe the bug**
When doing `mise install cue` on linux x86-64 it errors out with a "could not uncompress" message

**To Reproduce**
mise use -g cue

**Expected behavior**
No problem when trying to install cue

**`mise doctor` output**

No errors and no warnings

**Additional context**
I dont think the problem is with mise but mote likely with the cue plugin. Not sure what to do in this case

**Comment by roele** [comment]
This is reproducible in asdf with `asdf install cue latest` (without version mise always installs the latest available according `ls-remote`)

It seems that the archive for latest version `0.10.0-0.dev` is not available and therefore unpacking (a 404 error page with ending .tar.gz or similar) fails. If you check for the latest stable version via `mise ls-remote cue`, you'll find `0.9.2` which seems to install just fine via `mise install cue@0.9.2`

**Comment by happysalada** [comment]
Hey thanks! Let me close this.
