### ISSUE TITLE
Is there a way to run a blocking task?

### ISSUE THREAD

**Issue by newhook** [jdx/mise#2439]
Can mise be used as an air replacement (for live reload of apps)?

https://github.com/air-verse/air

I was hoping to do something like:

`mise watch -t dev:api`

where `dev:api` was defined like:

```
[tasks."dev:api"]
run = 'cd api && go run .'
sources = ['api/**']
```

but it doesn't work. I imagine the reason is because the `go run .` blocks and therefore the watcher doesn't get a chance to run.

I was hoping to do that with multiple targets to orchestrate running a few applications for local dev purposes.

**Comment by CEbbinghaus** [comment]
Are you asking for long running commands to be cancelled and restarted when a file change is detected?

**Comment by jdx** [comment]
I'm working on a related project for daemons: https://github.com/jdx/pitchfork

that said, in this case I think you just need to pass the right argument to watchexec, I think it's `--restart`:

```
mise watch -t dev:api --restart
```
