### ISSUE TITLE
rvm and mise conflict

### ISSUE THREAD

**Issue by rakuyoMo** [jdx/mise#2454]
Suppose project A uses rvm and project B uses mise.

rvm's `source "$HOME/.rvm/scripts/rvm"` command will insert the ruby ​​version at the front of `PATH`. If this version is different from the version defined in `.mise.toml` in project B, the mise-related dependencies in project B will use the wrong ruby ​​version.

More specifically, fastlane recently supported mise: [asdf-fastlane](https://github.com/mollyIV/asdf-fastlane). But this plugin has the above problem.

Has anyone encountered this problem? Is there any good way to avoid this problem?
(Except for migrating all project dependencies to mise as soon as possible, because it is possible to clone other people's projects)

**Comment by roele** [comment]
Not sure i understand the problem entirely and i am not familiar with Ruby but i assume `source $HOME/.rvm/scripts/rvm` is part of a startup file (e.g. .bashrc, .bash_profile) file. The order of execution within the startup file defines what takes precedence so if you want `mise` to have precedence you should put the activation code for `mise` after the initialization of `rvm`.

```shell
# rvm activation code
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# mise activation code
export MISE_SHELL=bash
export __MISE_ORIG_PATH="$PATH"
mise() {
...
}
_mise_hook() {
...
};
if [[ ";${PROMPT_COMMAND:-};" != *";_mise_hook;"* ]]; then
  PROMPT_COMMAND="_mise_hook${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
fi
```

**Comment by rakuyoMo** [comment]
@roele Hello! Thank you for your reply.

> Not sure i understand the problem entirely and i am not familiar with Ruby but i assume source $HOME/.rvm/scripts/rvm is part of a startup file (e.g. .bashrc, .bash_profile) file.

Your guess is basically correct. My `.zshrc` file is as follows:

```shell
# Some irrelevant content ...

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH="$PATH:$HOME/.rvm/bin"

# For mise
eval "$(~/.local/bin/mise activate zsh)"
```

> The order of execution within the startup file defines what takes precedence so if you want mise to have precedence you should put the activation code for mise after the initialization of rvm.

No matter where `source "$HOME/.rvm/scripts/rvm"` is in the file, it will insert the relative path at the beginning of `PATH`. So adjusting the order is useless.

**Comment by roele** [comment]
@rakuyoMo There is a [activate-aggressive](https://mise.jdx.dev/configuration.html#activate-aggressive) setting which lets you enforce putting the tools in front of the path. Depending on how the rvm script works this might help.
