### ISSUE TITLE
This does not look like a tar arhive

### ISSUE THREAD

**Issue by happysalada** [jdx/mise#2490]
**Describe the bug**
When running mise use -g fzf you get an exit 1 could not uncomotess

**To Reproduce**
Mise use -g fzf
On x86-64 linux

**Expected behavior**
Mise can install the asdf fzf plugin

**`mise doctor` output**

```text
REPLACE WITH OUTPUT OF `mise doctor`
```

**Additional context**
It looks like the output of the fzf plugin are not compressed, i would expect that if the files are not compressed then this doesnt error out

**Comment by RubenMakandra** [comment]
This is the wrong place to report. Check this [issue](https://github.com/kompiro/asdf-fzf/issues/2) in asdf-fzf.   
`fzf` changed their release tags to include a `v`, which breaks the asdf plugin.

**Comment by happysalada** [comment]
Thank you !
