### ISSUE TITLE
zig@0.13.0 not installed in osx

### ISSUE THREAD

**Issue by tyoc213** [jdx/mise#2497]
**Describe the bug**
<img width="622" alt="imagen" src="https://github.com/user-attachments/assets/d78a665c-9aac-4c5f-b534-1e250cc12f35">

**`mise doctor` output**

```text
version: 2024.8.12 macos-arm64 (2024-08-20)
activated: yes
shims_on_path: no

build_info: 
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS
  Built: Tue, 20 Aug 2024 22:15:12 +0000
  Rust Version: rustc 1.80.1 (3f5fd8dd4 2024-08-06) (Homebrew)
  Profile: release

shell: 
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin23.0)

dirs: 
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/Library/Caches/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims

config_files: 
  ~/.config/mise/config.toml
  ~/.mise.toml
  ~/follow-llama-from-scratch/.mise.toml

backends: 
  cargo
  core
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins: 
  zig  https://github.com/cheetah/asdf-zig.git#9d11e5b

toolset: 
  python@3.11.9  

env_vars: 
  MISE_SHELL=zsh

settings: 
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf = true
  asdf_compat = false
  cargo_binstall = true
  color = true
  disable_default_shorthands = false
  disable_tools = []
  experimental = false
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  http_timeout = 30
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  libgit2 = true
  node_compile = false
  not_found_auto_install = true
  paranoid = false
  plugin_autoupdate_last_check_duration = "7d"
  python_default_packages_file = "~/.default-python-packages"
  python_pyenv_repo = "https://github.com/pyenv/pyenv.git"
  raw = false
  trusted_config_paths = []
  quiet = false
  verbose = false
  vfox = false
  yes = false
  ci = false
  debug = false
  trace = false
  log_level = "info"
  python_venv_auto_create = false

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false

No warnings found
No problems found
```

**Additional context**
Add any other context about the problem here. Consider running mise with `--debug` or `--trace` for extra debug info.

**Comment by roele** [comment]
While `mise install` does install tools to `~/.local/share/mise/installs`, it does not put them on your PATH by default. This can be verified with `mise ls`. Green versions indicate active and grey version inactive tools and the config source shows which config is used.

For tools to be on the path they need to be defined either in the global or a local (or project specific) configuration file. A more convenient command might be `mise use zig@0.13.0` which will create a `.mise.toml` file with tool and version specified or `mise use --global zig@0.13.0` which will write the tool version into the global configuration.

If you use `mise activate` (in your shell start file), changing into a directory with a `.mise.toml`file will automatically activate the tool versions defined in the local `.mise.toml` file.

You can find a quick introduction and most used commands at https://mise.jdx.dev/dev-tools/
