### ISSUE TITLE
Tool download URL rewriting?

### ISSUE THREAD

**Issue by seanhagen** [jdx/mise#2517]
I'm pretty sure this isn't possible, but I want to throw it out there.

I'm in the process of re-installing Linux on my laptop; and when running mise to re-install tools, several tools have changed their download paths since the plugin was written. For example, [the `protolint` package](https://github.com/spencergilbert/asdf-protolint) expects the download URL for Linux to find the package for 64-bit systems with a value of 'x86_64' -- but apparently at some point the `protolint` repo changed to using 'amd64'. The problem is that the `asdf-protolint` plugin just uses the output of `uname -m` -- which is 'x86_64'.

I was wondering if it'd be possible for mise to shim curl/wget in a way that allows re-writing the URL used for downloading releases from GitHub/etc?

In my case, I'd just want to replace `Linux_x86_64` with `Linux_amd64` if the version for protolint is above 0.45.0. 

I have already submitted a PR to the [asdf-protolint](https://github.com/spencergilbert/asdf-protolint/pull/38) repo, but just figured that a feature like this would help out folks who don't want to have to figure out how to update the bash scripts used by plugins 😅

**Comment by jdx** [comment]
I think the right answer here is just working with plugin authors. I don't think mise should do more here.
