### ISSUE TITLE
`mise toml`

### ISSUE THREAD

**Issue by jdx** [jdx/mise#2521]
add a way to edit `mise.toml` files:

```
$ mise toml set tools.python latest
$ mise toml rm tools.python
$ mise toml set FOO bar
$ mise toml add env._.path ./bin
```

**Comment by jdx** [comment]
@roele (because you're known for jumping on these sort of things) if you happen to look into this, reach out to me on discord first—I've got an idea to run by you first

**Comment by janbuchar** [comment]
Can this be made to not make `mise.toml` untrusted? 

This is what I currently need to do to make a python virtual environment:

```sh
mise use python
vim .mise.toml # edit to add [env] section
python -m virtualenv .venv # ...unless create=true was added during the edit
mise trust
```

I'd much prefer being able to just do this:
```sh
mise use python
mise toml set env._python.venv.path .venv
mise toml set env._python.venv.create true
```

Of course, a way to set `path` and `create` at once would be even better.

**Comment by jdx** [comment]
given the purpose of the trust feature is to prevent loading files from untrusted projects I think it stands to reason that manually setting things should automatically make them trusted
