### ISSUE TITLE
Separate installs of one version of language like virtualenv

### ISSUE THREAD

**Issue by asokol123** [jdx/mise#2523]
I want rather strange things: allow two different versions of `node@20`
For example, I have two projects - a/ and b/
They both use `node@20`, but I want to completely separate them, so `npm install -g` in one of them will not affect another.
Looks like it's possible to create something like this:
```
~/.local/mise/installs/node/20 # regular installation of node@20
~/.local/mise/installs/node/named-install-for-project-a-version-20
~/.local/mise/installs/node/named-install-for-project-b-version-20
```

**Comment by jdx** [comment]
I would just copy the directory, that will achieve that
