### ISSUE TITLE
Manual downloaded version detected as outdated

### ISSUE THREAD

**Issue by ayZagen** [jdx/mise#2548]
At the time of writing this bug request, bun version 1.1.27 released. So as usual, I tried to fetch it with mise by running 
```
mise up
```
but it didn't download the latest release
```
mise All tools are up to date
```

so I ran install command by specifying version:
```
mise install bun@1.1.27
mise bun@1.1.27 ✓ installed
```

But now, the ls shows that the latest version is outdated:
```
Tool   Version            Config Source              Requested
bun    1.1.26
bun    1.1.27 (outdated)  ~/.config/mise/config.toml latest
```

**Comment by roele** [comment]
Did you try a `mise cache clear`?

**Comment by ayZagen** [comment]
![{03605644-8AE5-4A4E-B692-8786B4A148D7}](https://github.com/user-attachments/assets/f34e96d3-3064-4e11-a651-48f2db7bb5b9)

**Comment by roele** [comment]
Pretty much the same issue as in #2275 i assume. The version host still has an older version and is not up to date as `curl mise-versions.jdx.dev/bun` shows. 

So disabling the version lookup via version host with `mise set MISE_USE_VERSIONS_HOST=false` should resolve this.

**Comment by ayZagen** [comment]
i couldn't tried your solution because currently after `mise up`, it is correctly shown, so closing in favor of #2275, thanks.
