### ISSUE TITLE
Pipx/uv: add option to inject packages into an existing virtual environment

### ISSUE THREAD

**Issue by ricardoseriani** [jdx/mise#2551]
Pipx has a concept of injecting a package into an existing virtual environment, for example, to add Pandas into the IPython environment.

For pipx you can use `pipx inject package [dependencies ...]`, like, `pipx inject bpython pandas`
For uv you can use `uv tool install --wit=<package>`, like `pipx tol install --with=pandas ipython`

I'm trying to use mise with pipx (specifically uv) to consolidate all my python, go and rust packages all in one place, so if possible, add this feature.

Thanks in advance for this awesome project. It's really changed my way of using/managing some of my software/languages and keep it sync in more than one machine.

Best regards.

**Comment by pappasam** [comment]
@ricardoseriani looks like, for poetry, this can be accomplished at install time:

```toml
"pipx:poetry" = { version = "latest", pipx_args = "--preinstall poetry-plugin-export" }
```

**Comment by ricardoseriani** [comment]
> @ricardoseriani looks like, for poetry, this can be accomplished at install time:
> 
> ```toml
> "pipx:poetry" = { version = "latest", pipx_args = "--preinstall poetry-plugin-export" }
> ```

Thanks for the information.
I was trying to know how to accomplish that since the issue was closed.
There is any way that I can do that directly in command line, while running the `mise install` or `mise use -g`?

**Comment by abossenbroek** [comment]
I bump into the same issue with dvc to install dvc-gs dependency. Preinstall doesn't seem to work. Tried

```
"pipx:iterative/dvc[gs]" = {version="latest"}
```

but dvc-gs package is not available when inspecting with `dvc doctor`. I can only get it to work with `pipx install dvc[gs]`
