### ISSUE TITLE
windows self-update from 2024.9.0 to 2024.9.1 fails

### ISSUE THREAD

**Issue by kylegrover** [jdx/mise#2556]
**Describe the bug**
```
$ mise self-update
Checking target-arch... mise-v2024.9.1-windows-x64.tar.gz
Checking current version... v2024.9.0
Checking latest released version... v2024.9.1
New release found! v2024.9.0 --> v2024.9.1
New release is compatible
mise ReleaseError: No asset found for target: `mise-v2024.9.1-windows-x64.tar.gz`
```

**To Reproduce**
`mise self-update` with v2024.9.0 windows. I used git-bash but I suspect that's irrelevant.

**Additional context**
I think this is a format mismatch somewhere, mise-v2024.9.1-win-x64... does seem to exist (without the dows)

**Comment by jeremy** [comment]
build-tarball.sh [needs to switch](https://github.com/jdx/mise/blob/338d24f41054a8c2573d6ec1a679e0f6ed56c457/scripts/build-tarball.sh#L10-L26) from `win` to `windows` to match [std::env::costs::OS](https://doc.rust-lang.org/std/env/consts/constant.OS.html) (which self-update uses).

**Comment by jdx** [comment]
nice catch, you're right, unfortunately changing that might break a lot of stuff but I'll see what I can do
