### ISSUE TITLE
Missing contents of specific tool directory doesn't prompt for an install 

### ISSUE THREAD

**Issue by lucasteligioridis** [jdx/mise#2557]
**Describe the bug**

Sorry if this has already been raised, I searched issues and didn't come across anything that looked familiar.

There have been a few instances where we've had mise run an install of a specific tool chain (node/ruby for example) where the directory of the tool exists but the contents are either non-exist (directory completely empty) or there has been a missing `bin/` directory. Here are 2 examples of what I've seen:

Missing `bin/` directory:
```
ls ~/.local/share/mise/installs/node/22.8.0
include/  lib/  share/  CHANGELOG.md  LICENSE  README.md
```

Completely empty directory:
```
ls ~/.local/share/mise/installs/node/22.8.0
```

This might be describing 2 separate problems, but with both of these issues `mise` reacted like everything was "installed" and kept popping up with errors around `mise No version is set for shim: node` which led us astray a bit and not understanding why this was reporting this outcome. 

**To Reproduce**
Delete the `bin/` directory or empty the contents of one of the version directory of any tool and see the output.

**Expected behavior**
Not sure the best way to resolve this, because it might be different with plugins or different tools, but it sounds like it could be a better/safer approach if the `bin/` contents are checked as the "source of truth". If the binary itself is missing, then `mise` could consider this tool not installed and prompt for a install or at least `reinstall`. Something extra steps (if easily possible) to better validate an install has finished correctly would be nice.

**Additional context**

To the original problems here, I actually have no idea how the state of these tools had a missing directory like the `bin/` at all or how contents were missing entirely from the folder. It's possible that halfway through a `mise` install there was an interruption and the install never fully completed? Not sure what else it could be.

**Comment by jdx** [comment]
During installation a cache file should be created to note that an installation is incomplete. Sounds like that functionality is not working correctly.

The problem here is we don't really know what the directory _should_ look like. Even a completely empty bin directory may actually be ok in edge cases—though none come to mind at the moment.

That said, an entirely empty install directory probably is cause for concern.

I think the right path forward is for me (or someone) to verify the incomplete install cache file is working correctly.

**Comment by lucasteligioridis** [comment]
> The problem here is we don't really know what the directory should look like. Even a completely empty bin directory may actually be ok in edge cases—though none come to mind at the moment.

I figured this would be the case and expected this to be a difficult problem to resolve without understanding what "good" should look like.

To be fair this case I've only seen a few times across many different machines, but maybe a fully empty directory would be something more tenable to resolve.
