### ISSUE TITLE
Ability to install automatically binaries to `/usr/local/bin`

### ISSUE THREAD

**Issue by MustCodeAl** [jdx/mise#2562]
This would help would with integrations for IDES tremendously, instead of having to specify mise's shim path. or creating symlinks to the shims, it would be nice if it installed binaries to `/usr/local/bin` automatically by default for root users and `$HOME/bin` for non-root users ,and or allow to users to select a custom path. like [ubi](https://github.com/houseabsolute/ubi#environment-variable-parameters) does

**Comment by jdx** [comment]
I'm not sure I follow. This would only support global installs of tools, you wouldn't be able to use project-versions which is a fundamental feature in mise.

**Comment by MustCodeAl** [comment]
> I'm not sure I follow. This would only support global installs of tools, you wouldn't be able to use project-versions which is a fundamental feature in mise.

it would be more so for the tools that could be installed with asdf like  delta, fzf, lazygit, etc. and I find being able to install languages and tools globally with mise keeps my env very clean and organized. Though I guess making it default install to global for people wouldn't make much sense, but allowing the option  would be nice.
