### ISSUE TITLE
Create a setting for preferred java vendor

### ISSUE THREAD

**Issue by rocketraman** [jdx/mise#2620]
It would be nice if there was a way to set the preferred java vendor.

I would suggest two options:

* `java_preferred_vendor` (string) to set the preferred java vendor, so "21" when `java_preferred_vendor` is set to `temurin`, then `java@21` would resolve to `temurin-21`.
* `java_allow_preferred_vendor` (boolean) if false, then 21 would resolve to `openjdk-21` rather than `temurin-21`.

The purpose of the former is to allow a user or project maintainer to generally set a preferred vendor.

The purpose of the latter is to allow a project maintainer to override a user's settings and require the vendor to be explicitly set by the project. The reason for this is that a project may have licensing restrictions, have explicitly purchased a commercial sdk, or so on. In this case, a user's local setting for `java_preferred_vendor` should not override the desired sdk.

These comments in a different issue are linked here for reference:

* https://github.com/jdx/mise/issues/2618#issuecomment-2364115841
* https://github.com/jdx/mise/issues/2618#issuecomment-2364121337
* https://github.com/jdx/mise/issues/2618#issuecomment-2364554415

**Comment by jdx** [comment]
> java_allow_preferred_vendor (boolean) if false, then 21 would resolve to openjdk-21 rather than temurin-21.

Why wouldn't they just use `openjdk-17`?

**Comment by rocketraman** [comment]
> > java_allow_preferred_vendor (boolean) if false, then 21 would resolve to openjdk-21 rather than temurin-21.
> 
> Why wouldn't they just use `openjdk-17`?

Good point.

**Comment by roele** [comment]
Such a setting will lead to different behaviour for different users (could be desired though, see #1674).

Also this would cause issues when used on a per project level. Java is installed globally in `$MISE_DATA_DIR/installs/java` and `mise` just checks if a version exists in the folder. It cannot distinguish between a folder `23.0.0` containing openjdk and `23.0.0` containing temurin.

**Comment by jdx** [comment]
> Such a setting will lead to different behaviour for different users

isn't that the point of any setting? haha

> Also this would cause issues when used on a per project level.

That's a good point. What we could do is always put the vendor name and as some logic in the resolving to make that work, but as you're well aware that's piling on more code to what is already the nastiest part of the codebase.

**Comment by roele** [comment]
i'm starting to believe that removing the shorthand would be a better choice :)

anyways i think we should keep as is. we can make it more clear in the docs that the shorthand is referring to openjdk, is not updated after 6 months and can recommend to use specific vendors.

**Comment by rocketraman** [comment]
> anyways i think we should keep as is. we can make it more clear in the docs that the shorthand is referring to openjdk, is not updated after 6 months and can recommend to use specific vendors.

That works for me.

**Comment by rocketraman** [comment]
> [Aliases versions](https://mise.jdx.dev/dev-tools/aliases.html#aliased-versions) should help setting up a mapping between shorthand versions and your preferred vendor.

That works reasonably well, other than the fact that I have to remember to keep the alias versions up-to-date.
