### ISSUE TITLE
Release 2024.9.7 breaks configurations that were using `v` in version names with go backend

### ISSUE THREAD

**Issue by sgtsquiggs** [jdx/mise#2634]
**Describe the bug**
Since the release of 2024.9.7 we're seeing:
```mise versions should not start with a 'v', please remove it```
in our CICD runs during `mise install`

**To Reproduce**

Use mise 2024.9.7 with config
```text
[tools]
go = "1.22.4"
node = "lts-hydrogen"
python = "3.10"
# tool pins should be more strict
golangci-lint = "1.54.2"
just = "1.25.2"
pnpm = "8"
poetry = "1.4.2"
sqlc = "1.21.0"
jq = "1.7.1"
yq = "4.43.1"
"go:github.com/clear-street/reinforcer/cmd/reinforcer" = "v0.3.1"
"go:github.com/golang/mock/mockgen" = "v1.6.0"
"go:github.com/sgtsquiggs/gta/cmd/gta" = "v0.3.1"
"go:github.com/sgtsquiggs/tools/cmd/structtagger" = "v0.1.0"
"go:github.com/vektra/mockery/v2" = "v2.43.0"
"go:golang.org/x/tools/cmd/stringer" = "v0.21.0"
"go:golang.org/x/vuln/cmd/govulncheck" = "v1.0.1"
"go:github.com/dmarkham/enumer" = "v1.5.9"

[plugins]
sqlc = "https://github.com/schmir/asdf-sqlc.git"
jq = "https://github.com/lsanwick/asdf-jq.git"
yq = "https://github.com/sudermanjr/asdf-yq.git"
```

in cicd we overlay this local config:
```text
[tools]
go = "system"
node = "system"

[settings]
python_compile = true
jobs = 2
```

**Expected behavior**

mise should install dependencies without error

**`mise doctor` output**

```text
will need to capture this from cicd job runner...
```

**Additional context**
Add any other context about the problem here. Consider running mise with `--debug` or `--trace` for extra debug info.

**Comment by sgtsquiggs** [comment]
Capturing verbose install logs and doctor output in a few minutes

**Comment by sgtsquiggs** [comment]
This seems to be due to the changes for the go backend - if you were using `v` in your versions mise now fails to install them.

**Comment by sgtsquiggs** [comment]
This is a pain. We have to either pin to a previous version, or get _every developer_ to update to the latest, and then update our mise configs.

**Comment by sgtsquiggs** [comment]
This can be reproduced locally w/ mise 2024.9.7:

```text
❯ mise install go:golang.org/x/tools/cmd/stringer@v0.21.0
mise versions should not start with a 'v', please remove it
mise Run with --verbose or MISE_VERBOSE=1 for more information
```

**Comment by jdx** [comment]
@roele is working on a fix, but as I mentioned in the other thread the go backend is experimental so in general don't be surprised to see breaking changes
