### ISSUE TITLE
hints should not mess with completions

### ISSUE THREAD

**Issue by RafalSkolasinski** [jdx/mise#2683]
Right now when I try to type
```bash
mise use kube<tab>
```

I am getting a hint
```bash
$ mise use kubemise hint see available plugins with mise registry        # < messed up line with my partial + hint
mise hint disable this hint with mise settings set disable_hints registry or all with mise settings set disable_hints "*"
$ mise use kube-controller-tools@0.16.3                                                  # < completion continues as usual
kubebuilder@  kubectl-bindrole@  kubefedctl@  kubergrunt@  kubeval@                kube-credential-cache@
kubecm@       kubectl-buildkit@  kubefirst@   kubeseal@    kubevela@               kube-linter@
kubecolor@    kubectl-convert@   kubelogin@   kubesec@     kube-capacity@          kube-score@
kubeconform@  kubectl-kots@      kubemqctl@   kubeshark@   kube-code-generator@
kubectl@      kubectx@           kubent@      kubespy@     kube-controller-tools@
```

Hints are great and I love them but they should not mess with completions. I am happy to see them once I execute my command. 
~Also, would be nice if the "mise settings set disable_hints "*"" would hint on how to disable this specific hint, I wouldn't want to miss on others.~

**Comment by roele** [comment]
This looks similar to or like a regression of #2558

**Comment by RafalSkolasinski** [comment]
I should've mention I am using `fish` shell, the https://github.com/jdx/mise/issues/2558 is specific to zsh.

**Comment by jdx** [comment]
> Also, would be nice if the "mise settings set disable_hints "*"" would hint on how to disable this specific hint, I wouldn't want to miss on others.

that is in the output you sent

**Comment by RafalSkolasinski** [comment]
> that is in the output you sent

oh, that is there indeed...
