### ISSUE TITLE
Automatic disabling of mise or Creating a unique config in certain directories. (Bug: Mise not setting path according to MISE_CONFIG_DIR)

### ISSUE THREAD

**Issue by Shobhit0109** [jdx/mise#2687]
In some projects, when using nix or any other mise can mess up paths.

Solution: 
According to me, this can be done using 2 ways:
1. Using direnv to disable mise.
2. Using local config to disable global config which contains all tools. (or Easy access to choose which to disable).

**Comment by jdx** [comment]
I recommend replacing direnv with mise

**Comment by Shobhit0109** [comment]
How can i auto activate mise in a directory? 
I also want to ask how can i auto install missing tools?

**Comment by jdx** [comment]
what you could probably do is set `MISE_CONFIG_DIR=somerandomthing` in envrc

**Comment by Shobhit0109** [comment]
This might be a bug in mise but when using MISE_CONFIG_DIR variable mise is not updating the paths in fish shell. 
NOTE: I have set this variable using universal variable fish feature so that it applies to all subshells.

As you can see in this screenshot.
![image](https://github.com/user-attachments/assets/9b141cd1-75d1-4e80-aeb7-96c836081df0)

**Comment by jdx** [comment]
I'm not really sure what you're wanting here but it sounds like maybe you're using MISE_CONFIG_DIR instead of MISE_DATA_DIR

**Comment by LandonSchropp** [comment]
@jdx I have the same use case as @Shobhit0109: My company uses Nix to manage tools for one directory, but I still would like to use Mise globally. I was hoping something like this would work:

``` toml
[tools]
no,de = false
pnpm = false
ruby = false
```
