### ISSUE TITLE
How to print log from tools called via mise exec?

### ISSUE THREAD

**Issue by malcommac** [jdx/mise#2690]
Hi, 
I'm using Mise in my development workflow, especially with the Tuist (tuist.io) CLI tool. Unfortunately, when I call tuist generate via Mise (mise x -- tuist generate), the output from Tuist never prints. Is there a way to capture the stdout of the tool being called?
Thanks

**Comment by jdx** [comment]
mise already does this, it's probably something to do with tuist 

Cc @pepicrft

**Comment by pepicrft** [comment]
@malcommac that's odd, we output the logs through the standard pipelines, which Mise forwards. I double-checked with the github.com/tuist/tuist repository, where we also use Tuist against Tuist, and it works as expected. What do you get if you try there:

```
mise x -- tuist generate
```
