### ISSUE TITLE
Updating Bun to the Latest Version

### ISSUE THREAD

**Issue by 7TeamApp** [jdx/mise#2691]
Can you update Bun to the latest version?

![image](https://github.com/user-attachments/assets/97d8209a-caa2-416b-8152-9c89682a5a9b)

**Comment by jdx** [comment]
it seems the vfox plugin manually updates the versions in this repo: https://github.com/ahai-code/sdk-sources. This issue is with [vfox-bun](https://github.com/ahai-code/vfox-bun), not mise
