### ISSUE TITLE
bash completion generates "nosort" error on macOS with Bash v3

### ISSUE THREAD

**Issue by dgholz** [jdx/mise#2700]
**Describe the bug**

This is a dupe of #883. I see this error when opening a new Terminal window on macOS:
```
-bash: complete: nosort: invalid option name
```

I see in the original ticket:

> [the Bash completion code] is generated (currently, I have some plans to change this) by [clap_complete](https://docs.rs/clap_complete/4.4.1/clap_complete/)

`clap_complete` was removed in 87141bc6f8913c53cd1cf98ebd8b5dab3cb2c0a2, and I see in the diff that the workaround it provided for older versions of Bash was not preserved.
https://github.com/jdx/mise/blob/d9b8e9e69de50f2dc0de9fc4e0f5418075f85680/completions/mise.bash#L5044-L5048

DO you think it could be added back in?

**Comment by jdx** [comment]
targeting 20+ year old bash is not high on my priority list, just upgrade it

**Comment by dgholz** [comment]
I see the Bash completions are generated by [jdx/usage](https://github.com/jdx/usage), I think this issue is in the wrong place.
