### ISSUE TITLE
Faster installs for erlang

### ISSUE THREAD

**Issue by paradox460** [jdx/mise#2721]
Currently, both the old ASDF erlang plugin and the built-in erlang plugin depend on kerl to build the erlang binary every single time.

This is acceptable on a dev machine, but when trying to use in CI, particularly on a slower project, where builds are infrequent, it can stretch a build to many times its length, as erlang has to be rebuilt every time.

https://github.com/erlef/setup-beam uses pre-built binaries that target various operating systems common in CI providers. It does this by sourcing them from various files on `builds.hex.pm` or on a mirror, as they are originally built by [bob](https://github.com/hexpm/bob).

The [logic for choosing which file to download is fairly simple, albeit long, due to the amount of things supported](https://github.com/erlef/setup-beam/blob/main/src/setup-beam.js#L751-L1002). But at its heart its just attempting to download `https://builds.hex.pm/builds/otp/<architecture>/<versionSpec>.tar.gz` for erlang versions.

There's been a [discussion about this for a long time on the old asdf-erlang plugin](https://github.com/asdf-vm/asdf-erlang/issues/165), but it hasn't seen much traction since 2022

**Comment by cw789** [comment]
Also for MacOS there are now builds available: https://elixirforum.com/t/new-community-maintained-otp-builds-for-macos/67338

**Comment by jdx** [comment]
I'd really love to see this as I can tell erlang+elixir are quite popular both with asdf and mise. I would greatly welcome a contribution if someone is willing to help. I may get around to it soon otherwise. [swift](https://github.com/jdx/mise/pull/3271) would be a good reference on how to do this.
