### ISSUE TITLE
uvx --with-requirements

### ISSUE THREAD

**Issue by KyleKing** [jdx/mise#2722]
I have a use case where I want `uv` tool dependencies to be specified like `uvx --with-requirements=requirements-mdformat.txt mdformat`. A similar idea to expand CLI argument support was floated for `pipx` to support `--preinstall` in https://github.com/jdx/mise/issues/2491#issuecomment-2322629056, but adding either of these arguments would cause the tools to diverge.

With how `uvx` works, an alternative might be an alias that is directory-specific and unloaded (e.g. `alias mdformat="uvx --with-requirements=requirements-mdformat.txt mdformat"`). This is probably possible today combining `direnv` (or mise) to set directory specific environment variables and a shell function that reads these variables to build the `uvx` command

**Comment by KyleKing** [comment]
Maybe what could address this request is a more general `install-options` to specify a list of CLI arguments that are passed to the "install" invocation of the backend? Rather than explicitly specifying options?

**Comment by joshriverscambia2019** [comment]
The `install-options` solution would be helpful to me, as adding a `--with` CLI flag seems to be the [correct way to install Ansible with uv](https://github.com/astral-sh/uv/issues/6314#issuecomment-2365278852) at present.
