### ISSUE TITLE
Allow `config ls` to return JSON

### ISSUE THREAD

**Issue by dpassen** [jdx/mise#2769]
While `mise ls` and `mise tasks ls` support the `--json/-J` flag to emit JSON, `mise config ls` does not. This would be a welcome addition, especially for tooling that relies on reading the output in a consistent format.

**Comment by jdx** [comment]
@roele sorry can you change the output to "tools" instead of "plugins"?

**Comment by roele** [comment]
Right, these are actually tools (ToolRequest says it already) was thrown off by the table header.  Should we adapt that as well?

**Comment by jdx** [comment]
Yeah
