### ISSUE TITLE
daemons

### ISSUE THREAD

**Issue by jdx** [jdx/mise#2806]
a feature I'd like to see in mise would be the ability to launch a daemon (which likely would just be a mise task) while in a particular directory. I could use this myself for launching databases, local api services, or syncing files (e.g.: rsync).

I think this would be a little tricky since mise should also close when it exits the directory and mise doesn't really know when something is exited. I think this would require making mise itself a daemon or something to monitor and know when to close the child task daemon.

**Comment by jdx** [comment]
meh

**Comment by jbadeau** [comment]
This feature is a really cool aspect of flox https://flox.dev/docs/concepts/services/

Is there any chance to have this worked on? We would also be willing to contribute.

**Comment by jdx** [comment]
it's not going to be a part of mise. I started writing a separate project called pitchfork for this but it's quite young and I'm not actively working on it right now.
