### ISSUE TITLE
ruby-build missing

### ISSUE THREAD

**Issue by jesse-fabric** [jdx/mise#2817]
I'm sure this is something I screwed up, but when attempting to install a specific Ruby version, I get the following:

```
❯ mise up
mise WARN  ruby build tool update error: failed to update ruby-build: No such file or directory (os error 2)
mise ERROR Failed to install ruby@2.5.8
mise ERROR failed to execute command: ~/Library/Caches/mise/ruby/ruby-build/bin/ruby-build 2.5.8 /Users/<user>/.local/share/mise/installs/ruby/2.5.8
mise ERROR No such file or directory (os error 2)
```

`~/Library/Caches/mise/ruby/ruby-build/bin/ruby-build` does not exist. What's the best way to restore it? Yes I know that's a super-old Ruby (it's an old project), but it seems to affect newer versions, too.

**Comment by jdx** [comment]
`mise cache clear`

**Comment by stan-stately** [comment]
i hit this error on my CI any time I bump the version in my `.ruby-version` file. is it possible to fix this without clearing the cache? 

i'd need to run a `mise cache clear` before every CI run which would decimate CI performance

**Comment by jdx** [comment]
can someone print the debug output that is experiencing this? I suspect it's probably the lockfile that's causing this but I'm not sure why

**Comment by mobilutz** [comment]
> `mise cache clear`

Thanks @jdx for the solution.

How about adding this information to the `warn` output? I have 0 knowledge in Rust and don't know how to add such a thing here, otherwise I would love to open a PullRequest for this idea.
