### ISSUE TITLE
Add `hook-env` command to CLI reference list

### ISSUE THREAD

**Issue by texdade** [jdx/mise#2862]
Hello,

is there any specific reason why the command `mise hook-env` is not in the CLI reference list? Since `mise activate` should only be used in interactive shell session, it seems that `mise activate --shims` it's the only possibility when working with scripts, but to me it seems that using `mise hook-env` works just as fine, but without the hassle of shims :D

**Comment by jdx** [comment]
Because it works fine until it doesn't. There's lots of gotchas with that method so it's not promoted in the documentation. hook-env is an internal command so it is hidden.
