### ISSUE TITLE
Allow installing python on Windows via vfox backend

### ISSUE THREAD

**Issue by alcroito** [jdx/mise#2864]
With latest version of mise, if i run `mise use python` on an arm windows machine, I get:
```
mise ERROR Failed to install python@3.13.0
mise ERROR python can not currently be compiled on windows
```
I thought maybe i can use the vfox backend to install python, but:
```
$ mise use vfox:python
mise ERROR Invalid version: vfox-python
mise ERROR relative URL without a base
```

Running `mise registry` doesn't show vfox:python in the list, but it seems to be an officially supported plugin of vfox,
as listed here: https://vfox.lhan.me/plugins/available.html
https://github.com/version-fox/vfox-python

I thought maybe i can specify the relative github url, but not even the example from the docs seems to work:

```
$ mise use -g 'vfox:version-fox/vfox-cmake'
mise ERROR Failed to install vfox:version-fox/vfox-cmake@3.30.5
mise ERROR Invalid version: vfox-version-fox-vfox-cmake
mise ERROR relative URL without a base
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

Would it be possible to allow installing python via vfox backend?

**Comment by jdx** [comment]
It used the html module in vfox which I haven't added support for yet: https://github.com/jdx/vfox.rs/issues/4

Can you use the core plugin for python in the meantime?
