### ISSUE TITLE
Failed to deserialize __MISE_WATCH

### ISSUE THREAD

**Issue by theMackabu** [jdx/mise#2880]
**Describe the bug**
Warning message on shell start

**To Reproduce**
- Install mise `mise WARN  Failed to deserialize __MISE_WATCH`
- Add `eval "$(mise activate env)"` to ~/.zshrc
- Load your shell

**Expected behavior**
No warning message

**`mise doctor` output**

```bash
version: 2024.10.13 linux-x64 (ee83488 2024-10-28)
activated: yes
shims_on_path: no

build_info:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Mon, 28 Oct 2024 03:25:17 +0000
  Rust Version: rustc 1.81.0 (eeb90cda1 2024-09-04)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-redhat-linux-gnu)

dirs:
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/.cache/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims

config_files:
  ~/.config/mise/config.toml

backends:
  cargo
  core
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:

toolset:
  node@23.1.0

env_vars:
  MISE_SHELL=zsh

settings:
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf_compat = false
  cache_prune_age = "30d"
  ci = false
  color = true
  debug = false
  disable_backends = []
  disable_default_registry = false
  disable_hints = []
  disable_tools = []
  experimental = false
  fetch_remote_versions_cache = "1h"
  fetch_remote_versions_timeout = "10s"
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  http_timeout = "30s"
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  libgit2 = true
  lockfile = false
  log_level = "info"
  not_found_auto_install = true
  paranoid = false
  pin = false
  plugin_autoupdate_last_check_duration = "7d"
  quiet = false
  raw = false
  trace = false
  trusted_config_paths = []
  use_versions_host = true
  verbose = false
  yes = false

  [cargo]
  binstall = true

  [node]

  [pipx]
  uvx = false

  [python]
  default_packages_file = "~/.default-python-packages"
  pyenv_repo = "https://github.com/pyenv/pyenv.git"
  venv_auto_create = false
  venv_stdlib = false

  [ruby]
  default_packages_file = "~/.default-gems"
  ruby_build_repo = "https://github.com/rbenv/ruby-build.git"
  ruby_install = false
  ruby_install_repo = "https://github.com/postmodern/ruby-install.git"

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false
No warnings found
No problems found
```

**Additional context**
![Screenshot From 2024-10-31 17-51-19](https://github.com/user-attachments/assets/7243728b-21b8-4fb4-aa09-0459bf2a2899)
![Screenshot From 2024-10-31 17-51-55](https://github.com/user-attachments/assets/6f9d99eb-0932-4ae7-90d0-d713899ad180)

**Comment by jdx** [comment]
I have not seen reports of this in over 2 years. I suspect this was caused by something not mise modifying that env var

**Comment by theMackabu** [comment]
<img width="559" alt="Screenshot 2024-11-27 at 2 07 16 PM" src="https://github.com/user-attachments/assets/a7479043-126c-4a4b-a886-6f448dcdf82c">
I seem to be having a new issue

**Comment by dimitarvp** [comment]
Just got this warning after upgrading from `v2024.11.32` to `v2024.11.36` today. Happened on both Linux and macOS.

Exact text error:

```plain
mise WARN  Failed to deserialize __MISE_WATCH missing field `latest_update`
```

**Comment by jdx** [comment]
that's expected. The structure of that data changed so it's not compatible with other versions. If you re-open your terminal it shouldn't happen again unless you use an older version of mise again.

**Comment by dimitarvp** [comment]
Oh, true. I just did and the warning is no longer there. Thanks.

**Comment by halostatue** [comment]
I have added a [warning](https://github.com/macports/macports-ports/pull/26824/files#diff-e2d5ad5ab4267915d8ebba41a352a4ac6f8e63951638d27ebae96bb469893f8eL75-R84) about this to the latest MacPorts pull request (https://github.com/macports/macports-ports/pull/26824).

**Comment by Joker666** [comment]
I am getting this error even with new terminals tho. Started with the new update.

https://github.com/user-attachments/assets/c4c194b0-ad15-461d-86e0-6098c75db456

**Comment by jdx** [comment]
you probably have multiple versions of mise conflicting with one another

**Comment by halostatue** [comment]
> Strange it is true, I am not sure if the new update has anything to do with it.
> 
> ```
> $ which -a mise
> /opt/homebrew/opt/mise/bin/mise
> /opt/homebrew/bin/mise
> ```
> 
> Wondering which one is the canonical path, both has the same version.

Two things:

- you should not have `/opt/homebrew/opt/` *anything* in your `$PATH`, which looks to be the case; check how your `$PATH` is initialized. (Homebrew paths should be `…:/opt/homebrew/bin:/opt/homebrew/sbin:…` or similar.)
- you may want to `brew uninstall -f mise` and then make sure that both are gone before doing `brew install mise` again.

**Comment by Joker666** [comment]
> > Strange it is true, I am not sure if the new update has anything to do with it.
> > ```
> > $ which -a mise
> > /opt/homebrew/opt/mise/bin/mise
> > /opt/homebrew/bin/mise
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Wondering which one is the canonical path, both has the same version.
> 
> Two things:
> 
>     * you should not have `/opt/homebrew/opt/` _anything_ in your `$PATH`, which looks to be the case; check how your `$PATH` is initialized. (Homebrew paths should be `…:/opt/homebrew/bin:/opt/homebrew/sbin:…` or similar.)
> 
>     * you may want to `brew uninstall -f mise` and then make sure that both are gone before doing `brew install mise` again.

Uninstalling `brew uninstall -f mise` throws errors and reinstalling it back results in `mise` putting `/opt/homebrew/opt/mise/bin/mise` in the path.

I was tracing back how it was getting added to the path.

```
$ env | grep PATH
__MISE_ORIG_PATH=/opt/homebrew/opt/mise/bin
```

Later `__MISE_ORIG_PATH` is added to the PATH.

https://github.com/jdx/mise/blob/main/src/shell/fish.rs#L21

I am trying to figure out how is this env var set in the first place.

**Comment by halostatue** [comment]
That's not how `__MISE_ORIG_PATH` works. This is something that the mise shell integrations set to the value of `$PATH` when you enter a directory managed by mise. It then updates `$PATH` to include the direct paths to the mise tools (at the beginning). When you *leave* that directory, `$PATH` is replaced with `$__MISE_ORIG_PATH`.

The output of `echo $PATH` is going to be more valuable for debugging this, and what I am expecting to see is `/opt/homebrew/bin`, `/opt/homebrew/sbin`, and `/opt/homebrew/opt/mise/bin` — and that last one is the incorrect value that should not be in your `$PATH` under any circumstances. It is likely something in your `.zshrc` or `config.fish` or `.bashrc` is somehow getting that path.

I use mise from MacPorts (I am a maintainer on the portfile) and don't use it from Homebrew (I’m trying to eliminate most of my homebrew dependencies except casks), so I can't really help much further with this — but this is *not* going to be a mise issue, but in your shell configuration files.

**Comment by jdx** [comment]
just for what it's worth, if you're running 2 different versions of mise (presumably with one never receiving updates and likely months out of date), I have absolutely no clue what kind of issues that might cause but I would not be surprised if it manifested in extremely unusual behavior which would be very hard to diagnose. That is a serious problem and if this serialization error is elucidating that—well it's probably a good thing.

**Comment by dudicoco** [comment]
I'm also running into this error after upgrading to the latest version of mise:
```sh
INSERT ➜  mise --version                  
2024.11.37 macos-arm64 (7ac5ab3 2024-11-30)

package-managers 
INSERT ➜  brew list | grep mise

```

**Comment by jdx** [comment]
> I'm also running into this error after upgrading to the latest version of mise:
> 
> ```sh
> 
> INSERT ➜  mise --version                  
> 
> 2024.11.37 macos-arm64 (7ac5ab3 2024-11-30)
> 
> 
> 
> INSERT ➜  brew list | grep mise
> 
> 
> 
> ```

Good. Fix it.

**Comment by brandon-welsch** [comment]
BTW if you have the same issue inside VS Code, creating new terminal doesn't fix the issue, it still appear. So you need to restart VS Code and after that it disappear completely 😉

**Comment by jc00ke** [comment]
![image](https://github.com/user-attachments/assets/afa35a9e-47bc-414f-8e2f-e54f29705c3f)
 
I'm seeing this on my desktop that was off all last week. Turned it on this morning, updated (via `apt`) and now I see this error. I tried uninstalling, opening a new terminal, then reinstalling, then opening a new terminal and I still see the warning. Please let me know what other info might be helpful in debugging this! Thanks! :pray:

**Comment by halostatue** [comment]
> I'm seeing this on my desktop that was off all last week. Turned it on this morning, updated (via `apt`) and now I see this error. I tried uninstalling, opening a new terminal, then reinstalling, then opening a new terminal and I still see the warning. Please let me know what other info might be helpful in debugging this! Thanks! 🙏

Why do you have mise in both `/bin/mise` and `/usr/bin/mise`? Figure that out and you might be able to resolve this.

**Comment by Joker666** [comment]
> > I'm seeing this on my desktop that was off all last week. Turned it on this morning, updated (via `apt`) and now I see this error. I tried uninstalling, opening a new terminal, then reinstalling, then opening a new terminal and I still see the warning. Please let me know what other info might be helpful in debugging this! Thanks! 🙏
> 
> Why do you have mise in both `/bin/mise` and `/usr/bin/mise`? Figure that out and you might be able to resolve this.

This is the same issue I have in my Linux machine as well, couldn't figure out why both are in the PATH, not in Mac, not in Linux.

However, the warning message has gone away after restarting the VS Code.

> just for what it's worth, if you're running 2 different versions of mise (presumably with one never receiving updates and likely months out of date)
The real issue is not two different versions of `mise` are installed. It's the same one, the same version.

```
$ brew list | grep mise
> mise
```
One entry. Both `/opt/homebrew/opt/mise/bin` and `/opt/homebrew/bin/mise` in Mac is the same version, same for Linux.
/bin/mise and /usr/bin/mise

The issue is mise is installed here `/opt/homebrew/opt/mise`, just like many other tools in `/opt/homebrew/opt/`. However `/opt/homebrew/opt/mise/bin` should never be added to the path, just like

`/opt/homebrew/opt/btop/bin` is not in the path but

```
$ which -a btop
/opt/homebrew/bin/btop
```

**Comment by jdx** [comment]
if it's the same version this error wouldn't happen

**Comment by jc00ke** [comment]
Could there be something up with the `apt` install?

Debugging below shows that installing it via `apt` is putting the 2 executables in `/usr/bin/` and `/bin/`. That's def not something I'm doing manually. I have not tried to restart my computer, but will in the morning.

```
jesse@jimmie:~$ which -a mise
/usr/bin/mise
/bin/mise

jesse@jimmie:~$ sudo apt remove mise
REMOVING:                       
  mise

Summary:
  Upgrading: 0, Installing: 0, Removing: 1, Not Upgrading: 0
  Freed space: 33.9 MB

Continue? [Y/n] Y
(Reading database ... 509288 files and directories currently installed.)
Removing mise (2024.11.37) ...
Processing triggers for man-db (2.13.0-1) ...

jesse@jimmie:~$ which -a mise

jesse@jimmie:~$ sudo apt install mise
Installing:                     
  mise

Summary:
  Upgrading: 0, Installing: 1, Removing: 0, Not Upgrading: 0
  Download size: 12.2 MB
  Space needed: 33.9 MB / 6,223 MB available

Get:1 https://mise.jdx.dev/deb stable/main amd64 mise amd64 2024.11.37 [12.2 MB]
Fetched 12.2 MB in 0s (41.2 MB/s)
Selecting previously unselected package mise.
(Reading database ... 509282 files and directories currently installed.)
Preparing to unpack .../mise_2024.11.37_amd64.deb ...
Unpacking mise (2024.11.37) ...
Setting up mise (2024.11.37) ...
Processing triggers for man-db (2.13.0-1) ...

jesse@jimmie:~$ which -a mise
/usr/bin/mise
/bin/mise

jesse@jimmie:~$ ls -lah /usr/bin/mise
-rwxr-xr-x 1 root root 33M Nov 29 17:07 /usr/bin/mise
jesse@jimmie:~$ ls -lah /bin/mise
-rwxr-xr-x 1 root root 33M Nov 29 17:07 /bin/mise

jesse@jimmie:~$ stat /usr/bin/mise
  File: /usr/bin/mise
  Size: 33860912  	Blocks: 66144      IO Block: 4096   regular file
Device: 254,1	Inode: 523361      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-12-02 16:31:03.000000000 -0800
Modify: 2024-11-29 17:07:24.000000000 -0800
Change: 2024-12-02 16:31:03.471830578 -0800
 Birth: 2024-12-02 16:31:03.323830742 -0800

jesse@jimmie:~$ stat /bin/mise
  File: /bin/mise
  Size: 33860912  	Blocks: 66144      IO Block: 4096   regular file
Device: 254,1	Inode: 523361      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-12-02 16:31:03.000000000 -0800
Modify: 2024-11-29 17:07:24.000000000 -0800
Change: 2024-12-02 16:31:03.471830578 -0800
 Birth: 2024-12-02 16:31:03.323830742 -0800
```

**Comment by jdx** [comment]
having 2 binaries is not a problem. Having 2 binaries that are different versions will be a problem.

**Comment by jc00ke** [comment]
> having 2 binaries is not a problem. Having 2 binaries that are different versions will be a problem.

Totally, just wanted to double check that that's expected behavior of the installer. 👌 I'll try rebooting in the morning. Thanks!

**Comment by jc00ke** [comment]
No warning after reboot this morning! :tada:

**Comment by matthutchinson** [comment]
Me too,. a reboot solved it 👍

**Comment by jdx** [comment]
given this is simply a warning that doesn't affect behavior, I don't think it would've been worth it to do more leg-work on this. I've never changed the structure of this before and doubt I'll do so again anytime soon.
