### ISSUE TITLE
`mise tasks run`: add autocompletion

### ISSUE THREAD

**Issue by powerman** [jdx/mise#2903]
Autocompletion already works for `mise run`, but not for `mise tasks run`.

**Comment by powerman** [comment]
@roele Sorry, this wasn't fixed.

```
$ mkdir mise-task-run-completion
$ cd mise-task-run-completion
$ cat >.mise.toml <<'EOF'
[tasks.test]
run = 'echo test'
EOF
$ mise version
2024.11.1 linux-x64 (4927c37 2024-11-05)
$ mise completion zsh >~/.zsh/completions/_mise
$ zsh
$ mise run test   ### mise run <Tab> - works
[test] $ echo test
test
$ mise tasks run   ### mise tasks run <Tab> - nothing
```

**Comment by roele** [comment]
@powerman 
Interesting, just updated `mise` and it seems to work for me in fish shell.

```bash
mise self-update
mise completion fish > ~/.config/fish/completions/mise.fish
cd ~/Downloads/mise-tasks
mise tasks run <TAB>
all    docs       docs:markdown  test:unit
build  docs:html  lint
```

**Comment by powerman** [comment]
Yeah, in bash also works. So, it's zsh issue.

**Comment by roele** [comment]
I'm not a ZSH user but the generated script generally seems to work to some extent once i turn on completions autoloading.

```bash
zsh
autoload -U compinit
compinit
mise completion zsh > mise.zsh
source mise.zsh
mise task run <TAB>
docs   -- html
test   -- unit
all    build  docs   lint
```

**Comment by powerman** [comment]
Hmm. Now it works for me too. Only actual change on my side was an OS reboot. Probably there were some leftovers in zsh config/completions from older mise versions and they somehow break it.

**Comment by hverlin** [comment]
I use `zsh` and can also confirm that autocompletion works for both `mise run` and `mise tasks run` 👍
