### ISSUE TITLE
`tasks.*.run` templates: add shell escaping for `arg()` and `option()`

### ISSUE THREAD

**Issue by powerman** [jdx/mise#2906]
In v2024.11.0 both `arg()` and `option()` returns their values as is. As their values are supposed to be used in a shell command's param they needs to be escaped (using rules depending on current `tasks.*.shell` value).

Partial workaround is to surround them in a single quotes (e.g. `'{{ arg(name="a") }}'`) - but this way we won't be able to use single quote itself in values.

Another but related issue: `arg(var=true)` and `option(var=true)` currently join list of their values using single space and this makes it impossible to correctly split it back to a list of values (which can itself contain spaces, quotes, shell wildcards, etc.). As a result currently it can be used only for list of values which does not contain any spaces/quotes/shell wildcards/etc.

**Comment by jdx** [comment]
> As their values are supposed to be used in a shell command's param

not always, imagine this:

```toml
[tasks.run]
run = 'node <<EOF
console.log('{{arg(name="a")}}');
EOF'
```

I think it would be a mistake to blindly escape everything. We could add an `escape=true` option though.

**Comment by powerman** [comment]
Sure, sometimes you may need unescaped value. But if we had to choose between "always escaped" or "always unescaped" - then it's first! :smile: 

Probably escaping can be done using filter function in templates. This way you can control which arg/option to unescape. Just please-please-please make escaping default behaviour, so that extra filter will mark value as "raw, don't escape it".
