### ISSUE TITLE
Mise does not work if GITHUB_TOKEN is not valid public Github token

### ISSUE THREAD

**Issue by dal13002** [jdx/mise#2910]
**Describe the bug**
mise doesn't work by default when `GITHUB_TOKEN` is set but not a valid token to public github. We use Github Enterprise Server and set the `GITHUB_TOKEN` environment variable on our shell in order to interact with it. When talking to public GIthub (ie pull public repos from github.com) we do not want to use that environment variable but I believe due to this change that token is always send: https://github.com/jdx/mise/pull/2815 . This causes a problem because this is not a valid public Github token and we get 401 Unauthorized when using mise

**To Reproduce**
1. Set `GITHUB_TOKEN` to some non valid public github token (this will replicate setting a token for Github Enterprise Server)
2. Run `mise install bat --verbose`
3. We get an output similar to:
```
DEBUG mise::cli ARGS: mise install bat --verbose
DEBUG mise::config config: ~/.mise.toml
DEBUG mise::toolset install_versions: bat@latest
DEBUG mise::http GET https://api.github.com/repos/sharkdp/bat/releases/tags/0.24.0
DEBUG reqwest::connect starting new connection: https://api.github.com/
DEBUG mise::http GET https://api.github.com/repos/sharkdp/bat/releases/tags/0.24.0 401 Unauthorized
DEBUG mise::backend::ubi Failed to get release for ubi:sharkdp/bat@0.24.0, trying with 'v' prefix: HTTP status client error (401 Unauthorized) for url (https://api.github.com/repos/sharkdp/bat/releases/tags/0.24.0)
DEBUG ubi Parsed --project sharkdp/bat = sharkdp / bat
DEBUG ubi exe name = bat
DEBUG ubi install path = /home/<user>/.local/share/mise/installs/bat/0.24.0/bin/bat
DEBUG ubi adding GitHub token to GitHub requests
DEBUG reqwest::connect starting new connection: https://api.github.com/
DEBUG mise::backend::ubi Failed to install with ubi version 'v0.24.0': HTTP status client error (401 Unauthorized) for url (https://api.github.com/repos/sharkdp/bat/releases/tags/v0.24.0), trying with 'ubi:sharkdp/bat@0.24.0'
DEBUG ubi Parsed --project sharkdp/bat = sharkdp / bat
DEBUG ubi exe name = bat
DEBUG ubi install path = /home/<user>/.local/share/mise/installs/bat/0.24.0/bin/bat
DEBUG ubi adding GitHub token to GitHub requests
DEBUG reqwest::connect starting new connection: https://api.github.com/
Error: 
   0: Failed to install bat@0.24.0
   1: Failed to install with ubi 'ubi:sharkdp/bat@0.24.0': HTTP status client error (401 Unauthorized) for url (https://api.github.com/repos/sharkdp/bat/releases/tags/v0.24.0)
```
4. If we `unset GITHUB_TOKEN`, everything works as expected

**Expected behavior**
Mise should work even if Github Enterprise Server token is set for `GITHUB_TOKEN` 

Mise version:
```
2024.11.0 linux-x64 (eae29db 2024-11-01)
```

**Comment by jdx** [comment]
you could set `MISE_GITHUB_TOKEN` to a valid token. I don't have a great idea for making it work with what to mise is an invalid token.

**Comment by dal13002** [comment]
I feel like MISE should not depend on `GITHUB_TOKEN` environment variables since this is assuming 
1. Token is only for public Github
2. Users want to use their credentials to pull from public repos

Even with this token set, I can natively pull public repos using git (ie if I run `git clone https://github.com/jdx/mise`) so git respects this boundary but MISE doesn't.

In my opinion either: 
1. Mise should not use `GITHUB_TOKEN` directly and only depend on `MISE_GITHUB_TOKEN`
2. Or there should be a way to disable using `GITHUB_TOKEN` credentials when pulling from mise
3. Maybe there is a way to look at the git config / credentials to see what URL it is referencing and only use it if the credentials are for github.com

**Comment by jdx** [comment]
> Mise should not use GITHUB_TOKEN directly and only depend on MISE_GITHUB_TOKEN

Most users do not use GHE. It's common to set `GITHUB_TOKEN` for a set of tools without needing to configure each one independently, so using `GITHUB_TOKEN` makes sense to me and I don't think that should change.

> Or there should be a way to disable using GITHUB_TOKEN credentials when pulling from mise

You can, but it requires setting MISE_GITHUB_TOKEN to a valid token. What we could do is ignore the token if it's empty, so you could set `MISE_GITHUB_TOKEN=` (empty string) in order to get mise to ignore GITHUB_TOKEN.

> Maybe there is a way to look at the git config / credentials to see what URL it is referencing and only use it if the credentials are for github.com

I don't see how this would resolve the issue.

**Comment by dal13002** [comment]
@jdx I tried this out today but it doesn't seem to work:
```
export MISE_GITHUB_TOKEN=''
export GITHUB_TOKEN='invalid_token'

mise install --verbose
DEBUG ARGS: mise install --verbose
DEBUG config: ~/.mise.toml
DEBUG install_versions: fd@latest
INFO  ubi:sharkdp/fd@10.2.0 installing
DEBUG GET https://api.github.com/repos/sharkdp/fd/releases/tags/10.2.0
DEBUG starting new connection: https://api.github.com/
DEBUG GET https://api.github.com/repos/sharkdp/fd/releases/tags/10.2.0 404 Not Found
DEBUG Failed to get release for ubi:sharkdp/fd@10.2.0, trying with 'v' prefix: HTTP status client error (404 Not Found) for url (https://api.github.com/repos/sharkdp/fd/releases/tags/10.2.0)
DEBUG Parsed --project sharkdp/fd = sharkdp / fd
DEBUG exe name = fd
DEBUG install path = /home/<user>/.local/share/mise/installs/fd/10.2.0/bin/fd
DEBUG adding GitHub token to GitHub requests
DEBUG starting new connection: https://api.github.com/
DEBUG Failed to install with ubi version 'v10.2.0': HTTP status client error (401 Unauthorized) for url (https://api.github.com/repos/sharkdp/fd/releases/tags/v10.2.0), trying with 'ubi:sharkdp/fd@10.2.0'
DEBUG Parsed --project sharkdp/fd = sharkdp / fd
DEBUG exe name = fd
DEBUG install path = /home/<user>/.local/share/mise/installs/fd/10.2.0/bin/fd
DEBUG adding GitHub token to GitHub requests
DEBUG starting new connection: https://api.github.com/
Error: 
   0: Failed to install fd@10.2.0
   1: Failed to install with ubi 'ubi:sharkdp/fd@10.2.0': HTTP status client error (401 Unauthorized) for url (https://api.github.com/repos/sharkdp/fd/releases/tags/v10.2.0)

Location:
   src/backend/ubi.rs:123

Version:
   2024.11.6 linux-x64 (ac78120 2024-11-10)
```
Please let me know if I'm doing something wrong
