### ISSUE TITLE
`mise i go` adds redundant PATH entry to non-existing dir

### ISSUE THREAD

**Issue by powerman** [jdx/mise#2928]
**Describe the bug**
`mise i go` adds 2 PATH entries, one is valid but second is both redundant and non-working because points to non-existing dir.

**To Reproduce**
```
$ mise i go
$ mise bin-paths | grep /go/ | xargs ls -ld
ls: cannot access '/home/powerman/.local/share/mise/installs/go/1.23.2/go/bin': No such file or directory
drwxr-xr-x 2 powerman powerman 4096 Nov  5 09:55 /home/powerman/.local/share/mise/installs/go/1.23.2/bin
```

**Expected behavior**
`~/.local/share/mise/installs/go/1.23.2/go/bin` shouldn't be added to PATH.

**Comment by jdx** [comment]
seems to be it should be there since `go install` will install CLIs to that directory. Not existing shouldn't cause any problems.

**Comment by powerman** [comment]
> seems to be it should be there since `go install` will install CLIs to that directory.

No, `go install` is not configured to use that non-existing dir. Currently it's configured to use a directory with `go` binary itself:

```
$ which go
/home/powerman/.local/share/mise/installs/go/1.23.2/bin/go
$ go env GOBIN
/home/powerman/.local/share/mise/installs/go/1.23.2/bin
```

See also about current GOBIN: https://github.com/jdx/mise/discussions/2929
