### ISSUE TITLE
Document `min_version` config setting

### ISSUE THREAD

**Issue by glasser** [jdx/mise#2933]
If you want to take advantage of a newish feature of mise in a shared project, it would be nice to have a way to specify a minimum mise version and at least get a warning or maybe error if it isn't matched. (Having mise actually control its own version seems overkill, but a warning would be nice.)

**Comment by jdx** [comment]
we already have this: https://github.com/jdx/mise/blob/e13543aa938f0c64709c9b0bcf72c48084353f9d/.mise.toml#L3

**Comment by glasser** [comment]
Ah cool — is it documented? I couldn't find it when I looked at https://mise.jdx.dev/configuration.html and https://mise.jdx.dev/configuration/settings.html

**Comment by hverlin** [comment]
Seems to only be in the json schema: https://github.com/jdx/mise/blob/e13543aa938f0c64709c9b0bcf72c48084353f9d/schema/mise.json#L732-L735
