### ISSUE TITLE
Is it possible to `cargo install --bin`?

### ISSUE THREAD

**Issue by zx8** [jdx/mise#2963]
Example:

```
$ mise exec cargo:solana-labs/solana@tag:v1.18.26 -- solana-keygen
```

Errors with:

> `error: multiple packages with binaries found: gen-headers, gen-syscall-list, proto, rbpf-cli, solana-accounts-bench, solana-accounts-cluster-bench, solana-banking-bench, solana-bench-streamer, solana-bench-tps, solana-cargo-build-bpf, solana-cargo-build-sbf, solana-cargo-registry, solana-cargo-test-bpf, solana-cargo-test-sbf, solana-cli, solana-dos, solana-faucet, solana-genesis, solana-gossip, solana-install, solana-keygen, solana-ledger-tool, solana-log-analyzer, solana-merkle-root-bench, solana-net-shaper, solana-net-utils, solana-poh-bench, solana-remote-wallet, solana-stake-accounts, solana-store-tool, solana-tokens, solana-transaction-dos, solana-upload-perf, solana-validator, solana-watchtower, solana-zk-keygen. When installing a git repository, cargo will always search the entire repo for any Cargo.toml.`

How can I specify that I want to install `solana-keygen` specifically?

**Comment by jdx** [comment]
this could be added as a tool option in the cargo backend
