### ISSUE TITLE
Use any version available instead of throwing an error

### ISSUE THREAD

**Issue by svipas** [jdx/mise#2968]
So my problem currently with mise is that we have in our project `.node-version` and `.ruby-version` and instead of using available versions mise throws an error saying that `mise ERROR Tool not installed for shim: node` even though it is installed is just that `.node-version` contains `16`, but I have `20` installed.

My feature request or question if that is already possible: how to still have warning about it, but fallback to currently installed version even though it might not match the one defined in the file?

```
mise ERROR Tool not installed for shim: node 
Missing tool version: node@16.20.2 
Install all missing tools with: mise install 
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

So instead of an error here, I would love if mise still uses Node version which is `20` (I have installed), but gave me warning that it fallback and saying that project expects `16` as defined in `.node-version`.

**mise ls**
```
Tool    Version            Config Source                                Requested
bun     1.1.33             ~/.config/mise/config.toml                   latest   
go      1.23.2             ~/.config/mise/config.toml                   latest   
node    16.20.2 (missing)  ~/Developer/mobile-application/.node-version 16       
node    20.18.0                                                                  
python  3.13.0             ~/.config/mise/config.toml                   latest   
ruby    2.7.5              ~/Developer/mobile-application/.ruby-version 2.7.5 
```

**Comment by jdx** [comment]
I think this is a bad idea. You have a configuration file specifying a version, that should be the version that gets used. You can ignore idiomatic files if you want.

**Comment by svipas** [comment]
How I can then ignore it in mise?
