### ISSUE TITLE
How to get started with custom backend development?

### ISSUE THREAD

**Issue by shinebayar-g** [jdx/mise#3061]
I want to write a backend (?) for tools that doesn't exist in the registry. Is there any docs around it?

**Comment by syhol** [comment]
Are you sure you want to write a backend? These normally allow access to a whole repository of different tools, e.g.
- npm enables the installation of tools from the npm registry
- pipx enables the installation of tools from the pypi registry
- ubi enables the installation of binaries from github releases
- asdf enables the installation of tools from asdf plugins

If its just a single tool you want to use with mise, then you have some options:
- If it can be installed from a github release:
  - You might be able to install it with ubi:
    - `mise use ubi:the-github-user/the-github-repo` e.g. `mise use ubi:astral-sh/ruff`?
  - Or you add it to the aqua repository, aqua is experimental in mise right now but a very promising development
    - docs here: https://aquaproj.github.io/docs/products/aqua-registry/contributing
- Else you can write an asdf or vfox plugin for it:
  - https://asdf-vm.com/plugins/create.html
  - https://vfox.lhan.me/plugins/create/howto.html

If you truly do want to write a backend, there are no docs for that and it would be a much more complex task.

**Comment by shinebayar-g** [comment]
Thanks for the answer. I should've probably explain myself better. Classic case of xy problem here.
I'm trying to do install binaries from github releases. I want it to be generic. It seems ubi is exactly made for that.

I tested it on [kind](https://github.com/kubernetes-sigs/kind/releases/tag/v0.25.0) and it works great.

`mise use -g ubi:kubernetes-sigs/kind`

However I couldn't figure out how to use it on [cilium-cli](https://github.com/cilium/cilium-cli/releases/tag/v0.16.20)

```sh
❯ mise use -g ubi:cilium/cilium-cli
mise ERROR failed to install ubi:cilium/cilium-cli@0.16.20
mise ERROR Failed to install with ubi 'ubi:cilium/cilium-cli@0.16.20': could not find any files named cilium-cli in the downloaded tarball
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

Then I tried below settings in my `~/.config/mise/config.toml` config file.

Test 1

```sh
[tools]
"ubi:cilium/cilium-cli" = { exe = "cilium" }

❯ mise use -g ubi:cilium/cilium-cli
mise ERROR failed to install ubi:cilium/cilium-cli@0.16.20
mise ERROR Failed to install with ubi 'ubi:cilium/cilium-cli@0.16.20': could not find any files named cilium-cli in the downloaded tarball
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

Test 2

```sh
[tools]
"ubi:cilium/cilium-cli" = { matching = "cilium-linux-amd64" }

❯ mise use -g ubi:cilium/cilium-cli
mise ERROR failed to install ubi:cilium/cilium-cli@0.16.20
mise ERROR Failed to install with ubi 'ubi:cilium/cilium-cli@0.16.20': could not find any files named cilium-cli in the downloaded tarball
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

Version

```sh
❯ mise version
2024.11.15 linux-x64 (d3d8dc0 2024-11-16)
```

**Comment by jdx** [comment]
config seems right, might be a bug

**Comment by shinebayar-g** [comment]
Gotcha. I got it working somehow after deleting my backup binary. I had my old cilium cli backed up in `/usr/local/bin/cilium.backup` path and noticed that `mise ls` was showing the version as `system` somehow.. Deleted that and opened a new shell somehow it was gone.

**Comment by syhol** [comment]
I think this was partially mitigated by https://github.com/jdx/mise/pull/3076

@shinebayar-g I can't reproduce the condition you described above but if you see the following I ran commands I ran today:
```console
❯ echo '
[tools]
"ubi:cilium/cilium-cli" = { version = "latest", exe = "cilium" }
' >mise.toml

❯ mise install
mise Installed binary into /Users/syhol/.local/share/mise/installs/ubi-cilium-cilium-cli/0.16.20/bin/cilium
mise ubi:cilium/cilium-cli@0.16.20 ✓ installed

❯ cilium version
cilium-cli: v0.16.20 compiled with go1.23.2 on darwin/arm64
cilium image (default): v1.16.3
cilium image (stable): v1.16.4
cilium image (running): REDACTED

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```

You can see it works as expected. @shinebayar-g are you happy to close the ticket?

**Comment by shinebayar-g** [comment]
Sure. Thanks for the follow up.
