### ISSUE TITLE
Issues / Warnings / Unexpected Behavior During `asdf` Plugin Pull via SSH

### ISSUE THREAD

**Issue by markussiebert** [jdx/mise#3099]
**Describe the bug**
When attempting to pull `asdf` plugins from a non-public repository via SSH, we encounter issues, warnings, and unexpected behavior. Below is a detailed description of the problems faced.

**To Reproduce**

mise plugins install my-plugin git@my.git.host:asdf-plugins/my-plugin.git

1. **With SSH Agent Running:**
    - The operation generally works but issues a warning:
      ```
      mise WARN  git clone failed: authentication required but no callback set; class=Ssh (23); code=Auth (-16)
      ```
    - In this scenario, there was an SSH agent running that had the password for the SSH key used for pulling.

2. **Without SSH Agent Running:**
    - There is an expectation to enter the password manually.
    - However, there is no password prompt displayed. Instead the warning the following line shows up:
      ```
      mise plugin:my-plugin cloning git@my.git.host:asdf-plugins/my-plugin.git
      ```
    - If the password isn't entered and you hit enter, the password prompt appears for a brief moment before the operation times out.
    - If you type in the correct password, everything works (apart from the described behaviour)

**Expected behavior**
There should be a prompt to type in password - or no errors if everything is fine ..

**`mise doctor` output**

```text
version: 2024.11.9 macos-arm64 (2024-11-13)
activated: yes
shims_on_path: no
```

**Additional context**
Add any other context about the problem here. Consider running mise with `--debug` or `--trace` for extra debug info.

**Comment by jdx** [comment]
you can disable the libgit2 setting

**Comment by markussiebert** [comment]
setting 

```
export MISE_LIBGIT2=false
```

in my .zshrc doesn't change the behaviour
