### ISSUE TITLE
Shebang in `run=` has no effect, but using it in example creates impression it will work:

### ISSUE THREAD

**Issue by jdx** [jdx/mise#3174]
Shebang in `run=` has no effect, but using it in example creates impression it will work:

https://github.com/jdx/mise/blob/36a19f87b80aafb15f33dd818f3a4b4a0277c295/docs/tasks/toml-tasks.md?plain=1#L33-L36

_Originally posted by @powerman in https://github.com/jdx/mise/issues/2873#issuecomment-2453996738_

**Comment by jdx** [comment]
this should actually function, what it should do is set the `shell` property

**Comment by powerman** [comment]
AFAIR I've tried something more complicated than just mention concrete shell - probably I've tried to run `usage` in shebang and this won't work.

**Comment by jdx** [comment]
you can use [`#!/usr/bin/env -S`](https://mise.jdx.dev/tips-and-tricks.html#shebang) for that

**Comment by powerman** [comment]
Yeah, that's what I've tried to do AFAIR, and it didn't worked inside `run=`.
