### ISSUE TITLE
pipx/uv python upgrade problem

### ISSUE THREAD

**Issue by jdx** [jdx/mise#3210]
ok so to start this is maybe a terrible idea. However it might also be the seed of something useful.

I've been thinking about the pipx/uv python upgrade problem. Essentially that if you do this then there are problems:

```sh-session
$ mise use python@3.12.0
$ mise use pipx:black
$ mise use python@3.12.1
$ mise rm python@3.12.0
$ mise x -- black # fails
```

The reason being is that when you install `pipx:black` it uses the current active python version provided by mise (or system python if no python is installed). When you later uninstall 3.12.0, the pipx venv used to point to 3.12.0 and doesn't get updated to point to 3.12.1.

I put a basic patch in specific for `mise up` that does address this. If a python version is upgraded, mise runs `pipx reinstall` on all pipx tools installed however this introduced new problems.

* it doesn't work on uv (uv doesn't have a reinstall command but I think it's the same as removing/installing)
* it is very slow even with a single pipx tool, but this runs on all version of all _installed_ tools which for some users I bet could be into the hundreds.
* it doesn't work in situations like above where the python is being installed/uninstalled—it only runs on `mise up`.

I spoke with @charliermarsh a bit about this and he said in homebrew what they do is symlink to the python minor version in the venvs so that when python is upgraded as long as the minor version doesn't change the symlinks just point to the new micro version. I believe he said this is definitely hacky and probably doesn't work with all tools but in general it's safe to do this across micro versions. Symlinks can't work for us though the way things are today because the python version should actually be different based on which directory you're in. Imagine running mise in 2 terminal tabs in different directories—we have to pick one python to use.

My thinking here is that we should centralize the python version used for pipx specifically to avoid this problem and be able to create a symlink like this. The central version could be bumped on mise releases and mise could perform a migration step when it first launches that either updates the central python version the symlink points to or if the minor version is bumped would perform the expensive 'reinstall-all' step.

The obvious downside of this approach is you would lose the ability to specify which version of python to run tools with. Perhaps that could be a global setting like `MISE_PIPX_PYTHON_VERSION` or something. Though that would still be global configuration so you wouldn't be able to do it on a tool itself.

For that, I propose a tool option:

```toml
[tools]
"pipx:black" = { version = "latest", python = "3.12" }
```

With all of that in place, I think it would address all the issues I can think of. However it's a lot to build and it makes mise not just more complex under the hood but more complex to use. Arguably the current state of just using the python version that was there when the tool was installed is simpler and easier to understand even given this issue.

**Comment by jdx** [comment]
I just put support in for `mise i -f pipx:*` which will reinstall all pipx tools. I think having users manually call this alongside the `mise up` hack put in is probably sufficient for now

**Comment by hverlin** [comment]
I wish there was a way to do this for `npm` packages, at least. If I install a global package with `mise use -g npm:...`, I can't use it in repos where node is on a different version.

Also mentioned here: https://github.com/jdx/mise/issues/3152#issuecomment-2495218065

**Comment by jdx** [comment]
I'm going to close this for now because I think `mise i -f pipx:*` should be acceptable. I think doing more here is just asking for too much complexity.
