### ISSUE TITLE
Registry backend precedence documentation

### ISSUE THREAD

**Issue by scop** [jdx/mise#3222]
Reading https://mise.jdx.dev/dev-tools/backends/aqua.html, I get a picture that the ubi backend would be the preferred one, followed by aqua.

However, all entries in https://mise.jdx.dev/registry.html (as well as `mise registry`) have aqua _before_ ubi.

I don't know if the order of backends output in registry is also the order in which they are preferred in case just the tool name without a backend is specified, but I get a feeling this is how it is.

This raises a few thoughts / RFE's:
- Could the backend precedence be documented somewhere? If it already is, could it be made more prominent so I would have caught it :) (I accept I may have just missed it)
- The precedence between aqua and ubi in the registry (if I guessed it right) does not seem consistent with https://mise.jdx.dev/dev-tools/backends/aqua.html -- perhaps that and https://mise.jdx.dev/dev-tools/backends/ubi.html should be reworded to convey that aqua is actually the preferred one (if it is).

As a bonus item, I don't know if ubi supports verifying downloads against checksums. aqua does, so in that sense, if ubi does not, featurewise, perhaps aqua should be the preferred default (unless it already is).

**Comment by jdx** [comment]
yeah I've switched to preferring aqua, however this isn't a global configuration, it's specified on a tool-by-tool basis so there may be some reason we want to prefer ubi to aqua on a specific tool

**Comment by StingRayZA** [comment]
Additionally, the `asdf` page mentions that `asdf` is used by default.
> asdf is the original backend for mise. It's the default if no backend is specified
