### ISSUE TITLE
Java Plugin List Issue

### ISSUE THREAD

**Issue by ImmortalFan** [jdx/mise#3228]
<img width="414" alt="image" src="https://github.com/user-attachments/assets/7aef29be-d30c-4833-bb71-a4b6267213df">

The list of Java plugins has been reduced to OpenJDK only, and other vendors' OpenJDKs are no longer available. Is this by design or a bug? I am using the latest version.

**Comment by jdx** [comment]
I'm seeing all the versions. Do you have a java plugin installed?

**Comment by ImmortalFan** [comment]
> I'm seeing all the versions. Do you have a java plugin installed?

<img width="275" alt="image" src="https://github.com/user-attachments/assets/ad184490-48ac-4a51-9511-7f259f900995">

I have the Java plugin here, and the Java plugin seems to be a core plugin that doesn't need to be installed.

**Comment by jdx** [comment]
those are not core plugins, uninstall your java plugin

**Comment by ImmortalFan** [comment]
> those are not core plugins, uninstall your java plugin

I have uninstalled the Java plugin, but it doesn't seem to have made any difference.

**Comment by jdx** [comment]
what is the output of `mise dr`? try the following:

```
mise cache clear
mise plugins rm java
mise install java
```

**Comment by ImmortalFan** [comment]
> ```
> mise install java
> ```

Thank you very much,it’s  fixed now.
