### ISSUE TITLE
Exclude directories from activating mise tools

### ISSUE THREAD

**Issue by dParikesit** [jdx/mise#3233]
Hello,

Sometimes I use nix with direnv (hence having .envrc) and uv (.python-version) in my projects. On those projects, I want mise to not get activated. 

Ideas on how it can be implemented
- Add a setting to exclude directories (or maybe add it in the global config?)
- Add a .mise.toml in the dir I want to exclude that tell mise to ignore this dir (I'm fine with adding a .gitignore item)
- Add a setting that tell mise to ignore .envrc and .python-version (and any config other than mise-specific config)

An optional feature that is nice to have is allowing mise tasks to run but prevent mise tools to get activated in the dir

Thanks!

**Comment by jdx** [comment]
`mise trust --ignore` or `MISE_IGNORE_CONFIG_PATHS`

**Comment by dParikesit** [comment]
What is it supposed to do? When I use `mise trust --ignore` or `MISE_IGNORE_CONFIG_PATHS`, I still have mise in my path. I also still get the warning `mise WARN  missing: python@3.13.0` for my uv project

**Comment by jdx** [comment]
it sounds like he wants to remove mise entirely from PATH, idk why you'd want to do that
