### ISSUE TITLE
Update has broken Zed's default executables

### ISSUE THREAD

**Issue by markbrown4** [jdx/mise#3276]
**Describe the bug**

[Zed](https://zed.dev/download)'s default formatter Prettier no longer runs for me.
I've tracked it down to Mise activation in `~/.zshrc`.

When mise is activated and I open a `.tsx` file in Zed, it starts up multiple mise processes, the fans start spinning and the formatters time out.

**To Reproduce**

Activate Mise in `~/.zshrc`

```
eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(mise activate zsh --shims)"
```

1. Download and install the Zed text editor:  https://zed.dev/download
2. Launch Zed and make a new text file `test.tsx`
3. Enter `function test() {alert("a")}` and save file

**Expected behavior**

Zed's default settings for `.tsx` files are to format with Prettier.

```tsx
function test() {
  alert("a");
}
```

Prettier is installed to `~/Library/Application Support/Zed/prettier`.
It's not clear to me _why_ these are triggering these `mise` processes or what is hanging.

Can you shed any light on this?

**Comment by mise-en-dev** [comment]
I'm not going to debug it for you but you can setup file logging as described [here](https://mise.jdx.dev/troubleshooting.html#mise-is-failing-or-not-working-right) to see what mise is doing

**Comment by markbrown4** [comment]
It's related to shims somehow.  This works as expected.

```diff
- eval "$(mise activate zsh)"
+ eval "$(mise activate zsh --shims)"
```

I've had one issue after another with shims the last two weeks, will avoid it.

**Comment by jdx** [comment]
while I don't have logs to confirm I think https://github.com/jdx/mise/commit/35d31a1baf96fe6f0e764e26228c1b03ba24ddce may have fixed this
