### ISSUE TITLE
mise hook_env and ignored_config_paths

### ISSUE THREAD

**Issue by cpence** [jdx/mise#3289]
At the moment, `mise hook-env` does not respect `settings.ignored_config_paths`, so it is impossible to prevent mise from automatically running this command in a shell in which mise is activated.

This is problematic if mise runs slowly in a particular directory on your machine -- for example, because that directory is mounted over sshfs.

**To Reproduce**
Mount a directory over sshfs at, say, `/mnt/work`. Then:

```
 ~  mise doctor | grep ignored
  ignored_config_paths  ["/mnt/"] ~/.config/mise/config.toml
 ~  cd /mnt/work
 /m/work  time mise hook-env -s fish

________________________________________________________
Executed in  614.13 millis    fish           external
   usr time   25.13 millis    0.00 millis   25.13 millis
   sys time   22.47 millis    2.15 millis   20.32 millis

 /m/work  
```

**Expected behavior**
Because the `/mnt` path is ignored, `mise hook-env` should also quick-exit, rather than taking 600ms to show my prompt.

**`mise doctor` output**

```text
version: 2024.11.36 linux-x64 (c4bc235 2024-11-29)
activated: yes
shims_on_path: no

build_info:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS
  Built: Fri, 29 Nov 2024 13:02:17 +0000
  Rust Version: rustc 1.82.0 (f6e511eec 2024-10-15) (Arch Linux rust 1:1.82.0-2)
  Profile: release

shell:
  /usr/bin/fish
  fish, version 3.7.1

dirs:
  cache: ~/.cache/mise
  config: ~/.config/mise
  data: ~/.local/share/mise
  shims: ~/.local/share/mise/shims
  state: ~/.local/state/mise

config_files:
  ~/.config/mise/config.toml

backends:
  aqua
  asdf
  cargo
  core
  gem
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:

toolset:
  core:node@23.3.0
  core:python@3.13.0
  core:ruby@3.3.6
  npm:prettier@3.4.1
  pipx:black@24.10.0
  pipx:cpplint@2.0.0
  pipx:hatch@1.13.0
  pipx:isort@5.13.2
  pipx:keyring@25.5.0
  pipx:pypaperbot@1.4.0
  pipx:pyright@1.1.389

env_vars:
  MISE_SHELL=fish

settings:
  experimental          true      ~/.config/mise/config.toml
  ignored_config_paths  ["/mnt/"] ~/.config/mise/config.toml

No problems found
```

**Comment by cpence** [comment]
I just tried setting the environment variable `MISE_IGNORED_CONFIG_PATHS` to `/mnt` and `mise hook-env -s fish` unfortunately still takes ~600ms in that folder.

**Comment by jdx** [comment]
oh sorry, I misunderstood. The config does work for what it's designed to do: ignore any potential config files, however mise is still looking for files in those directories where it won't find anything because it's ignored.

I think this function needs to be updated to not be looking at ignored paths:

https://github.com/jdx/mise/blob/65694784bc1a407b34f51df6b6376e5ae23db85c/src/config/mod.rs#L764-L785

**Comment by cpence** [comment]
Awesome, thanks so much! :tada:
