### ISSUE TITLE
Include in "deb-get" index

### ISSUE THREAD

**Issue by Entze** [jdx/mise#3291]
[deb-get](https://github.com/wimpysworld/deb-get)  provides `apt-get` functionality for .debs published in 3rd party repositories or via direct download.

According to [their README](https://github.com/wimpysworld/deb-get?tab=readme-ov-file#adding-software) and [CONTRIBUTING](https://github.com/wimpysworld/deb-get/blob/main/01-main/CONTRIBUTING.md) it seems like the mise deb repository should be good to go.

This issue is regarding discussion whether this is wanted, and who would maintain the package on this index.

**Comment by jdx** [comment]
I think I'm happy with the current deb builds for now
