### ISSUE TITLE
Unable to download gpg keys from server behind proxy

### ISSUE THREAD

**Issue by J-PC** [jdx/mise#3293]
Hello,

I figured a problem downloading node package on a corporate proxy behind a firewall.
The debug mode shows that downloading the tarball is not a problem but it uses gpg cli to download gpg keys from a public server.
The http_proxy is set but it is not honored by the gpg cli (no --keyserver-options with http-proxy parameter).

Eventually, this a problem related to gpg.

I'm unable to download manually the keys required adding the option "--keyserver-options http-proxy=$http_proxy"
I downloaded the keys with curl piping a gpg --import command.

I expected the "mise use" command to work as the keys where present but it still failed trying to download keys.

**To Reproduce**

To reproduce the problem, one just needs to sit behind a firewall and downloading for example node with `mise install node` which uses the core backend.

**Expected behavior**

I expected mise to get the gpg keys needed and the package installed

**`mise doctor` output**

```text
version: 2024.11.36 linux-x64 (0461143 2024-11-29)
activated: yes
shims_on_path: no

build_info:
  Target: x86_64-unknown-linux-musl
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Fri, 29 Nov 2024 10:31:55 +0000
  Rust Version: rustc 1.82.0 (f6e511eec 2024-10-15)
  Profile: release

shell:
  /bin/bash
  GNU bash, version 5.2.26(1)-release (x86_64-redhat-linux-gnu)
  Copyright (C) 2022 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

  This is free software; you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.

dirs:
  cache: ~/.cache/mise
  config: ~/.config/mise
  data: ~/.local/share/mise
  shims: ~/.local/share/mise/shims
  state: ~/.local/state/mise

config_files:
  ~/.config/mise/config.toml

backends:
  aqua
  asdf
  cargo
  core
  gem
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:

toolset:
  ubi:google/go-containerregistry[exe=crane]@0.20.2
  ubi:jdx/usage@1.3.3

env_vars:
  MISE_SHELL=bash

settings:

No problems found
```

**Additional context**

Here the debug output of the command :

```
DEBUG ARGS: /home/jorge/.local/bin/mise use --verbose nodejs
DEBUG config: ~/.config/mise/config.toml
DEBUG install_some_versions: node@latest
INFO  node@23.3.0     install
INFO  node@23.3.0     download node-v23.3.0-linux-x64.tar.gz
DEBUG GET Downloading https://nodejs.org/dist/v23.3.0/node-v23.3.0-linux-x64.tar.gz to ~/.local/share/mise/downloads/node/23.3.0/node-v23.3.0-linux-x64.tar.gz
DEBUG GET https://nodejs.org/dist/v23.3.0/node-v23.3.0-linux-x64.tar.gz
DEBUG starting new connection: https://nodejs.org/
DEBUG proxy(http://localhost:3128) intercepts 'https://nodejs.org/'
DEBUG GET https://nodejs.org/dist/v23.3.0/node-v23.3.0-linux-x64.tar.gz 200 OK
DEBUG GET Downloading https://nodejs.org/dist/v23.3.0/SHASUMS256.txt to ~/.local/share/mise/downloads/node/23.3.0/SHASUMS256.txt
DEBUG GET https://nodejs.org/dist/v23.3.0/SHASUMS256.txt
DEBUG GET https://nodejs.org/dist/v23.3.0/SHASUMS256.txt 200 OK
DEBUG GET Downloading https://nodejs.org/dist/v23.3.0/SHASUMS256.txt.sig to ~/.local/share/mise/downloads/node/23.3.0/SHASUMS256.asc
DEBUG GET https://nodejs.org/dist/v23.3.0/SHASUMS256.txt.sig
DEBUG GET https://nodejs.org/dist/v23.3.0/SHASUMS256.txt.sig 200 OK
DEBUG $ gpg --keyserver hkps://keys.openpgp.org --recv-keys --quiet C0D6248439F1D5604AAFFB4021D900FFDB233756 DD792F5973C6DE52C432CBDAC77ABFA00DDBF2B7 CC68F5A3106FF448322E48ED27F5E38D5B0A215F 8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600 890C08DB8579162FEE0DF9DB8BEAB4DFCF555EF4 C82FA3AE1CBEDC6BE46B9360C43CEC45C17AB93C 108F52B48DB57BB0CC439B2997B01419BD92F80A A363A499291CBBC940DD62E41F10027AF002F8B0
gpg: keyserver receive failed: No keyserver available
ERROR gpg failed
Error:
   0: failed to install core:node@23.3.0
   1: gpg exited with non-zero status: exit code 2

Location:
   src/cmd.rs:423

Version:
   2024.11.36 linux-x64 (0461143 2024-11-29)

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by jdx** [comment]
you can disable gpg in settings

**Comment by jdx** [comment]
I'm certain you're capable of finding that in the docs yourself

**Comment by dtsdwarak** [comment]
This should do it.

```
$ mise settings node.gpg_verify=false
```

Ref -
https://mise.jdx.dev/configuration/settings.html#node.gpg_verify

**Comment by farzadmf** [comment]
Question: aren't we giving up on security by disabling gpg? Is there a "better" way to fix this?

**Comment by jdx** [comment]
if you look at the pull requests tab you'll see that I have been working on this

**Comment by farzadmf** [comment]
@jdx GREAT! Sorry, didn't check that; thanks for letting me know.

I REALLY appreciate your work on this tool. I switched to it a while back from `asdf`, but hadn't been "using" it per se. But recently started setting it up because I got a new laptop, and OMG, what a lovely experience!

And you being SUPER responsive is just the icing on the cake! 🎉

**Comment by farzadmf** [comment]
@jdx quick question: now that the PR is merged, I tried to "undo" `mise settings node.gpg_verify=false`, and I thought it would be `mise settings remove node.gpg_verify`.

But, when I run the command and `cat ~/.config/mise/config.toml`, I still see:
```toml
# ...
[settings.node]
gpg_verify = false
```

If I do `mise settings remove node`, it does remove that section, but that seems to be too destructive to remove the whole section when i need to remove only one key.

Of course, not a big deal, and I can even edit the file by hand, but I was wondering if I'm missing something (most probably), and if this is the intended behavior
