### ISSUE TITLE
Musl mise binary will install musl-linked static python

### ISSUE THREAD

**Issue by janimo** [jdx/mise#3295]
With the recent change to install musl binaries we have the same issue as #1716
Statically built python will not work well with venv among other problems.

**Comment by jdx** [comment]
ah right I knew there was a reason we didn't want to do that, changing it back

**Comment by zanieb** [comment]
@jdx a friendly heads up that we now support dynamically-linked musl Python distributions https://github.com/astral-sh/python-build-standalone/pull/541
