### ISSUE TITLE
mise settings improvements

### ISSUE THREAD

**Issue by hverlin** [jdx/mise#3301]
`mise settings` has been improved in the latest releases and now offers `json` output. Thank you!

```shell
❯ mise settings --json                    
{
  "disable_backends": "[\"java\"]",
  "experimental": true
}

❯ mise settings --toml                    
disable_backends = ["java"]
experimental = true

❯ mise settings                           
Key               Value    Source                    
disable_backends  ["java"] ~/.config/mise/config.toml
experimental      true     ~/.config/mise/config.toml
```

Would it be possible to make the following changes? (I can create PRs)
- `toml` and/or `json` output could include the source of the settings, like it does for the table output (I have a similar request for `mise env --json` in https://github.com/jdx/mise/issues/3012)
```json
{
  "experimental": { "value": true, "source": "~/.config/mise/config.toml" }
}
```
- arrays are shown as strings in the json output, but not in the toml output. I believe this might be a bug?

For context, I am trying to display them in https://github.com/hverlin/mise-vscode:
<img width="1502" alt="image" src="https://github.com/user-attachments/assets/ff92022e-a85e-4857-a3f7-55d1863600ce">

I have also noticed that `python.default_packages_file` does not show in the default output, even it's different from the default value. I might use the default output from `mise` going forward, but just curious why isn't it shown?

**Comment by jdx** [comment]
> arrays are shown as strings in the json output, but not in the toml output. I believe this might be a bug?

looks like escape characters are added to the json output that shouldn't be there. I think in json we should return arrays but in toml it should probably return one string for the array delimited by how the settings get read in. Otherwise you wouldn't be able to take the output from this command and use it as input into another config file.

> toml and/or json output could include the source of the settings, like it does for the table output (I have a similar request for mise env --json in https://github.com/jdx/mise/issues/3012)

I considered doing that in the initial version but the output is a lot less friendly IMO. I think we should add this behind a `--sources` flag for json and toml

**Comment by hverlin** [comment]
> looks like escape characters are added to the json output that shouldn't be there. I think in json we should return arrays but in toml it should probably return one string for the array delimited by how the settings get read in. Otherwise you wouldn't be able to take the output from this command and use it as input into another config file.

So the `toml` output stays as is. However, I can update the json output to:
```json
{
  "disable_backends": ["java"],
  "experimental": true
}
```

I agree that the `toml` with sources might not be so useful. What about adding an extra output format: `--json-with-sources` for both `mise settings` and `mise env`?

```shell
mise settings ls --json-with-sources
{
  "disable_backends": { "value": ["java"], "source": "~/.config/mise/config.toml" },
  "experimental": { "value": true, "source": "~/.config/mise/config.toml" }
}
```

**Comment by jdx** [comment]
I think that's a good idea. Makes it clear it's only for json
