### ISSUE TITLE
`mise generate bootstrap`

### ISSUE THREAD

**Issue by jdx** [jdx/mise#3306]
a command that basically does `curl https://mise.run > run-with-mise.sh && echo 'exec mise x -- "$@"' >> run-with-mise.sh` though we should think about how this is used a bit in a project and if there is anything else it could/should do

**Comment by hverlin** [comment]
Could it generate something like this? If `mise` is already present, use it, otherwise install it.

```sh
#!/bin/sh
set -eu

find_mise() {
    if command -v mise >/dev/null 2>&1; then
        command -v mise
        return 0
    fi

    if [ -x "$HOME/.local/bin/mise" ]; then
        echo "$HOME/.local/bin/mise"
        return 0
    fi

    return 1
}

MISE_BIN=$(find_mise || true)

if [ -z "${MISE_BIN:-}" ]; then
    if ! command -v curl >/dev/null 2>&1; then
        echo "Error: curl is not installed"
        exit 1
    fi

    TMP_DIR=$(mktemp -d)
    trap 'rm -rf "$TMP_DIR"' EXIT

    if ! curl -fsSL https://mise.run > "$TMP_DIR/mise.sh"; then
        echo "Error: Failed to download mise installer"
        exit 1
    fi

    if ! sh "$TMP_DIR/mise.sh"; then
        echo "Error: mise installation failed"
        exit 1
    fi

    MISE_BIN=$(find_mise)
    if [ -n "$MISE_BIN" ]; then
        echo "mise installed successfully"
        "$MISE_BIN" trust
    else
        echo "Error: mise installation succeeded but mise not found"
        exit 1
    fi
fi

exec "$MISE_BIN" "$@"
```

This way:
```sh
./mise.sh run <task>
```
This could also contain the whole content of `https://mise.run` to set a strict version.

---

The way `gradlew` does it is that it creates a local `.gradle` directory with a specific version of `gradle`. I believe this could also be done by setting the following variables so it installs `mise` in `.mise/`  with the exact version. 
```
MISE_VERSION=...
MISE_INSTALL_PATH=...
MISE_DATA_DIR=...
MISE_STATE_DIR=...
MISE_CACHE_DIR=...
MISE_CONFIG_DIR=...
``` 
I am not sure how well this would work with `mise` as things might conflict if `./mise.sh` is called while `mise` is already activated, for example.
I think relying on a global instance of `mise` might be good enough for it to work in CI at least?

**Comment by jdx** [comment]
I don't build mise in a way where I would expect people to be running local versions like that. This got mentioned in #3364 too but I don't see a compelling reason why mise should start being designed this way. For a start, mise is forwards-compatible (with respect to its internal structure) but not backwards-compatible. If you switch to an old version of mise things may break or at least be missing. I suspect this would be quite challenging since until gradle mise lasts for a shell session, it's not just a command you execute in a directory like gradle. What should mise do once you leave the project directory?

**Comment by hverlin** [comment]
yeah, using `MISE_VERSION` might only make sense in CI

**Comment by jdx** [comment]
back to your original question though, yes this should be idempotent and not install if it's already there. That makes sense for mise.run because if someone's running that they may have a corrupt/broken install and it's best just to ignore what may or may not be there, but a bootstrapping script should reuse what's existing since it would be called in normal execution.

**Comment by syhol** [comment]
Created a little wrapper for tasks and tools that auto-installs mise when not present: https://github.com/jdx/mise/discussions/2041#discussioncomment-11525427

**Comment by jdx** [comment]
I think this should involve 2 separate commands kind of based on what @syhol demonstrated. I'm thinking we have `mise g bootstrap` which would generate a shim for calling/fetching mise that could go into `bin/mise`. Second, we have a command like `mise g task-stubs` that would build a stub for each task in `bin/{task_id}` that calls `bin/mise run {task_id}`

**Comment by syhol** [comment]
> Maybe we could have a --localize flag that would put all the config/cache/data dirs into a .mise inside the project.

I thought about this too, but after playing with those directory env vars I've become a bit scared of them. It took me 4 attempts to undo it when I set them in my toml env. But if we keep it in the shim it could work well.

The flag would be on the generator subcommand right?

**Comment by jdx** [comment]
Yeah

**Comment by dudicoco** [comment]
Here's how i'm currently handling mise bootstrapping:

`install_mise.sh`
```sh
#!/usr/bin/env bash

set -eo pipefail

# mise_installer_version=""
mise_version="v2024.12.17"
install_path="$HOME/.local/bin/mise"

install() {
  export MISE_VERSION=$mise_version
  # TODO: install from github releases
  curl https://mise.run | sh
}

activate() {
  case "${SHELL:-}" in
  */zsh)
    echo "Activating Mise in your shell at ${ZDOTDIR-$HOME}/.zshrc"
    echo "eval \"\$($install_path activate zsh)\"" >>"${ZDOTDIR-$HOME}/.zshrc"
    ;;
  */bash)
    echo "Activating Mise in your shell at $HOME/.bash_profile"
    echo "eval \"\$($install_path activate bash)\"" >>"$HOME/.bash_profile"
    ;;
  */fish)
    echo "Activating Mise in your shell at $HOME/.config/fish/config.fish"
    echo "$install_path activate fish | source" >>"$HOME/.config/fish/config.fish"
    ;;
  *)
    $install_path activate --help
    ;;
  esac
}

command_output=$($install_path --version 2>/dev/null) || command_failed=true

if [[ ${command_failed:-false} == "true" ]]; then
  install
else
  desired_mise_version="${mise_version#v}"
  # Extract the version from the output
  current_mise_version=$(echo "$command_output" | awk 'NR==1 {print $1}')

  if [ "$current_mise_version" != "$desired_mise_version" ]; then
    install
  fi
fi

if [[ ! $CI ]]; then
  activate
  $install_path trust
  purple='\033[0;35m'
  neutral='\033[0m' # No Color
  echo ""
  echo -e "${purple}============================================================================${neutral}"
  echo -e "${purple}Installation complete. Please restart your shell for changes to take effect.${neutral}"
  echo -e "${purple}============================================================================${neutral}"
fi

if [[ $CI ]]; then
  $install_path trust
  $install_path run all-ci
  $install_path env | sed 's/^export//' | xargs -I {} echo "{}" >>"$GITHUB_ENV"
fi
```

I think that some of the script's functionality could be implemented directly into the official mise installation script:
- Check if mise is already installed at the desired version
- Ask user if shell should be activated
- TODO: use installation script locked to a specific release/commit - https://github.com/jdx/mise/discussions/3431

The script can be used both locally and in CI and makes for a seamless experience between the two, making vendor specific installations (https://github.com/jdx/mise-action) not necessary (caching is still required though).
