### ISSUE TITLE
missing precompiled python binaries

### ISSUE THREAD

**Issue by User087** [jdx/mise#3317]
Mise appears to fetch the precompiled binaries using the list linked to [here](https://github.com/jdx/mise/blob/27a3aefa767c8ef142009dd54c4d7dcc19c235b2/src/plugins/core/python.rs#L91), but that project has releases that haven't been included in that list, e.g. [this](https://github.com/indygreg/python-build-standalone/releases/tag/20210103), perhaps because the filenames don't appear to conform to the format catered for by [the code for constructing the url from the filename](https://github.com/jdx/mise/blob/27a3aefa767c8ef142009dd54c4d7dcc19c235b2/src/plugins/core/python.rs#L116), but the same seems to apply to some of the filenames given in that list, e.g. see lines 252-263, 280-283, 817-824, 841-844. So it seems that either the code should be updated to cater for those filenames, or it already does in which case there are some missing from that list as mentioned above.

Another option that might be worth considering is making a setting for the user to specify a path to their own precompiled binary, which would allow them to download any missing binaries from [the same project](https://github.com/indygreg/python-build-standalone/releases) and just manually specify the path to it when installing through Mise.

**Comment by jdx** [comment]
sounds like this just means we're missing older 3.8/3.9 releases which does not seem like a big deal since they're still available just not precompiled
