### ISSUE TITLE
Git hooks

### ISSUE THREAD

**Issue by boris-smidt-klarrio** [jdx/mise#3344]
Hey jdx,

There seem to be several tools to manage git hooks in projects to make test run before a commit or before pushing the code:
https://pre-commit.com/
https://github.com/typicode/husky
https://github.com/evilmartians/lefthook
(example https://github.com/evilmartians/lefthook/blob/master/examples/complete/lefthook.yml) 

The issue i have with these tools is that they don't compose that well with mise tasks, so you can't really use the features of the pre-commit tooling like subselecting the staged files in mise. So then you have to kinda duplicate the logic between the two.

## feature request:
Have git hooks as a feature in mise, lefthook might be good for inspiration since it seemed easier to setup than per-commit. I think mise really has the advantage that with its task dependencies so the hooks can all run in parallel.

Pre-commit seems to have quite some overlap with mise that it can also install tools so now i have to backport these tasks to mise to be able to run them. 

## current workaround
I define tasks pre-commit and pre-push and put dependencies on all the hooks that need to run and duplicate build in plugins of `pre-commit` and drop the staging files part.

**Comment by jdx** [comment]
[we already have this](https://mise.jdx.dev/cli/generate/git-pre-commit.html)
