### ISSUE TITLE
Restrict Python versions to prebuilt binaries

### ISSUE THREAD

**Issue by brendanator** [jdx/mise#3347]
Right now the latest releases of Python are not available prebuilt - https://github.com/indygreg/python-build-standalone/issues/398

When I run `mise install python` / `mise install python@3.12` it compiles Python from source

This is especially bad in CI if I've previously run `mise use python@3.12`

Is it possible to restrict the Python (and other tool) versions to prebuilt versions only?

**Comment by jdx** [comment]
[yes](https://mise.jdx.dev/lang/python.html#python.compile)

**Comment by brendanator** [comment]
Awesome, thanks!
