### ISSUE TITLE
add brew/windows installs to getting started carousel

### ISSUE THREAD

**Issue by jdx** [jdx/mise#3356]

**Comment by hverlin** [comment]
I can take this. However, on the https://mise.jdx.dev/getting-started.html page, we will have to clarify that some installers will automatically [activate](https://github.com/Homebrew/homebrew-core/blob/ab9a669e4bbc9c5326714ff36891978de84b586b/Formula/m/mise.rb#L50) / use [shims](https://mise.jdx.dev/installing-mise.html#windows-scoop) etc. 

Some also automatically install the [autocompletion](https://github.com/Homebrew/homebrew-core/blob/ab9a669e4bbc9c5326714ff36891978de84b586b/Formula/m/mise.rb#L45) (also for [macport](https://github.com/macports/macports-ports/blob/master/sysutils/mise/Portfile#L34))

Based on this, I feel like maybe the `curl` install should perhaps offer you to install the autocompletion (or add a message about it at the end of the installation)

**Comment by hverlin** [comment]
Maybe we can leverage something like https://vitepress-plugins.sapphi.red/tabs/ here (like on this [page](https://infisical.com/docs/cli/overview))

**Comment by jdx** [comment]
> I can take this. However, on the https://mise.jdx.dev/getting-started.html page, we will have to clarify that some installers will automatically [activate](https://github.com/Homebrew/homebrew-core/blob/ab9a669e4bbc9c5326714ff36891978de84b586b/Formula/m/mise.rb#L50) / use [shims](https://mise.jdx.dev/installing-mise.html#windows-scoop) etc.
I believe just those 2.

> Some also automatically install the [autocompletion](https://github.com/Homebrew/homebrew-core/blob/ab9a669e4bbc9c5326714ff36891978de84b586b/Formula/m/mise.rb#L45) (also for [macport](https://github.com/macports/macports-ports/blob/master/sysutils/mise/Portfile#L34))

I think they all do except mise.run

> Based on this, I feel like maybe the curl install should perhaps offer you to install the autocompletion (or add a message about it at the end of the installation)

I'm cool with a message, but automating it is going to be impossible to get right.

> Maybe we can leverage something like https://vitepress-plugins.sapphi.red/tabs/ here (like on this [page](https://infisical.com/docs/cli/overview))

it's already included, see https://mise.jdx.dev/installing-mise.html#apt

**Comment by jdx** [comment]
ah ok, sounds good to me—though I'm also content with code comments
