### ISSUE TITLE
Mise doesn't seem to properly activate during docker build

### ISSUE THREAD

**Issue by taranlu-houzz** [jdx/mise#3361]
**Describe the bug**
I am trying to get `mise`, `uv`, and `pdm` setup inside of a `docker` image. I am able to successfully install `mise` and `uv`, but when I try to use `uv` in a `RUN` command, it fails, even though I am explicitly sourcing the `~/.bashrc` that has been updated with the `mise` activation code. If I just build to the `uv` stage and exec into the container, `mise` and `uv` are available and functional as expected. I have verified that the `.bashrc` has been updated, I that it is actually run. It seems that `mise` is just not updating the path correctly for some strange reason. To try to verify this, I used `RUN mise env` right at the start of the `pdm` stage, and it showed an unmodified `PATH`.

**To Reproduce**
This is my `Dockerfile`:
```Dockerfile
# syntax=docker/dockerfile:1


####################################################################################################
# base
####################################################################################################


FROM ubuntu:24.04 AS base

# ==Config image==
SHELL ["/bin/bash", "-c"]
ENV PATH=/root/.local/bin:${PATH}

# ==Install and update packages==
# Image base packages
RUN --mount=type=cache,target=/var/cache/apt \
    apt update && apt upgrade -y

# Additional base packages
RUN --mount=type=cache,target=/var/cache/apt \
    apt install -y \
    curl \
    git


####################################################################################################
# mise
####################################################################################################


FROM base AS mise

# ==Install mise==
ARG MISE_VERSION=v2024.10.8
RUN curl https://mise.run | env MISE_VERSION=${MISE_VERSION} sh

# ==Configure mise==
# NOTE: This is only applicable for interactive bash sessions.
RUN echo 'eval "$(mise activate bash)"' >> ${HOME}/.bashrc


####################################################################################################
# uv
####################################################################################################


FROM mise AS uv

# ==Install uv==
# NOTE: Shell configuration is handled automatically by the installer by default.
ARG UV_VERSION=0.5.6
RUN mise plugins install -y uv
RUN mise install uv@${UV_VERSION}
RUN mise use --global uv@${UV_VERSION}


####################################################################################################
# pdm
####################################################################################################


FROM uv AS pdm

# ==Install pdm==
ARG PDM_VERSION=2.21.0
ARG PDM_PYTHON_VERSION=3.13.1
RUN mise plugins install -y pdm
RUN source ${HOME}/.bashrc && \
    uv run \
    --python ${PDM_PYTHON_VERSION} \
    --python-preference "only-managed" \
    mise install pdm@${PDM_VERSION}

# ==Configure mise==
RUN source ${HOME}/.bashrc && \
    mise global pdm ${PDM_VERSION}
```

**Comment by jdx** [comment]
```
# NOTE: This is only applicable for interactive bash sessions.
RUN echo 'eval "$(mise activate bash)"' >> ${HOME}/.bashrc
```

you literally have a comment in your own code explaining why this doesn't work

**Comment by taranlu-houzz** [comment]
Yes, I know. But I am explicitly sourcing the `.bashrc` later, and it doesn't work. I also did try modifying to use `SHELL ["/bin/bash", "-ic"]` and that also does not work.

**Comment by jdx** [comment]
please read the docs more closely, this is exactly how it behaves. Specifically this:

> This is only intended to be used in interactive sessions, not scripts. mise is only capable of updating PATH when the **prompt is displayed to the user**. For non-interactive use-cases, use shims instead.

https://mise.jdx.dev/cli/activate.html

**Comment by jdx** [comment]
there are 2 solutions presented for this exact situation: https://mise.jdx.dev/dev-tools/shims.html#zshrc-bashrc-files

**Comment by taranlu-houzz** [comment]
Ah, okay, I see. I swear that I had this working in the past with `rtx`, but maybe I am misremembering? Thank you for pointing me to the workarounds.
