### ISSUE TITLE
mise use defaults to global ~/.tool-versions

### ISSUE THREAD

**Issue by ViggoV** [jdx/mise#3365]
**Describe the bug**
I am trying `mise` as an alternative to `adsf`. However when I write for example `mise use node@22`, rather than creating a local `mise.toml` file it just uses `~/.tool-versions`. Since local pinning is the default behavior there is no `--local` flag. The only option is to specify `-p ./mise.toml`

This is problematic as the major benefit of this kind of tool in our organization is to check the specific versions into git for smooth onboarding

**To Reproduce**
1. Have a global `.tool-versions` file from `asdf`
2. Create a project and use Mise to install something (may need to exist in the .tool-versions file beforehand)
3. Note that mise prints the `~/.tool-versions` path rather than create a local `mise.toml`

**Expected behavior**
I excpect the default behavior to be the creation or update of a `mise.toml` file

**`mise doctor` output**
```text
version: 2024.12.0 macos-arm64 (2024-12-04)
activated: yes
shims_on_path: no

build_info:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS
  Built: Wed, 4 Dec 2024 18:50:12 +0000
  Rust Version: rustc 1.83.0 (90b35a623 2024-11-26) (Homebrew)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (arm64-apple-darwin24.0)

dirs:
  cache: ~/Library/Caches/mise
  config: ~/.config/mise
  data: ~/.local/share/mise
  shims: ~/.local/share/mise/shims
  state: ~/.local/state/mise

config_files:
  ~/.tool-versions
  ~/Documents/projects/prototypes/auth-test-setup/mise.toml

backends:
  aqua
  asdf
  cargo
  core
  gem
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:
  dotnet  ssh://git@github.com/hensou/asdf-dotnet.git#888fdde

toolset:
  aqua:pnpm/pnpm@8.3.1  (missing)
  asdf:dotnet@9.0.101
  asdf:emersonsoares/asdf-dotnet-core@6.0.403  (missing)
  asdf:mise-plugins/asdf-yarn@1.22.19  (missing)
  asdf:mise-plugins/mise-poetry@1.4.2  (missing)
  core:bun@1.1.21       (missing)
  core:go@1.16.15       (missing)
  core:node@22.12.0
  core:python@3.10.8    (missing)
  core:ruby@3.2.0       (missing)
  core:rust@1.77.1      (missing)

env_vars:
  MISE_SHELL=zsh

settings:

No problems found
```

Note: this is after forcefully creating `mise.toml` using `-p ./mise.toml`

**Additional context**
Add any other context about the problem here. Consider running mise with `--debug` or `--trace` for extra debug info.

**Comment by jdx** [comment]
use `~/.config/mise/config.toml` instead

**Comment by jdx** [comment]
you could run `cat ~/.tool-versions | tr ' ' '@' | xargs -n2 mise use -g`

**Comment by ViggoV** [comment]
I have unstalled `mise` because of this and some conflicts with `asdf`
