### ISSUE TITLE
List of urls for repos and binaries

### ISSUE THREAD

**Issue by jbadeau** [jdx/mise#3368]
Hello,

I like the idea of securing the supplychain for mise pliugins. It would be very nice if you maintained a list of repos urls and binary urls used so that organizations can white list them.

Regards,
Jose

**Comment by syhol** [comment]
Are you thinking of something other than `mise registry` 
![image](https://github.com/user-attachments/assets/522a7508-c521-4462-8df3-d01523bacd9d)

This can be found at https://mise.jdx.dev/registry.html and https://github.com/jdx/mise/blob/main/registry.toml

**Comment by jdx** [comment]
I think what they're looking for is an exhaustive list of urls to add to a firewall. I don't think that's realistic.

**Comment by jbadeau** [comment]
The issues is that companies want to know where mise/asdf plugins are reaching out to. I understand you don’t control all plugins but it would be nice for the core. Other plugins would prob be forked internally like mise but this just means everyone maintains their own. Would be great to maybe have a public register one day but security is important and knowing where binaries are installed from is required.

**Comment by jdx** [comment]
this would be a lot of work for me to maintain and would only help organizations that spend significant time working with such a list. There are better ways I can spend my time to enhance supply chain security like adding cosign/slsa to more tools which help everyone not just large corporations.
