### ISSUE TITLE
Tasks: `${root}` environment variable appears equal to `${MISE_PROJECT_ROOT}`, not `${MISE_CONFIG_ROOT}`

### ISSUE THREAD

**Issue by dradtke** [jdx/mise#3377]
**Describe the bug**

In the documentation [here](https://mise.jdx.dev/tasks/#environment-variables-passed-to-tasks), it lists these environment variables as being available to Mise tasks:

> `MISE_CONFIG_ROOT` or `root`: The directory containing the `mise.toml` file where the task was defined.
> `MISE_PROJECT_ROOT`: The root of the project.

However, it looks like `root` is actually used as an alias for `MISE_PROJECT_ROOT`, not `MISE_CONFIG_ROOT`.

**To Reproduce**

To reproduce, I have a pretty simple setup:

```
.
├── .mise
│   └── tasks
│       └── show-root-file
├── .mise.toml
└── subdir
    └── .mise.toml
```

In `.mise.toml`:

```toml
[tasks.show-root-toml]
run = """
echo "MISE_CONFIG_ROOT = ${MISE_CONFIG_ROOT}"
echo "MISE_PROJECT_ROOT = ${MISE_PROJECT_ROOT}"
echo "root = ${root}"
"""
```

In `subdir/.mise.toml`:

```toml
# empty
```

`.mise/tasks/show-root-file`:

```bash
#!/usr/bin/env bash
echo "MISE_CONFIG_ROOT = ${MISE_CONFIG_ROOT}"
echo "MISE_PROJECT_ROOT = ${MISE_PROJECT_ROOT}"
echo "root = ${root}"
```

With these files in place, here is the output I see when I run this task, both as a file and as TOML:

```bash
$ cd subdir

$ mise run show-root-toml
[show-root-toml] $ echo "MISE_CONFIG_ROOT = ${MISE_CONFIG_ROOT}"
MISE_CONFIG_ROOT = /home/dradtke/workspace/mise-example
MISE_PROJECT_ROOT = /home/dradtke/workspace/mise-example/subdir
root = /home/dradtke/workspace/mise-example/subdir

$ mise run show-root-file
[show-root-file] $ ~/workspace/mise-example/.mise/tasks/show-root-file 
MISE_CONFIG_ROOT = /home/dradtke/workspace/mise-example
MISE_PROJECT_ROOT = /home/dradtke/workspace/mise-example/subdir
root = /home/dradtke/workspace/mise-example/subdir
```

**Expected behavior**

According to the documentation, `root` and `MISE_CONFIG_ROOT` should have the same value, but they don't.

**`mise doctor` output**

```text
version: 2024.12.0 linux-x64 (20525d2 2024-12-04)
activated: yes
shims_on_path: no

build_info:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Wed, 4 Dec 2024 19:00:28 +0000
  Rust Version: rustc 1.83.0 (90b35a623 2024-11-26)
  Profile: release
```

**Additional context**

N/A

**Comment by dradtke** [comment]
This section appears to confirm this behavior: https://github.com/jdx/mise/blob/4683b32e8c52a8c0952e4c4706eef57aade05652/src/cli/run.rs#L256-L257

**Comment by hverlin** [comment]
Ah, sorry, just updated it and added it to the wrong line :man_facepalming: 
Thanks for catching this!
