### ISSUE TITLE
`mise format`

### ISSUE THREAD

**Issue by jdx** [jdx/mise#3422]
basically just sort the config file

**Comment by hverlin** [comment]
Will this be compatible with `taplo`?
https://taplo.tamasfe.dev/configuration/formatter-options.html

**Comment by jdx** [comment]
we could probably add taplo as a lib if it's not too heavy—the json schema stuff would be nice to validate the config against the schema inside mise as well

**Comment by jdx** [comment]
looking at the taplo formatter, it's great for managing some of the whitespace stuff (which is awesome and worth adding for that alone), but I'd like some custom sorting that would go beyond what taplo could do.

I think config files should roughly follow this order:

```toml
[env]
[tools]
[tasks]
[settings]
```

(there are more top-level things but those are the big ones)

here's how I think this should work (either notes for myself or someone else if they want to pick this up, I think it's a good one to pick up since it probably won't touch much of the rest of the code)

First, I wouldn't use the normal toml_config parser at all. I would just read it in as `toml_edit::Value`, and sort it that way. That'll be a lot easier.

In tools, the order actually matters in some cases since the order of the tools is what goes into PATH. This is rarely important so I think we should by default sort the tools but provide a flag like `--disable-tool-sort` or something (with an alias for `--disable-tools-sort`). This is also true with `[env]` so I think something similar like `--disable-env-sort` would be good.

There will be some edge cases to work out like that env can be an array `[[env]]`.

This would likely be a follow-up, but at some point I'd like it to simplify configs so if you had this originally:

```toml
[tools]
node = {version = "latest"}
[tasks.foo]
run = ["echo 123"]
```

it could simplify both of those to:

```toml
[tools]
node = "latest"
[tasks.foo]
run = "echo 123"
```

mise does a _ton_ of this and I'm always looking to add more since I like the config to be flexible and where users don't need to remember if something is an array or not.

**Comment by hverlin** [comment]
I think there is also an edge case with `vars` and `env`?
