### ISSUE TITLE
Create winget package

### ISSUE THREAD

**Issue by knolljo** [jdx/mise#3425]
In Windows there is a way to install packages like on most linux distros with a package manager. It's called `winget` and is officially supported by Microsoft.

Offering mise to be installed via winget would make the distribution on Windows much easier.

If there is interest in this, I could contribute to it.
Creating a package is pretty straight forward with `winget-create`.

**Comment by jdx** [comment]
yeah this just hasn't happened yet because I don't know how to do it, some help would be great. Even if you could just give me a script to build it I could do the work of integrating it into the release process

**Comment by knolljo** [comment]
After some research I found [Komac](https://github.com/russellbanks/Komac), which seems to be used by a lot of rust based projects like `gitui` or`just`.

It provides a [GitHub Acrion](https://github.com/russellbanks/Komac?tab=readme-ov-file#usage-with-github-actions-winget-releaser-).

**Comment by knolljo** [comment]
After some research I found [Komac](https://github.com/russellbanks/Komac), which seems to be used by a lot of rust based projects like `gitui` or`just`.

It provides a [GitHub Acrion](https://github.com/russellbanks/Komac?tab=readme-ov-file#usage-with-github-actions-winget-releaser-). 

This [Repo](https://github.com/michidk/winget) might be a good starting point to implement your own Gh-Workflow.

**Comment by jdx** [comment]
unrelated: seems like a tool we should add to the registry

I think the best way to integrate it would be to add it to [build-tarball.ps1](https://github.com/jdx/mise/blob/main/scripts/build-tarball.ps1)

Then I think we just need to modify this to add it as an asset:

https://github.com/jdx/mise/blob/9c71e44cc12871cd69f2a4829390e912cb8519a8/.github/workflows/release.yml#L125-L129

And then it needs to be published to s3 and the github release, and I assume to WinGet after that.

I will probably have some time to get around to this at some point, but it involves dusting off my windows laptop so idk when.

**Comment by knolljo** [comment]
This tool would definitely make a fine addition to the tool collection! 

Afaik the publishing process to winget is just a pull request to the official `winget-pkgs` repo with some manifest files for a package.

These manifests include the location where to pull the exe/installer from, for most packages it is the GH Releases page. The Action could do a pull request to winget-pkgs automatically for each release.

It is also possible to create an external repo that periodically checks the Releases page for mise and updates the manifest on a change.

I have a Windows machine ready, lmk if i can help.

**Comment by jdx** [comment]
you should be able to just run that ps file if you clone this repo, e.g.: `pwsh scripts/build-tarball.ps1`. Assuming that works, then just add komac and build the installer and submit a PR.

**Comment by andrewcrook** [comment]
Chocolatey is another
