### ISSUE TITLE
Multiple version of mise

### ISSUE THREAD

**Issue by Ernest0-Production** [jdx/mise#3437]
# Context

We use mise to install tools both locally and on CI.

Occasionally there is a need to update the version of mise, but make it so that the version is tied to the project commit to protect yourself from breaking changes and maintain backward compatibility.

# Problem

Currently, I created a file `.mise-version` in my repository and download the required version of mise using a bash script.
This solution is not entirely reliable on CI, since it can run several builds on different commits, each of which will try to install its own version of mise and only the last one will decide which version will be the final one.

At the moment, this causes problems when migrating `[plugins]` to `[alias]`

# Suggestion

Allow multiple versions of mise to be present at the same time and tie the version in `mise.toml`.
This feature will be stable and unchangeable most of the time, which means the risks of running into breakdowns will be much lower

# Implementation

1. Create a `.mise-version` file, which will contain the version

- The `mise acitvate` command should automatically detect the absence of the required version and issue a warning
- The `mise self-install` command should install the required version if it is missing (the name is based on the self-update command)
- The `mise self-update` command installs a new version and stores it as a `mise-latest` binary (more below)
- The `mise self-update --pin` command installs a new version and updates the `.mise-version` file

2. Store multiple versions of binaries

In `.local/bin/` the key binary will be `mise`, but it will act as a router.
When accessing it, it should take into account 
- from which directory the command was called
- is there a mise.toml configuration in this directory
- what version is specified in .mise-version
- if the version is specified, then redirect the call to the binary of a specific version (`~/.local/bin/mise-x-y-z`)
- if the version is not specified, then redirect the call to the binary `~/.local/bin/mise-latest`

**Comment by jdx** [comment]
you should be able to do this yourself by setting MISE_VERSION and MISE_INSTALL_PATH=mise-2024.1.1 using mise.run.

That said, I do not build mise in a way where switching between versions is guaranteed to function. Going up in versions is fine, but going back may not function. You should use a global version of mise in CI—which you can pin to avoid bugs and update it regularly. In general I don't ship breaking changes. If I do, it's going to come with a very long migration path with loud warnings and even that is very rare anymore.
