### ISSUE TITLE
I want to make a file task on macOS inside a group without using an alias, but I can't

### ISSUE THREAD

**Issue by stevelandeyasana** [jdx/mise#3443]
macOS reserves `:` as a filename character because it used to be the separator before OS X. Mise uses `:` as the group separator.

If I define a task in `mise-tasks/foo-bar` and include `#MISE alias="foo:bar"`, I can run it with `mise task run foo:bar`, but:
1. It still shows up in `mise task ls` as `foo-bar`, so it sorts contrary to my intentions
2. I can't run it with `mise foo:bar` (this might be a bug)

I hope the problem statement here makes sense. It seems problematic to have Mise's group separator be the same as a forbidden character in macOS filenames.

**Comment by jdx** [comment]
https://mise.jdx.dev/tasks/file-tasks.html#task-grouping

**Comment by stevelandeyasana** [comment]
All right, yeah I feel pretty silly now, thanks!
