### ISSUE TITLE
Trim whitespace from `run` in tasks

### ISSUE THREAD

**Issue by joshbode** [jdx/mise#3444]
If whitespace was trimmed (start and end of string) from the `run` field, then it would make it more convenient/readable to use multi-line scripts in tasks, e.g.

```toml
[tasks.test]
run = '''
printf 'args:\n'
printf '  - %s\n' "$@"
'''
```
which yields:
```
$ mise run test a b c
[test] $ printf 'args:\n'
args:
  -
sh: line 2: a: command not found
[test] ERROR task failed
```

note: If I put the first command on the first line, this _does_ work but it's a bit harder to read:
```toml
[tasks.test]
run = '''printf 'args:\n'
printf '  - %s\n' "$@"'''
```
yielding:
```
$ mise run test a b 'c d'
[test] $ printf 'args:\n'
args:
  - a
  - b
  - c d
```
(also, only the first line of the command is shown, which is probably unnecessary)

**Comment by jdx** [comment]
I'm surprised this wasn't happening already
