### ISSUE TITLE
Rename `kubelogin` in registry?

### ISSUE THREAD

**Issue by jimeh** [jdx/mise#3493]
In mise's `registry.toml`, it sets up a `kubelogin` shorthand that installs [Azure/kubelogin](https://github.com/Azure/kubelogin), which is a Microsoft Azure specific kubectl login helper.

But there's also [int128/kubelogin](https://github.com/int128/kubelogin), which is a generic OIDC kubectl authentication helper, and it has 1.8K stars on GitHub compared to just under 500 for Azure's kubelogin helper.

Hence, I'd like to suggest that the `kubelogin` shorthand is renamed to `azure-kubelogin`, and a new `kubelogin` shorthand is added for [int128/kubelogin](https://github.com/int128/kubelogin).

This is likely to be an unpopular change for anyone who's installed Azure's kubelogin tool however, so I don't think if renaming it is reasonable. Not to mention, since both tools expose an executable with the same name, it might be reasonable to add a "conflicts with" option of some kind in mise's registry, so that it doesn't let you activate both tools at the same time, or at least warns you about it.

**Comment by jdx** [comment]
it'd be nice if https://github.com/jdx/mise/issues/3339 was in because that would lock the backend into the lockfile, but even if I patched that now it still wouldn't help people until they reinstalled (and were already using lockfiles). I think we should stop the bleeding here despite that.
