### ISSUE TITLE
prerun hook

### ISSUE THREAD

**Issue by kapitoshka438** [jdx/mise#3515]
It would be useful to have a prerun hook, which executes when you run `mise run`.
In particular, I need this hook to install a pinned version on mise before executing `mise install` (this type of hook is already implemented) and `mise run ...`
Kinda like this:
```
[env]
MISE_VERSION = "2024.12.8"

[hooks]
prerun = "mise self-update $MISE_VERSION -y"
```

**Comment by jdx** [comment]
I do not support this use-case. You should only ever increase the mise number or roll back if there is a bug.

In general I'm not opposed to having a prerun hook, but this use-case is a bad idea.

**Comment by kapitoshka438** [comment]
> I do not support this use-case. You should only ever increase the mise version or roll back if there is a bug.
> 
> 
> 
> In general I'm not opposed to having a prerun hook, but this use-case is a bad idea.

I'd like to mention that we have many projects which pin their own mise versions because different development teams work on them. But these projects run CI on the shared set of runners and we need to ensure full behavioral compliance between CI runners and delevoper machines and also to provide the ability to switch between mise versions on one machine according to a project.

**Comment by jdx** [comment]
I don't recommend that you do that

**Comment by jdx** [comment]
I'm going to close but if someone has an alternative use-case I'd be happy to reconsider
