### ISSUE TITLE
settings.python.uv_venv_auto = true doesn't update PATH correctly

### ISSUE THREAD

**Issue by tyilo** [jdx/mise#3567]
Currently when enabling `uv_venv_auto` the `VIRTUAL_ENV` environment variable is set correctly, but `PATH` is not updated, so `python` doesn't refer to the correct `python` executable inside the virtualenv.

```sh
$ mise --version
2024.12.10 linux-x64 (d52ec61 2024-12-14)
$ cat ~/.config/mise/config.toml
[settings]
experimental = true

[settings.python]
uv_venv_auto = true
$ cd /tmp
$ uv init foo --python 3.10
mise WARN  missing: python@3.10.16
$ uv run python --version
Using CPython 3.10.16
Creating virtual environment at: .venv
Python 3.10.16
mise WARN  missing: python@3.10.16
$ python --version
Python 3.12.7
mise WARN  missing: python@3.10.16
$ .venv/bin/python --version
Python 3.10.16
mise WARN  missing: python@3.10.16
$ printf '[env]\n_.python.venv = ".venv"\n' > mise.toml
mise WARN  Config files in /tmp/foo/mise.toml are not trusted.
Trust them with `mise trust`. See https://mise.jdx.dev/cli/trust.html for more information.
mise WARN  missing: python@3.10.16
$ mise trust
mise trusted /tmp/foo
mise WARN  missing: python@3.10.16
$ python --version
Python 3.10.16
mise WARN  missing: python@3.10.16
```

Furthermore, when `uv_venv_auto` is enabled, it would be nice if `.python-version` (managed by `uv`) is ignored, so you can get rid of the warnings, without having to install the python version in both mise and uv.

**Comment by syhol** [comment]
### venv not on path

> Currently when enabling uv_venv_auto the VIRTUAL_ENV environment variable is set correctly, but PATH is not updated, so python doesn't refer to the correct python executable inside the virtualenv.

Can confirm. Whats interesting is, the `.venv` path entry shows up in `mise dr` and `mise dr path`, but not in `echo $PATH`.

```console
root@497923c552b0:/tmp/foo# mise dr
...
path:
  ~/.local/bin
  /tmp/foo/.venv/bin
  /mise/installs/python/3.10.16/bin
  /mise/installs/viddy/1.3.0
  /usr/local/cargo/bin
  /usr/local/sbin
  /usr/local/bin
  /usr/sbin
  /usr/bin
  /sbin
  /bin
...
root@497923c552b0:/tmp/foo# mise dr path
/root/.local/bin
/tmp/foo/.venv/bin
/mise/installs/viddy/1.3.0
/mise/installs/python/3.10.16/bin
root@497923c552b0:/tmp/foo# echo $PATH | tr ':' '\n'
/root/.local/bin
/mise/installs/viddy/1.3.0
/mise/installs/python/3.10.16/bin
/usr/local/cargo/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
```

### Ignoring idiomatic_files when uv_venv_auto is enabled
> Furthermore, when uv_venv_auto is enabled, it would be nice if .python-version (managed by uv) is ignored, so you can get rid of the warnings, without having to install the python version in both mise and uv.

Disagree. when I use this feature (I haven't yet) I would plan to still manage my python install with mise. I would also like a uv_venv_auto_create feature too. You can manually do this with a mise setting.
To apply globally:
```console
root@cdd3a0686e4e:/tmp/foo# mise settings add idiomatic_version_file_disable_tools "python"
```
To apply locally to the current dir:
```console
root@cdd3a0686e4e:/tmp/foo# mise settings --local add idiomatic_version_file_disable_tools "python"
```

**Comment by jdx** [comment]
perhaps we could have a `mise sync python --uv` command

**Comment by tyilo** [comment]
Nice, thanks!
