### ISSUE TITLE
(python) Only skip creating the venv when the required (first or `env._.python.venv.python`) python version is missing

### ISSUE THREAD

**Issue by syhol** [jdx/mise#3569]
As raised here: https://github.com/jdx/mise/issues/1898

While inside directory with the following config:
```toml
[env]
_.python.venv = { path = "venv", create = true }
```

Currently the venv won't be created by mise if **any** of the requested python tool versions are missing. This enhancement is to instead only skip creating the venv if the specific python version for the venv is missing. The python version is decided as follows:
1. If `env._.python.venv.python` is present, then the tool version specified in `env._.python.venv.python`, e.g.:
    - WHEN `_.python.venv = { path = "venv", create = true, version = "3.10" }`
    - THEN 3.10 is the venv version
2. If the python tool is a list of versions, then the first tool version e.g.:
    - WHEN `tools.python = ["3.9", "3.10", 3.11"]`
    - THEN 3.9 is the venv version
3. If the python tool is a single version, that version should be used:
    - WHEN `tools.python = "3.11"`
    - THEN 3.11 is the venv version

This ☝️ is already the effective behaviour for how the venv version is selected, however, how it works under the hood is that if a `env._.python.venv.python` isn't present then it will use whatever python3 resolves to on PATH.

**Comment by jdx** [comment]
I suspect this isn't as important as it was when #1898 was created because that was when we didn't have precompiled pythons I think

**Comment by syhol** [comment]
Yeah, most mise installs only take a few seconds for me, but I am blessed with good internet speeds.
