### ISSUE TITLE
[Feature request] allow to define background tasks

### ISSUE THREAD

**Issue by FezVrasta** [jdx/mise#3606]
Hi, it would be very useful if Mise tasks supported a way to define a command that has to run in the background along with the main one.

For example, having a task to start the frontend application and in background run the backend and the database.

The way `depends` work today is weird, some commands do actually execute in the background, while others just hang and don't let the main command run.

**Comment by jdx** [comment]
I am working on this but not in mise https://github.com/jdx/pitchfork

**Comment by FezVrasta** [comment]
Thanks! This looks great
