### ISSUE TITLE
Feat: mise watch flags to clear terminal

### ISSUE THREAD

**Issue by boris-smidt-klarrio** [jdx/mise#3634]
Hey Jeff,

I've used mise watch and its really handy to have these very fast iterations without rerunning the command.

I've used `watchexec` in the past and found these features quite handy:

## clear the terminal between runs `--clear`
this is useful when you fix compiler, linter and tests to avoid the confusion between errors you already fixed and the new run.

## debouncing `--delay-run` `--debounce`
Sometimes when you go trough the lint, build cycle it can be useful to have a debounce so you can fix a few errors before rerunning the linter.

## force restart `--restart`
When you add `mise run app` to start a server its useful to restart that app on change. I don't use this that often and i can always add watchexec as a dependency for this.

https://github.com/watchexec/watchexec

**Comment by hverlin** [comment]
You can use any of the `watchexec` flag, see `--clear` for example: 
https://mise.jdx.dev/cli/watch.html#c-clear-mode

```sh
mise watch <my-task> --clear
```

**Comment by boris-smidt-klarrio** [comment]
Ah cool @hverlin thank you for pointing me out:

Note to myself run `mise self-update` before opening a feature request.

Maybe it could be a usefull thing for the PR template to notify t update to the latest version.

**Comment by jdx** [comment]
the args are literally copy+pasted from watchexec so you can use `--clear` without a value just like in watchexec
