### ISSUE TITLE
[BUG]  rust is now symlinked , wasn't before.

### ISSUE THREAD

**Issue by cocoonkid** [jdx/mise#3638]
**Describe the bug**
I Install mise via ansible to all my machines, for the root user and for one normal user. 
This worked like a charm with a shared mise dir (I know this has security implications, I am aware)

But with the latest release the cargo is not in the mise folder anymore but symlinked like 

![image](https://github.com/user-attachments/assets/109594d3-c06c-436f-8944-c053f56c2e1e)

**Expected behavior**

Just have the normal non-sym link version again that the normal user can access too.

**`mise doctor` output**

```text
❯ mise doctor
version: 2024.12.12 linux-x64 (2d9d289 2024-12-16)
activated: yes
shims_on_path: no

build_info:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Mon, 16 Dec 2024 18:21:32 +0000
  Rust Version: rustc 1.83.0 (90b35a623 2024-11-26)
  Profile: release

shell:
  /usr/bin/zsh
  zsh 5.8 (x86_64-redhat-linux-gnu)

dirs:
  cache: ~/.cache/mise
  config: /etc/mise/
  data: /opt/.mise
  shims: /opt/.mise/shims
  state: ~/.local/state/mise

config_files:
  /etc/mise/config.toml

backends:
  aqua
  asdf
  cargo
  core
  gem
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:
  lazydocker  https://github.com/comdotlinux/asdf-lazydocker.git#abb6f71
  pipx        https://github.com/yozachar/asdf-pipx.git#31db618

toolset:
  aqua:direnv/direnv@2.35.0
  asdf:lazydocker@0.24.1
  asdf:pipx@1.7.1
  core:rust@1.83.0
  ubi:ajeetdsouza/zoxide@0.9.6

path:
  /opt/.mise/installs/direnv/2.35.0
  /opt/.mise/installs/lazydocker/0.24.1/bin
  /opt/.mise/installs/pipx/1.7.1/bin
  ~/.cargo/bin
  /opt/.mise/installs/zoxide/0.9.6/bin
  ~/.local/share/zinit/plugins/rusty-ferris-club---shellclear
  ~/.local/share/zinit/polaris/bin
  /sbin
  /bin
  /usr/sbin
  /usr/bin
  ~/.bins/
  ~/.local/bin
  /usr/local/bin
  ~/.fzf/bin

env_vars:
  MISE_DATA_DIR=/opt/.mise
  MISE_CONFIG_DIR=/etc/mise/
  MISE_SHELL=zsh

settings:

No problems found


```

**Additional context**
![image](https://github.com/user-attachments/assets/8feeeda9-8b9e-49b7-a3e6-257004a2e25c)

I found the mise rust is actually installed as it should be. 
But linking it does not work. 

And I'd have to add some whacky tasks to my playbooks to account for this behaviour. 
rust is intentionally not installed via the system package manager.  (it might by default with rocky linux 9?)

Thank you for looking into this!

I flippin'n love mise!

**Comment by jdx** [comment]
this is how the core plugin works by design. you were probably using asdf-rust before

**Comment by cocoonkid** [comment]
It does 
`mise install rust@latest`
 since months and it always worked?
 I never specifically selected another plugin to use.

**Comment by cocoonkid** [comment]
Running it like this:

![image](https://github.com/user-attachments/assets/8be3a912-8f22-49f9-9c0d-e69031aa41e5)

![image](https://github.com/user-attachments/assets/ba21d171-6eae-429d-b90b-5e00c09a6fd8)

**Comment by hverlin** [comment]
If you really want to use the asdf rust plugin, you can switch back to it by setting a custom [alias](https://mise.jdx.dev/dev-tools/aliases.html).

```sh
docker run -it --rm --entrypoint=/bin/bash jdxcode/mise:latest
root@5e31607164b2:/mise# mise config set alias.rust asdf:code-lever/asdf-rust
root@5e31607164b2:/mise# mise use rust
```

**Comment by cocoonkid** [comment]
My apology. I do not get it. 

I always used the default "mise use rust@latest". 

I NEVER selected asdf-rust. I do not want to opt out of any default behaviour. 

On my local machine and on my servers  "mise use rust@latest"   
installed rust to 
local/share/mise/installs/rust/1.83.0/bin/cargo
or 
/opt/.mise/installs/rust/1.83.0/bin/cargo

Suddenly, since today  this does not happen. 
they get installed to /root/.cargo/ on my servers.  (fresh servers, same playbooks that always worked.)

I did not update locally yet. 


So I always used core:rust then how did that behaviour change ?

**Comment by hverlin** [comment]
`rust` was added to core 3 weeks ago: https://github.com/jdx/mise/releases/tag/v2024.11.31 (i.e. replacing the `asdf` plugin which was used previously)

**Comment by jdx** [comment]
Backends can change in releases. It's not considered a breaking change. Use a lockfile if you want to tie it down.

**Comment by cocoonkid** [comment]
> `rust` was added to core 3 weeks ago: [`v2024.11.31` (release)](https://github.com/jdx/mise/releases/tag/v2024.11.31) (i.e. replacing the `asdf` plugin which was used previously)

ahh. Okay. Thanks! now I understand!

Thanks everyone!
