### ISSUE TITLE
BUG: mise install --force not picking up enviroment

### ISSUE THREAD

**Issue by boris-smidt-klarrio** [jdx/mise#3702]
**Describe the bug**
When i do `mise install` it picks up the `.tool-versions` `mise.toml` file.  But when i add the flag `--force` it works only for a single tool.

Ideally it would reinstall all the tools listen in `mise.toml`.

As i workaround i did a `mise install --force tool@version` like the one defined in the versions file and that fixed it.

**To Reproduce**
```bash
$ mise install        
mise all runtimes are installed
```

Run `mise install --force` in a project with a .mise.toml file.
```bash
$ mise install --force
error: the following required arguments were not provided:
  <TOOL@VERSION>...
```

**Expected behavior**
The same behavior as `mise install` but reinstalling all tools.

```bash
$ mise install --force
mise certstrap@1.2.0     ✓ installed
mise sops@3.8.1          ✓ installed
mise pre-commit@3.7.1    ✓ installed
mise python@3.11.11      ✓ installed       
```

**`mise doctor` output**

```text
version: 2024.12.14 linux-x64 (ac3079c 2024-12-18)
activated: yes
shims_on_path: no

build_info:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Wed, 18 Dec 2024 18:58:12 +0000
  Rust Version: rustc 1.83.0 (90b35a623 2024-11-26)
  Profile: release

shell:
  /usr/bin/zsh
  zsh 5.9 (x86_64-ubuntu-linux-gnu)

dirs:
  cache: ~/.cache/mise
  config: ~/.config/mise
  data: ~/.local/share/mise
  shims: ~/.local/share/mise/shims
  state: ~/.local/state/mise

env_vars:
  MISE_SHELL=zsh

settings:

No problems found

```

**additional context**
I had to do a `mise install --force` because one of the tools didn't end up on my path. 

But it was after doing a major version upgrade and removing the existing plugins form mise so the non asdf backends would be used. So i suspect the original problem is a result of manual fiddling with the mise state.

**Comment by jdx** [comment]
this is by design and I don't see a compelling reason to add this functionality

**Comment by boris-smidt-klarrio** [comment]
Could a command 'reinstalled' be added instead to have a clear distinction.
It feels a bit incosistend that an `install != install --force`
While an `uninstall --all` is kinda the opposite operation of an `install`.
