### ISSUE TITLE
mise run shorthand does not support flags/options

### ISSUE THREAD

**Issue by hverlin** [jdx/mise#3717]
Using `mise <task> --some-option` does not work the same as `mise run <task> --some-option`. 
I am filing it as I think it's a bit confusing (for example, running `mise lint --fix` is not the same as `mise run lint --fix`)

![image](https://github.com/user-attachments/assets/1a1740ca-3510-428f-bc9d-005a3bf4ae4f)

As discussed in the discord, this might be fixed by using `trailing_var_arg` or `allow_hyphen_args` here https://github.com/jdx/mise/blob/5d57bd2dc6ebecc8bbf8fc290c3c707c353414b3/src/cli/mod.rs#L80

This is changing the behavior of the command, so not sure if this is correct:

```sh
# before
mise my_task abc -- a
[my_task] $ echo $* abc a
abc a
```

```sh
# after
./target/debug/mise my_task abc -- a
[my_task] $ echo $* abc -- a
abc -- a
```

**Comment by jdx** [comment]
that looks correct to me, the same thing should happen with `mise run my_task abc -- a`
