### ISSUE TITLE
Allow disabling the warning on every prompt execution and do it just on startup

### ISSUE THREAD

**Issue by qkaseman** [jdx/mise#3727]
```
mise WARN  deprecated [TOOL_VERSION_ALIASES]: tool version aliases should be `alias.<TOOL>.versions.<FROM> = <TO>`, not `alias.<TOOL>.<FROM> = <TO>`
```

It is _incredibly_ annoying for this to pop up every time the terminal prompt executes. I understand you want to make it clear to users that something is deprecated but this is beyond annoying. I just upgraded `mise` and wish I didn't because I don't really have time right now to figure out what this is actually asking me to do but now I either have to 

1. spend time I don't have figuring out what I need to do (I don't have any `alias.<TOOL>.<FROM> = <TO>` in my `config.toml` so I don't even know how to get rid of the warning).
2. Suffer though this annoyance.

I'll avoid updating `mise` in the future unless absolutely required until this feature is added.

The only thing about warnings I could find in `Settings` is about [missing tools](https://mise.jdx.dev/configuration/settings.html#status.missing_tools) which is not whats happening here.

**Comment by jdx** [comment]
you can make it go away by using that new structure

**Comment by qkaseman** [comment]
wow, that is an awful response: "this is bad please give a way to not have it happen" "don't care, just fix it based on an unclear warning message".

I'll no longer recommend `mise` then, it's unfortunate I'm forced to use it because I work at the same place as you.
