### ISSUE TITLE
Link to documentation about the deprecation in the deprecation message (or make the deprecation message itself clearer)

### ISSUE THREAD

**Issue by qkaseman** [jdx/mise#3728]
It would be nice if the deprecation message linked to documentation that actually provided details on the issue. The following is not clear to anyone who doesn't use `toml` files for config (I assume this is clear for someone who knows the `toml` syntax based on it being the message you chose). 

```
mise WARN  deprecated [TOOL_VERSION_ALIASES]: tool version aliases should be `alias.<TOOL>.versions.<FROM> = <TO>`, not `alias.<TOOL>.<FROM> = <TO>`
```

This would be less of a problem if [this](https://github.com/jdx/mise/issues/3727) was implemented but as is it is a frustration with a pretty simple fix as you already have a nice docsite.

**Comment by jdx** [comment]
it just means instead of this:

```
[alias.node]
lts = '20'
```

do this:

```
[alias.node.versions]
lts = '20'
```

I think it's clear

**Comment by qkaseman** [comment]
That's your choice as the maintainer but I'm giving you direct user feedback that it is not. take that as you will

**Comment by qkaseman** [comment]
Also, it would take almost no time to have simply had that example on a page of your documentation that the warning message links to. That example is _exactly_ what is needed.
