### ISSUE TITLE
Running multiple tasks via args and parallelism

### ISSUE THREAD

**Issue by davidolrik** [jdx/mise#3733]
In the docs there is this example for running multiple tasks in one go:

```sh
mise run build arg1 arg2 ::: test arg3 arg4
```

But as `mise` will run 4 jobs at the same time, the above command will run both the `build` action and the `test` action at the same time, which is not what I expected.

Is this intended behaviour, or should `:::` work as an implicit `depends`?

For `build` to complete before running `test`, I would have to add a `depends = ["build"]` to the `test` task, but if I've done that then `build` will always be run before `test` which might not always be what I want.

I run all of my task with the suggested alias `mr='mise run --'` which prevents me from adding a `--jobs 1` to `mise run`.

Maybe add a second kind of separator like `::::` that means "implicit depends" and keep `:::` as parallel.

What do you think?

**Comment by jdx** [comment]
I would just do `mise run build && mise run test` or add `wait_for = ["build"]` to `test`
