### ISSUE TITLE
settings completions not working

### ISSUE THREAD

**Issue by jdx** [jdx/mise#3785]

**Comment by hverlin** [comment]
I think it's not completely fixed, as it should probably show autocompletion for all settings (so `mise settings ls --all | awk '{print $1}'`?)
https://github.com/jdx/mise/blob/1fae2b02bf1770d710f8c70f4e41d97c6a4c6297/mise.usage.kdl#L2061

Currently, it only shows completion for modified settings:

<img width="179" alt="image" src="https://github.com/user-attachments/assets/13186317-42f6-47de-9fd1-29034c5c5ceb" />

Would be nice if it would show the description as well (but would require `jq` + using the json schema probably?)

**Comment by hverlin** [comment]
Maybe it's better if `mise` provide the output directly, instead of relying on `awk`/`jq`?
