### ISSUE TITLE
zstd detection false positive on MacOS

### ISSUE THREAD

**Issue by zbynek** [jdx/mise#3827]
**Describe the bug**
The new version of mise install script tries to decide whether to use `zstd` or `tar` based on `tar` version and this fails on MacOS with `tar` version 
`bsdtar 3.5.3 - libarchive 3.5.3 zlib/1.2.12 liblzma/5.4.3 bz2lib/1.0.8` (using MacOS 15.0.1).

**To Reproduce**
Run `curl https://mise.run/ | sh` on MacOS without `zstd` and the above mentioned version of `tar`.

**Expected behavior**
`mise` installed

**Workaround:**
Run `export MISE_INSTALL_EXT=tar.gz` before installing mise.

**Note:** the code introduced in https://github.com/jdx/mise/pull/3798/files checks for presence of `zstd` using `command -v`, doing that _before_ the version check should fix the issue.

**Comment by zbynek** [comment]
@roele do you know how did you get the `zstd` executable? I know it can be installed with Homebrew (https://formulae.brew.sh/formula/zstd ), but from a quick Google search I cannot find any evidence that it should be part of MacOS by default.

**Comment by roele** [comment]
The debug output for my run did not show usage of `zstd` but `tar` and i did not realize i actually had `zstd` installed (as dependency of curl, openjdk via brew). So you're saying the `zstd` binary is still required also when using `tar` which claims it can automatically detect compression and extract it without mentioning a dependency on other binaries.

**Comment by jdx** [comment]
I haven't had time to take a look but it's probably as OP said, the script does a check for whether it should use bsd tar or zstd but I may have the conditional flipped somewhere

**Comment by roele** [comment]
I could not find much information on the behaviour around dependencies for `bsdtar` but some `--use-compress-program` flag caught my attention that simply refers a command to use as compression algorithm which seems what might be used somehow with auto detection.

**Comment by jdx** [comment]
arguably we could just take the logic that uses bsdtar or zstd | tar out since it sounds like we're relying on `zstd` being installed regardless

**Comment by roele** [comment]
Agreed. GNU tar does not seem to have this limitation.

**Comment by zbynek** [comment]
Thanks for the fast turnaround! It works again for me on MacOS.
