### ISSUE TITLE
replace ruby-build with frum code

### ISSUE THREAD

**Issue by jdx** [jdx/mise#3872]
frum is a ruby version manager written in rust that does _not_ rely on ruby-build. If I'm understanding right, there is a "pre-release" version that can install ruby 10x faster than ruby-build: https://github.com/TaKO8Ki/frum

unfortunately, it seems unmaintained, but given it's MIT-licensed and written in rust, in theory it should be possible to import the installation logic into mise for these fast installs.

**Comment by jdx** [comment]
update: I'm not sure why it mentions "Blazing-Fast Ruby Installation" when all it is doing is calling the same `make install` that ruby-build does which takes most of the time. In my testing it's faster: 175s vs 161s which is hardly noticeable, let alone "blazing fast"—unless I did something wrong or am misunderstanding.

That said, I like the idea of the ruby code being inside of mise instead of it calling `ruby-build` even if the performance isn't much different.

Question for ruby users, do you care if mise is just calling `ruby-build` or the code is all in rust even if the behavior doesn't change anything? I did the same in replacing `node-build` with rust code and I think it was a good thing just to keep things simpler but maybe it's not worth the time? There's also the question of maintenance—ruby-build will probably be more on top of any potential issues with building ruby quicker than I will be.

**Comment by andrewthauer** [comment]
I have not dug too far into the internals of how `ruby-build` works so I couldn't say from a technical point of view atm. However, it's maintained by core Ruby language members and updated lock/stock with new ruby releases.

I would be hesitant to use a rust native version for the above reasons. Would it be hard to have this as an experimental / configurable option so that you could still use or fallback to `ruby-build`?

On a side note, I've always wondered why ruby is commonly built from source vs distributed as pre-complied versions for specific architectures.

**Comment by jdx** [comment]
I first looked at frum's logic which is pretty simple, basically just `tar && ./configure && make install` but I think it's probably too simple. ruby-build is 1500 lines of bash and a lot of it seems necessary to port into rust: https://github.com/rbenv/ruby-build/blob/master/bin/ruby-build. So I think you may be right. This was effective for node-build but node-build is much simpler—and people don't compile node very often anyways.

> On a side note, I've always wondered why ruby is commonly built from source vs distributed as pre-complied versions for specific architectures.

Because it's not portable. In Python the astral team is working on [portable binaries](https://github.com/astral-sh/python-build-standalone) we use in mise. People have attempted this with Ruby but nobody is currently maintaining an active project for portable ruby. Homebrew has such a [project](https://github.com/Homebrew/homebrew-portable-ruby) but it explicitly states in the readme it's not for general use.
