### ISSUE TITLE
MISE_ARCH

### ISSUE THREAD

**Issue by jdx** [jdx/mise#405]
We should have a MISE_ARCH env var which can be used to execute plugin scripts with `arch -x86_64`. Doing this will allow installing/running plugins in rosetta on arm macs.

Currently this can be done but it's a bit clunky:

```
mkdir ~/.local/mise-x86
wget https://mise.jdx.dev/mise-latest-macos-x86 ~/.local/mise-x86
~/.local/mise-x86 i java
```

**Comment by jdx** [comment]
sorry for taking a year to respond but I think that's a good callout, it probably should default to `~/.local/share/mise-x86_64` or something

**Comment by jacobat** [comment]
FWIW, I've been running with an architecture dependent `MISE_DATA_DIR` for a long time now without issues. Mostly using it for development with Ruby.

**Comment by teppeis** [comment]
@jdx Thank you! Can you update this document? https://mise.jdx.dev/tips-and-tricks.html#macos-rosetta
