### ISSUE TITLE
RTX with non-shell-based process invocation

### ISSUE THREAD

**Issue by jonathanmorley** [jdx/mise#548]
The way that `rtx` modifies environment variables via a shell hook, necessarily means that it requires a shell.
In normal use, this is not a problem - users generally interact with their system via a shell.

However, sometimes tools are invoked in ways that do not involve shells.

For example:
```typescript
await execa('pnpm', ['--version'], { cwd: 'different-dir', stdio: 'inherit' });
```

If this script snippet is executed in the following fs:
```
cwd
  - .tool-versions (1)
  - different-dir
    - .tool-versions (2)
```
where (1) contains `pnpm 6` and (2) contains `pnpm 7`, then under asdf, the snippet will output `7` (as expected), but `rtx` will output `6` (unexpected).

For this specific case, there is a workaround where `execa` can take a `shell` argument (https://github.com/sindresorhus/execa#shell), and the general case can be addressed by using shims in rtx.

I am raising this more as something to be documented, than as a bug to be fixed.

**Comment by jonathanmorley** [comment]
This feels like a slightly more generalized case of the 'IDE use-case' that favours shims, which is already documented

**Comment by jdxcode** [comment]
is running `rtx x pnpm` instead a solution for you?

**Comment by jonathanmorley** [comment]
`rtx x -- pnpm` is not an option, because this is in a script that needs to be compatible with systems using asdf too.

While I agree that `rtx activate` is not appropriate for non-interactive use-cases, the context of the snippet above was in a unit-test. I am interactively running the unit-test (in an `rtx activate`d shell), but the unit-test is non-interactively running pnpm.

**Comment by jdxcode** [comment]
I had an idea for this just now since I'm actually having some similar thoughts. It would be nice if there was a way to persist an "rtx-lite" that would be just bash that you could commit into a project to be used for version selection without needing to have rtx installed.

I'm not sure though, it's hard to say how version installation would/could work in something like that.

**Comment by cmer** [comment]
I have a shell script that `cd`s into a directory with some Ruby code, and executing the Ruby scripts from another shell script doesn't work. `rtx` doesn't do its thing. I'm assuming it is related to this?

**Comment by jdx** [comment]
solution is to use shims
