### ISSUE TITLE
rtx ls takes 10 seconds

### ISSUE THREAD

**Issue by dfang** [jdx/mise#676]
```
ubuntu@ubuntu2204:~/ $ time rtx ls --verbose
[WARN] rtx::config: newer rtx version 1.34.0 available, currently on 1.32.5
[WARN] rtx::toolset::tool_version_list: failed to resolve tool version: timed out updating node-build: timed out waiting on channel
erlang 26.0.2 
node   20.0.0 
nodejs 16.14.0
nodejs 18.16.0 ~/.tool-versions 18.16.0
nodejs 20.0.0 
pdm    2.7.4  
python 3.10.12

real	0m10.071s
user	0m0.035s
sys	0m0.104s

$ cat ~/.tool-versions 
nodejs 18.16.0
```
fyi: without global config file `~/.config/rtx/config.toml`

**Comment by dfang** [comment]
after I add these lines:

```
$ cat ~/.config/rtx/config.toml
[settings]
plugin_autoupdate_last_check_duration = '1 week' # set to 0 to disable updates


$ time rtx ls
[WARN] rtx::config: newer rtx version 1.34.0 available, currently on 1.32.5
erlang 26.0.2         
node   16.14.0 (missing) ~/.rtx.toml    16.14.0
node   20.0.0         
nodejs 16.14.0        
nodejs 18.16.0         ~/.tool-versions 18.16.0
nodejs 20.0.0         
pdm    2.7.4          
python 3.10.12        

real	0m0.077s
user	0m0.039s
sys	0m0.071s
```

Is there any environment variables like `RTX_UPDATE_CHECK`, `RTX_PLUGINS_UPDATE_CHECK` ?

**Comment by jdxcode** [comment]
it's timing out checking for new node versions. You can customize this with `RTX_FETCH_REMOTE_VERSIONS_TIMEOUT=10s`.

**Comment by dfang** [comment]
thanks.  but this is not what I mean.

for the best [performance](https://github.com/jdxcode/rtx#performance), I don't want auto check for rtx itself, rtx-plugins, rtx-apps(node,go that installed by rtx plugin), especially when I run `rtx ls`.  I think only checking for new versions when `rtx ls-remote xxx` or `rtx outdated` is reasonable. and if I want to update, I will run `rtx self-update` and `rtx plugin update` for myself.

so it would be great if there are some default environment  like `RTX_UPDATE_CHECK`, `RTX_PLUGINS_UPDATE_CHECK`, `RTX_APPS_UPDATE_CHECK` with default value 0.

what do you think?

**Comment by jdxcode** [comment]
there are no such checks

**Comment by dfang** [comment]
close ?

**Comment by dfang** [comment]
> it's timing out checking for new node versions. You can customize this with `RTX_FETCH_REMOTE_VERSIONS_TIMEOUT=10s`.

I don't understand why check new node versions when `rtx ls`, however I've upgraded rtx, I can't reproduce this issue.

**Comment by jdxcode** [comment]
When you install something it checks for new versions

**Comment by dfang** [comment]
I don't think it's necessary, at least I don't want this feature, and it may fail because of network issue. is there a way to disable this feature currently?

**Comment by ineu** [comment]
Automatic checks for updates might be convenient, but are definitely not something that should block the user's workflow. And when a shell takes 10 seconds just to launch in case of a poor internet connection, it does block the workflow. So there definitely should be an option to disable the checks at least for `rtx ls` or shell hooks, i.e. operations that do not *need* the internet connection. Obviously, `rtx install` or `rtx ls-remote` are useless without the internet connection, so such an option should be ignored in these commands.

**Comment by jdx** [comment]
I have not heard of any new reports about this so I assume it's resolved
