### ISSUE TITLE
Python: exclude tests folder by default (or config)

### ISSUE THREAD

**Issue by eugenesvk** [jdx/mise#691]
Half of Python's installation size of `rtx install python@3.12.0b4` is a mostly useless tests folder `lib/python3.12/test`
Is it possible to exlude that folder from installation via some kind of config https://github.com/python/cpython/issues/71827 (or maybe just autodelete it post-install if that previous one not posible)

**Comment by jdxcode** [comment]
I believe you should be able to do this today with the following:

```
CONFIGURE_OPTS=--disable-test-modules rtx install
```

**Comment by eugenesvk** [comment]
Oh, I see, thank you! What do you think of adding that as the default in rtx to make it more efficient without user effort (more waste should require more effort)?

**Comment by jdxcode** [comment]
I don't like the idea of modifying python-build's defaults.

**Comment by jdx** [comment]
new precompiled pythons won't have this directory
