### ISSUE TITLE
Automatically install tools when cd to a folder with config files

### ISSUE THREAD

**Issue by smikheiev** [jdx/mise#814]
Is there a way to automatically install tools (node, ruby, python, etc) when cd to a folder with `.rtx.toml` or `.nvmrc` or other configuration files? something like [this](https://github.com/nvm-sh/nvm#calling-nvm-use-automatically-in-a-directory-with-a-nvmrc-file) in nvm.

If it's not possible to do it now, do you think it's a good idea to add such a feature?

**Comment by jdxcode** [comment]
I believe you can set `RTX_MISSING_RUNTIME_BEHAVIOR=autoinstall`, however I've removed this from the documentation and I'm unsure if it's something I want to continue supporting forever.

**Comment by smikheiev** [comment]
thanks @jdx!

> I'm unsure if it's something I want to continue supporting forever

is there a reason for this? seems like a useful feature 🤔

**Comment by jdx** [comment]
`--yes` is a more elegant solution to most of what RTX_MISSING_RUNTIME_BEHAVIOR did—though it doesn't handle this exact use-case.

**Comment by jdx** [comment]
RTX_MISSING_RUNTIME_BEHAVIOR just adds a lot of complexity to the codebase for little benefit when `--yes` is available

**Comment by jdx** [comment]
with the new not_found handler I feel this probably isn't necessary anymore
