### ISSUE TITLE
SVG Logo for Simple Icons

### ISSUE THREAD

**Issue by 5ouma** [jdx/mise#845]
I found a nice rtx logo on README.
![logo-light.png](https://raw.githubusercontent.com/jdxcode/rtx/main/docs/logo-light.png)

How about adding this icon to [Simple Icons](https://simpleicons.org) to spread rtx more?
You need an SVG file for this icon which is a single path and has no color.
For more information, see [here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#5-check-the-icon).

**Comment by jdx** [comment]
the new logo wouldn't lend itself to vector art I'm afraid
