### ISSUE TITLE
rtx panics after timeout is handled

### ISSUE THREAD

**Issue by fiadliel** [jdx/mise#860]
When rtx tries to check latest tool versions (and perhaps other situations), it may panic after a timeout in update.

```
[WARN] rtx::toolset::tool_version_list: failed to resolve tool version: timed out: timed out waiting on channel
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: SendError { .. }
Location: src/timeout.rs:14
```

It looks like the background thread keeps running after timeout, and attempts to send the result over the mpsc channel.

I would expect rtx to exit cleanly (i.e. at least not unwrap the result).
Ideally, the background work would also be cancelled, but I guess since this currently runs on a thread, that's not necessarily trivial. 

**`rtx doctor` output**

```
rtx version:
  2023.8.9 macos-arm64 (2023-08-27)

build:
  Target: aarch64-apple-darwin
  Features: BREW, DEFAULT, NATIVE_TLS
  Built: Sun, 27 Aug 2023 19:10:04 +0000
  Rust Version: rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball)
  Profile: release

shell:
  /opt/homebrew/bin/fish
  fish, version 3.6.1

rtx data directory:
  /Users/xxx/.local/share/rtx

rtx environment variables:
  RTX_SHORTHANDS_FILE=~/.config/rtx/shorthands.toml
  RTX_SHELL=fish
  RTX_ENV=development

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "true", "jobs": "4", "legacy_version_file": "true", "legacy_version_file_disable_tools": "[]", "log_level": "INFO", "missing_runtime_behavior": "warn", "plugin_autoupdate_last_check_duration": "10080", "raw": "false", "shorthands_file": "/Users/xxx/.config/rtx/shorthands.toml", "trusted_config_paths": "[]", "verbose": "false", "yes": "false"}
```

**Comment by jdx** [comment]
I haven't used tokio before but I would assume it has some cancellation support

**Comment by fiadliel** [comment]
Yes - I understand that tasks are "detach on drop", but you can explicitly cancel with the join handle, and cancellations then occur at await points.
Futures, of course, stop being polled (and thus stop making progress) when dropped.
