### ISSUE TITLE
Allow increasing timeout from 10 seconds

### ISSUE THREAD

**Issue by jensbodal** [jdx/mise#865]
I'm currently on a slower connection and it takes about 12 seconds to run `./rtx/plugins/pnpm/bin/list-all`

I saw `RTX_FETCH_REMOTE_VERSIONS_TIMEOUT` [defaults to 10 seconds](https://github.com/jdx/rtx/blob/58b0e0e56f24fb12fae8d36cdf245dcec0808796/src/env.rs#L57), is it possible to configure this with an environment variable?

I played around with trying to set an environment variable for `RTX_FETCH_REMOTE_VERSIONS_TIMEOUT` but that resulted in some other errors.

**Comment by jensbodal** [comment]
Updated the title of this to hopefully make it more clear what the request is instead of the possible implementation detail

**Comment by MarioAriasC** [comment]
I managed to make it work like this:
```shell
export RTX_FETCH_REMOTE_VERSIONS_TIMEOUT="60 s"
```

**Comment by jdx** [comment]
I believe this functions now but let me know if that is not the case
