### ISSUE TITLE
Unable to set default runtime for Python with rtx

### ISSUE THREAD

**Issue by prabirkrsarkar** [jdx/mise#894]
**Describe the bug**

My new Ubuntu laptop had a preinstall Python 3.10.12. I used rtx to install versions 3.8.5 and 3.11 and set them as global default. However, after running it successfully I get a Python not found error with # python -V and $ python3 -V gives the preinstalled version 3.10.12!

**To Reproduce**
My environment: - 
# uname -a                                                                                                                         
Linux IN-JGQF1N3 6.2.0-32-generic #32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

# rtx use -g python@3.8.5 python@3.11                                                                                                   
Downloading Python-3.8.5.tar.xz...
-> https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tar.xz
Installing Python-3.8.5...
Installed Python-3.8.5 to /home/prasarkar/.local/share/rtx/installs/python/3.8.5
rtx python@3.8.5                                                                                                                                                 ✓ 2m Downloading Python-3.11.5.tar.xz...
-> https://www.python.org/ftp/python/3.11.5/Python-3.11.5.tar.xz
Installing Python-3.11.5...
Installed Python-3.11.5 to /home/prasarkar/.local/share/rtx/installs/python/3.11.5
rtx python@3.11.5                                                                                                                                                ✓ 2m rtx ~/.config/rtx/config.toml python@3.8.5 python@3.11

# cat ~/.config/rtx/config.toml                                                                                                     
[tools]
python = ["3.8.5", "3.11"]

# python -V                                                                                                                           
zsh: command not found: python

# python3.11 -V                                                                                                                      
zsh: command not found: python3.11

# python3 -V                                                                                                                      
Python 3.10.12

**Expected behavior**
# python -V
3.8.5

# python3.11 -V
3.11.5

**`rtx doctor` output**

```
 cat rtx_doctor.txt                                                                                                                1 ↵ ──(Wed,Sep13)─┘
rtx version:
  2023.9.0 linux-x64 (f333ac5 2023-09-05)

build:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Tue, 05 Sep 2023 14:21:04 +0000
  Rust Version: rustc 1.71.1 (eb26296b5 2023-08-03)
  Profile: release

shell:
  /usr/bin/zsh
  zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

rtx data directory:
  /home/prasarkar/.local/share/rtx

rtx environment variables:
  RTX_SHELL=zsh

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "false", "jobs": "4", "legacy_version_file": "true", "legacy_version_file_disable_tools": "[]", "log_level": "INFO", "missing_runtime_behavior": "warn", "plugin_autoupdate_last_check_duration": "10080", "raw": "false", "trusted_config_paths": "[]", "verbose": "false", "yes": "false"}

config files:
  /home/prasarkar/.config/rtx/config.toml
  /home/prasarkar/.tool-versions

plugins:
  go       (core)
  java     (core)
  node     (core)
  python   (core)
  ruby     (core)

toolset:
  python@3.8.5

1 problem found:
rtx is not activated, run `rtx activate` for setup instructions

```

**Additional context**
Ran rtx activate but that didn't fix the issue.

**Comment by jdx** [comment]
Please read the beginners guide so you can learn how to properly set up rtx https://dev.to/jdxcode/beginners-guide-to-rtx-ac4

**Comment by alhaiz313** [comment]
I am facing the same problem but with node. I have activated rtx as per the instructions but still no luck
rtx still indicates that it's not activated despite putting the right path for rtx
